### ISSUE TITLE
Can able to access ember data in inspector

### ISSUE THREAD

**Issue by SurenCraze** [emberjs/ember-inspector#1009]
I'm using google chrome, in ember inspector, everything is working except the data tab if I click it is not showing model's data

**Comment by rwwagner90** [comment]
@SurenCraze we need more info please. Ember version, ember-data version, etc. A reproducible test case would be great too.

**Comment by vronskiy** [comment]
same problem `Ember 1.13` `Data` tab in Ember inspector stopped working few days ago. Using MacOS and Chrome 76.0.3809.100.

**Comment by rwwagner90** [comment]
@vronskiy 1.13? Not 2.13 or 3.13? No one has provided enough info here to look into anything yet. Reproducible test cases are much appreciated!

If you are truly on 1.13, that is super old and we don't typically make changes to the old branches.

**Comment by belden** [comment]
@vronskiy I wonder if you're using an old version of ember-data alongside your Ember 1.13?. At work one of our applications uses Ember 1.12.2 with Ember-Data 1.0.0-beta.19.2. The `Data` tab in the Ember inspector stopped working until we started adding a `._debugContainerKey` to our models:

```js
import DS from 'ember-data';

const MyModel = DS.Model.extend({
  // ...whatever attrs here, etc
});

MyModel._debugContainerKey = 'model:my-model'; // ++ try adding this line to all your files
export default MyModel;
```

I found this solution by debugging the Ember inspector extension and observing a crash there; unfortunately I did this in January 2018 so don't have any specific debugging tips to help you out.

**Comment by rwwagner90** [comment]
@SurenCraze @vronskiy if you could please provide us with a reproduction, we would be happy to take a look, but there are a lot of different things that can change across apps, so it will be impossible to diagnose the problem without a repo or site we can look at.

**Comment by vronskiy** [comment]
@rwwagner90 Hi! The problem was typo in Ember data model relation name. So this tab stopped working. I'm sorry to trouble you!
