### ISSUE TITLE
How can I access application instance without Ember Inspector?

### ISSUE THREAD

**Issue by Krasiu** [emberjs/ember-inspector#1026]
Hello!

I have two questions regarding Ember apps.

Once Ember Inspector loads, I can go to console and access application instance like so:

`window.EmberInspector._application`

Is it possible to do without EmberInspector installed? (I need to do that on stripped version of Chrome via Selenium). Essentially, what does Ember Inspector do behind the scenes that makes accessing the application possible?

If that's impossible to do with just injecting JS, another solution would be to run Selenium with Ember Inspector installed. I have another problem here though:
`window.EmberInspector` is defined and accessible only after I click the "Ember" pane in DevTools - any workaround here? Can I somehow let Ember Inspector know that the page is loaded, and it can start doing it's magic?

Any help would be appreciated!

**Comment by chancancode** [comment]
Is this an app you have control of (can change its code) or any random app on the internet?

**Comment by Krasiu** [comment]
> Is this an app you have control of (can change its code) or any random app on the internet?

Any random app

**Comment by lifeart** [comment]
`Ember.Application.byName('emberweekly-issue-viewer')`

**Comment by rwwagner90** [comment]
@Krasiu does the suggestion by @lifeart work for you?

**Comment by chancancode** [comment]
I tested that today and can confirm that it works 😀
