### ISSUE TITLE
Integrate debug render tree

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1031]
The Ember work landed in https://github.com/emberjs/ember.js/pull/18372 which will be available in 3.14 beta shortly, which gives us ~ 6 weeks to integrate it 😬

I'm here to answer any questions!

**Comment by rwwagner90** [comment]
Thanks @chancancode! I'm planning to work on it this weekend and/or next week.

**Comment by chancancode** [comment]
Closed by #1088
