### ISSUE TITLE
using an old version of Ember message

### ISSUE THREAD

**Issue by jcthomas113** [emberjs/ember-inspector#1033]
I cannot use the ember extension, it is saying "You are using an old version of Ember". There is no other ember applications to choose from, how do I get this working?

"Allow access to file URLs" is checked.

Ember Version 3.11.0

![image](https://user-images.githubusercontent.com/12901969/65356362-ecd00800-dbb9-11e9-9a18-c1fd73d8a281.png)

**Comment by rwwagner90** [comment]
@jcthomas113 inspector should work fine. Have you tried hard refreshing the page with inspector open. Are there any errors in the console? Is there a reproduction we can look at?

**Comment by jcthomas113** [comment]
> @jcthomas113 inspector should work fine. Have you tried hard refreshing the page with inspector open. Are there any errors in the console? Is there a reproduction we can look at?

I have tried refreshing the page, with no luck. This is actually the case for myself and a few  other co-workers.

**Comment by rwwagner90** [comment]
@jcthomas113 can you please let me know if there are any errors in the console and can you please provide some sort of reproduction?

**Comment by rwwagner90** [comment]
@jcthomas113 were you able to get it to work?

**Comment by jcthomas113** [comment]
> @jcthomas113 were you able to get it to work?

yes, seems like the hard refresh worked.
