### ISSUE TITLE
ember-inspector keeps crashing and having to be reinstalled on 2.18 application

### ISSUE THREAD

**Issue by bretjb** [emberjs/ember-inspector#1041]
We're running Ember 2.18.2, and after the latest upgrade to ember-inspector 3.11, the extension keeps crashing. Chrome reports that, "the extension may have been corrupted" and then has to be repaired, which looks like it uninstalls and re-installs the extension.

This happens fairly frequently - seemingly once every time I close and re-open Chrome.

After cloning the repo and running the 3.12 version locally, I see the following error:
"Uncaught Error: Extension context invalidated."
The error is the line with the `>>>`
```
function listenToEmberDebugPort(emberDebugPort) {
    // listen for messages from EmberDebug, and pass them on to the background-script
    emberDebugPort.addEventListener('message', function(event) {
      >>> chrome.runtime.sendMessage(event.data);
    });
```

Please let me know if I can provide any other information.

**Comment by rwwagner90** [comment]
That doesn't sound like a line we would have changed. I suppose it is possible that Chrome updated and broke some APIs. @bretjb what version of Chrome are you on? Also, what are you doing in the inspector when the error occurs?

@nummi have you experienced anything like this?

**Comment by bretjb** [comment]
I'm not sure the error is related -- maybe it's something in the client files that's crashing, and that's the final location of the error.

I've seen the issue with both Chrome 76 and 77 on MacOS 10.14.5. Note: this is also happening to other members of my team with similar setups to mine (nearly latest/latest Chrome and Ember 2.18 with the latest ember-inspector).

**Comment by rwwagner90** [comment]
@bretjb could you try Firefox and see if Inspector crashes there too?

**Comment by rwwagner90** [comment]
@bretjb do you have a way for us to reproduce this?

**Comment by cadeParade** [comment]
Something similar happens to me also. I do not see the error in the console described above, but I do have to regularly "repair" the ember-inspector chrome extension. This happens to me and another person working on our app so I'm inclined to believe it's something about our app. Our app is on `ember-source: 3.12.0`, `ember-data: 3.13.1`.
I am running `ember-inspector v3.11.0`. in Chrome 76.0.3809.132. 
I will continue trying to get a repro case but it doesn't seem to happen after a specific thing -- it's usually something like I won't use it for a couple hours and when I come back, it doesn't show up in Chrome dev tools anymore and I have to open the Chrome extension window, click "repair", open a new tab and load my site again.

Our frontend is open source, you can find it here and run the tests (but that in itself does not seem to cause this failure case): https://github.com/percy/percy-web

I have not tried reproing in Firefox, I'll try to see if I get the same thing.

**Comment by nummi** [comment]
@cadeParade, do you know how long this has been happening?

Thanks @cadeParade, say hello to Mr. Briggs for me.

**Comment by cadeParade** [comment]
Hi @nummi thanks for your reply :)
It is a good question and I don't have a great answer. A couple of months at least. FWIW ~2 months ago we upgraded from ember-source 3.8 to 3.12. But @bretjb is seeing it on 2.18, so not sure if ember version would be the problem. 

I'll say hi to Derek :)

**Comment by PixelJanitor** [comment]
Mr. Briggs says hi back, @nummi 😁❤️

**Comment by cadeParade** [comment]
This seems to have resolved itself for me sometime since I last commented. I have upgraded to Chrome 78 since then, and have made no upgrades to any ember versions (source, data, cli). @bretjb if you upgrade to Chrome 78 does this problem go away?

**Comment by rwwagner90** [comment]
If anyone is still experiencing this on Ember 3.x, please let us know!
