### ISSUE TITLE
broccoli-babel-transpiler is opting out of caching

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#1043]
## Issue and Steps to Reproduce

  - `ember serve`
  - `[Concat: Test Support JS]broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: ...code ...`

## Your environment

Inspector `master` branch,
ember-cli `~3.13.0-beta.1`,
node `v10.15.0`,
Mac OS `10.14.6`

## Screenshots

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/3692/65822050-f88f8000-e1f2-11e9-8df1-cafe542bc0b0.png">

**Comment by rwwagner90** [comment]
We need to get on the latest broccoli-babel-transpiler. I have been trying unsuccessfully to get it to work. See https://github.com/emberjs/ember-inspector/pull/998

**Comment by rwwagner90** [comment]
@nummi I think this is fixed on latest?
