### ISSUE TITLE
component.get is not a function errors

### ISSUE THREAD

**Issue by habdelra** [emberjs/ember-inspector#1049]
## Issue and Steps to Reproduce
I'm using Ember 3.13.1 with octane enabled. When glimmer components on my page are rendered I encounter an error `component.get is not a function`. I confirmed that after I disable the ember inspector extension, the errors disappear.

I suspect that the ember inspector needs to be updated to handle glimmer components being emitted from Ember Octane, as apparently the API is different.

The ember application, whose components trigger this error is actually right here: https://github.com/cardstack/cardstack/tree/master/packages/cardhost

## Your environment
Ember 3.13.1 (with octane enabled)
Chrome Version 77.0.3865.90
Ember Inspector ver 3.11.0

## Screenshots
<img width="615" alt="Screen Shot 2019-10-07 at 1 14 33 PM" src="https://user-images.githubusercontent.com/61075/66334411-03d75f80-e907-11e9-8539-5412f80a964d.png">

**Comment by rwjblue** [comment]
I suspect this will be fixed once we land #1037, but @rwwagner90 would know better...

**Comment by rwwagner90** [comment]
Yeah, this should be fixed as part of that. We have a lot of changes to make to get that landed, so it might be a bit, but we are working on it!

**Comment by chancancode** [comment]
Should be closed by #1088 in the next release.
