### ISSUE TITLE
First visit to "Routes" table via "Routes" tab outputs JS error on app with engines.

### ISSUE THREAD

**Issue by GCheung55** [emberjs/ember-inspector#1054]
## Issue and Steps to Reproduce

  - The first visit to "Routes" table, by selecting the "Routes" tab, displays an empty table and outputs a JS error:
```
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: routeHandler.get is not a function
Stack trace: TypeError: routeHandler.get is not a function
    at o.buildSubTree (<anonymous>:4050:39)
    at o.<anonymous> (<anonymous>:3950:22)
    at Re.Ne.get (https://snapdragon-ws.fitbit.com/assets/vendor-617b03c28e2ef60d43021b01ddd6048c.js:3219:20)
    at Me (https://snapdragon-ws.fitbit.com/assets/vendor-617b03c28e2ef60d43021b01ddd6048c.js:3191:89)
    at o.get (https://snapdragon-ws.fitbit.com/assets/vendor-617b03c28e2ef60d43021b01ddd6048c.js:3828:58)
    at o.sendTree (<anonymous>:3956:30)
    at o.getTree (<anonymous>:3922:14)
    at h (https://snapdragon-ws.fitbit.com/assets/vendor-617b03c28e2ef60d43021b01ddd6048c.js:3070:111)
    at o.trigger (https://snapdragon-ws.fitbit.com/assets/vendor-617b03c28e2ef60d43021b01ddd6048c.js:3826:90)
    at <anonymous>:3502:14
```

Alternate clicks (14) between another tab and "Routes" tab will eventually have the table display data.

 May be related to #632 ?

  - Reproduction steps:
1. Go to https://www.fitbit.com/settings (You may need to create an account).
2. Open Ember-Inspector
3. Click on "Routes" tab

## Your environment

* Ember Version: 3.1
* Browser: Chrome 76.0.3809.100

## Screenshots

**The page to visit:** https://www.fitbit.com/settings
![image](https://user-images.githubusercontent.com/46033/67516490-99882400-f655-11e9-9c4f-7736f794fce3.png)

**Expected:** Table of routes, objects, and URLs are displayed.
![image](https://user-images.githubusercontent.com/46033/67516769-0f8c8b00-f656-11e9-8668-6a7cad9903a2.png)

**Actual:** Table is empty and JS error is output to console. Alternate clicks (14) between another tab and "Routes" tab will eventually have the table display data.
![image](https://user-images.githubusercontent.com/46033/67516579-bcb2d380-f655-11e9-8211-0041a4264918.png)

**Comment by rwwagner90** [comment]
Engines are not currently supported

**Comment by steventsao** [comment]
Mark this as duplicate to https://github.com/emberjs/ember-inspector/issues/632? @rwwagner90

**Comment by rwwagner90** [comment]
@steventsao yeah, I suppose they are basically the same ask, but this one does have some more context.

**Comment by RobbieTheWagner** [comment]
This must have been a timing issue. We use engines at work and I am able to access the Routes tab on the first click. Going to close for now, but please let us know if you are still experiencing issues!
