### ISSUE TITLE
full angle bracket name should be searchable

### ISSUE THREAD

**Issue by efx** [emberjs/ember-inspector#1059]
## Issue and Steps to Reproduce
This is a nuance to #1021. I expect to be able to search by the full component name, not just he first segment.
  - Navigate to [https://tv.apple.com/](https://tv.apple.com/)
  - Open ember inspector
  - go to the "Components" tab and type nav. You should see the `<NavHeader/>` result
  - type navh and you should see no results

## Your environment

stable chrome, latest ember inspector 

### expected
<img width="843" alt="expected_Screen Shot 2019-11-07 at 08 52 22" src="https://user-images.githubusercontent.com/472721/68394670-483f6080-013c-11ea-8b6f-d7e5d4cf9735.png">

### unexpected
<img width="1049" alt="unexpected_Screen Shot 2019-11-07 at 08 54 11" src="https://user-images.githubusercontent.com/472721/68394669-483f6080-013c-11ea-8039-a68f601aeabc.png">

I'd guess we are not correctly normalizing the entire component name for the case insensitive search. Hopefully it is a simple fix.

**Comment by rwwagner90** [comment]
> I'd guess we are not correctly normalizing the entire component name for the case insensitive search. Hopefully it is a simple fix.

Definitely sounds like that is the issue. @nummi mind taking a look?

**Comment by nummi** [comment]
Yeah, I’ll take a look today. This should be a quick one.

**Comment by nummi** [comment]
@rwwagner90, I think we should do a deploy. My fix for this is only on `master`.

**Comment by rwwagner90** [comment]
Ah gotcha. I will get a deploy out

**Comment by chancancode** [comment]
Can you test this on the latest (3.12.2) version?

**Comment by rwwagner90** [comment]
Fixed!
