### ISSUE TITLE
There's an empty void where the inspector should be

### ISSUE THREAD

**Issue by brian-c** [emberjs/ember-inspector#1064]
## Issue and Steps to Reproduce

It looks like the extension has a broken script hash. I'm not really up on extension development, so I hope this helps debug things:

- Visit https://emberjs.com/
- Right-click anywhere and select "Inspect Ember Component"
- The Ember inspector will open, but it's blank
- Right-click in the blank space where the Ember inspector should be and select "Inspect"
- An error appears twice in the new console that pops up:

`Failed to find a valid digest in the 'integrity' attribute for resource 'chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/panes-3-4-0/assets/ember-inspector.js' with computed SHA-256 integrity 'vRfOB+zwlqbAVgwg0e4YZW4qqbG899tr1UGDjEef21k='. The resource has been blocked.`

## Your environment

macOS 10.14.6
Chrome 78.0.3904.97
Ember Inspector 3.12.0

**Comment by rwwagner90** [comment]
We are aware, but do not know how to fix it yet.

**Comment by danilo-p** [comment]
Can you roll back to the latest stable version?

**Comment by chancancode** [comment]
#1065 should fix it, working on releasing it
