### ISSUE TITLE
Today's Update Broke the Extension

### ISSUE THREAD

**Issue by davidchalifoux** [emberjs/ember-inspector#1066]
## Issue and Steps to Reproduce

When opening the inspector on a valid Ember site, it doesn't load anything and is simply blank. I know there is at least one other person on the Ember Discord who is also experiencing this. There are no errors in the console or in the terminal.

## Your environment

Embe: 3.13.4
Ember Data: 3.13.1
Ember Inspector: 3.12.0

Chrome version 78.0.3904.97
Firefox (latest)

## Screenshots

![Screen Shot 2019-11-08 at 3 10 25 PM](https://user-images.githubusercontent.com/3289533/68507544-2a582580-023a-11ea-86f2-01dd98771c9f.png)

**Comment by rwjblue** [comment]
Thank you for reporting! Sorry about the trouble, the team is working to quickly correct the issue now. Hang tight, we'll get another update out soon...

**Comment by Ravenstine** [comment]
Reinstalling the add-on in Firefox seems to dislodge the problem.

**Comment by chancancode** [comment]
This should be fixed in the latest published version (3.12.2 in chrome and firefox)! Sorry about the trouble!
