### ISSUE TITLE
Inspector 3.12.2 not loading selected elements in right hand pane

### ISSUE THREAD

**Issue by pjcarly** [emberjs/ember-inspector#1071]
## Issue and Steps to Reproduce
 -  Make sure you are on version 3.12.2
  - Go to your Data tab, select a model type on the left with records in the store
  - Select a Model from the table
 -  Selected pane stays closed, if you open in manually from the top right. Nothing is selected

## Your environment

Happens on both latest Chrome and Firefox

## Screenshots

![Screenshot from 2019-11-09 01:49:15](https://user-images.githubusercontent.com/2808694/68519760-53f16b00-0293-11ea-80b9-aa96566e129a.png)

**Comment by rwwagner90** [comment]
Duplicate of https://github.com/emberjs/ember-inspector/issues/1068

**Comment by pjcarly** [comment]
Closing, and tracking progress on #1068
