### ISSUE TITLE
Mystery: why do we publish to NPM?

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1079]
We currently publish an `ember-inspector` package on NPM: https://www.npmjs.com/package/ember-inspector

It has all the source files in this repository, as well as the built output in `dist`.

Does anyone know why we publish this? Do you rely on this build in your team? Please let me know!

**Comment by rwwagner90** [comment]
@chancancode according to npm, the dependents are ember-electron and ember-remote-inspector. I suppose the use case is less for apps and more for installing into complex addons. For instance, ember-electron uses it to inject inspector into the DevTools in electron.

**Comment by chancancode** [comment]
Aha! Thank you! I’ll check those to make sure any tweaks I make to the build won’t break them!
