### ISSUE TITLE
Inspector does not recognize app if Ember.ENV.EXTEND_PROTOTYPES does not exist

### ISSUE THREAD

**Issue by jdrobertso** [emberjs/ember-inspector#1114]
## Issue and Steps to Reproduce

On opening Ember inspector on one of my Ember apps, I am getting the below stack trace.

raven.js:383 Uncaught TypeError: Cannot read property 'Array' of undefined
    at n.callback (<anonymous>:402:35)
    at n.exports (vendor-ff8d5821b66c1…b3ac1b81a4b902.js:3)
    at n._reify (vendor-ff8d5821b66c1…b3ac1b81a4b902.js:3)
    at n.reify (vendor-ff8d5821b66c1…b3ac1b81a4b902.js:3)
    at n.exports (vendor-ff8d5821b66c1…b3ac1b81a4b902.js:3)
    at requireModule (vendor-ff8d5821b66c1…b3ac1b81a4b902.js:3)
    at sendVersionMiss (<anonymous>:9612:19)
    at <anonymous>:9420:7
    at triggerOnce (<anonymous>:9493:7)
    at completed (<anonymous>:5962:7)
    at d (raven.js:379)

On debugging, I found that it hits the code mentioned in the PR [here](https://github.com/emberjs/ember-inspector/pull/1107). Specifically: `if (Ember.ENV.EXTEND_PROTOTYPES.Array)` is the line throwing the error. In my app, Ember.ENV.EXTEND_PROTOTYPES is undefined.

## Your environment

This issue is definitely present on the latest version of the Chrome Browser tool. On Firefox, the stack trace instead says `TypeError: Ember.ENV.EXTEND_PROTOTYPES is undefined`, but is essentially caused by the same issue. The Ember CLI version for the app is 2.5.0.

**Comment by rwwagner90** [comment]
@chancancode thoughts?

**Comment by chancancode** [comment]
Eh! Good catch, will fix soon!

**Comment by chancancode** [comment]
It's caused by this line: https://github.com/emberjs/ember-inspector/blob/47138779d4f6c559bda90a0e53df5838ac6da446/ember_debug/adapters/web-extension.js#L98. It should be `if (Ember.ENV.EXTEND_PROTOTYPES && Ember.ENV.EXTEND_PROTOTYPES.Array)`. If someone wants to send a pull request please go ahead, otherwise I'll do it in a few hours. Hoping to cut another patch release today to fix this and a few other minor issues.

**Comment by chancancode** [comment]
Working on it now!

**Comment by chancancode** [comment]
@jdrobertso what is the ember-source version of your app?

**Comment by jdrobertso** [comment]
@chancancode It looks like we are not using ember-source in that version of the app.

**Comment by chancancode** [comment]
I'm not exactly sure how this can happen, now that I think about it. Ember normalizes the `Ember.ENV.EXTEND_PROTOTYPES` into an object, and as far as I can tell, that code has been around for a long time, and it's definitely there on 3.4: https://github.com/emberjs/ember.js/blob/lts-3-4/packages/ember-environment/lib/env.ts#L166-L178

The way it's supposed to work (I could be wrong, cc @rwwagner90), is if your ember version is below that, it should switch to the old adapters, in which case this code shouldn't even run. But maybe the code is still loaded?

**Comment by chancancode** [comment]
@jdrobertso what is `Ember.VERSION`?

**Comment by jdrobertso** [comment]
@chancancode Apologies, I was going off the package.json ember-cli version. Ember.VERSION is 1.13.13.

**Comment by chancancode** [comment]
Fixed and published!
