### ISSUE TITLE
Component inspector description headers are [object Object]

### ISSUE THREAD

**Issue by afzal273** [emberjs/ember-inspector#1125]
## Issue and Steps to Reproduce
- Following ember guides for version 3.15 on Mac and Chrome version 79.0.3945.88, inspector version 3.13.1.
- When inspecting `Rental` component after Own Properties, the description just goes [object Object], screenshot attached.

## Screenshots
![2020-01-07_18-14-33](https://user-images.githubusercontent.com/8137882/71944902-11a4b700-317a-11ea-90d9-9b2889fac352.png)

**Comment by chancancode** [comment]
This is expected behavior as it’s the toString() output on glimmer components. We can think about ways to improve it though.

**Comment by patricklx** [comment]
Is this still an issue?
I think this has also been fixed by https://github.com/emberjs/ember-inspector/pull/1189

**Comment by rwwagner90** [comment]
Will assume this is fixed. If not, let us know!
