### ISSUE TITLE
Cannot read property 'PrototypeMixin' of undefined (in component inspector)

### ISSUE THREAD

**Issue by afzal273** [emberjs/ember-inspector#1126]
## Issue and Steps to Reproduce
- Using Ember v3.15 on OSX, Chrome version 79.0.3945.88, Ember inspector v 3.13.1.
- Following ember guides super rental tutorial.
- On clicking the parens next to args in own properties, it shows an error in console - Cannot read property 'PrototypeMixin' of undefined. Screen capture attached.

## Screenshots
![2020-01-07_18-27-37](https://user-images.githubusercontent.com/8137882/71945538-f20e8e00-317b-11ea-8217-229fd2ce3fa4.gif)

**Comment by patricklx** [comment]
@rwwagner90 this was fixed in https://github.com/emberjs/ember-inspector/pull/1149
