### ISSUE TITLE
Inspector breaks geocaching.com

### ISSUE THREAD

**Issue by sdahlbac** [emberjs/ember-inspector#1133]
Don't know exactly why, but having ember inspector enabled makes the geocaching.com site not working properly.

When enabled, I get warnings like 
```
'The resource https://www.google.com/recaptcha/api.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.'
```
 in the console.

## Issue and Steps to Reproduce

  - install ember inspector
  - navigate to e.g. https://coord.info/GC8J068 (might need an account...)
  - the map is not rendered
  - logs are not loaded

I guess one workaround is to only enable ember inspector on specific sites.

EDIT: it would help if localhost or http://localhost:4200 was possible to add...

![image](https://user-images.githubusercontent.com/659363/72327789-6f755980-36ba-11ea-9538-380b65e516aa.png)

## Your environment

Ember version, browser, etc.

ember inspector 3.13.1
osx 10.14.6 
chrome 79.0.3945.117

## Screenshots

![image](https://user-images.githubusercontent.com/659363/72327522-f1b14e00-36b9-11ea-84d0-8542e09a5ff2.png)

**Comment by rwwagner90** [comment]
I'm not really sure how just having, and not using Ember Inspector would cause issues. If you do not open up Ember Inspector, it should not cause any problems. If it is trying to run on every site before you click the Ember tab, we probably need to look into that.

**Comment by sdahlbac** [comment]
I don't really understand either but:

If I have the inspector set to click to enable, before clicking the page works, after enabling the site no longer works. (This is not an ember app AFAIK)

![inspector-click-to-enable](https://user-images.githubusercontent.com/659363/72352767-854f4280-36eb-11ea-9df0-92233f02e665.gif)


If I have the extension enabled on all sites

![image](https://user-images.githubusercontent.com/659363/72352893-c5aec080-36eb-11ea-9e7c-e59ca671aeaa.png)

the site is broken without going near the Ember tab?

**Comment by rwwagner90** [comment]
Is on all sites the default? I think we need to make it be when you click the extension.

**Comment by sdahlbac** [comment]
I don't remember changing it manually, but I guess it is possible that I remember poorly.

**Comment by chancancode** [comment]
I think this is probably fixed by #1136 (need to cut a release)

**Comment by rwwagner90** [comment]
@chancancode didn't #1136 only fix XML documents?

**Comment by chancancode** [comment]
It fixes the problem for anything that is not an HTML document. The problem in this case is an SVG document.

**Comment by rwwagner90** [comment]
@chancancode oh I had thought the fix only checked specifically for XML, that sounds like this should be fixed then.

**Comment by chancancode** [comment]
Hi @sdahlbac! We released a new version that should have fixed the issue, it's been published to the chrome/firefox store and should auto-update in your browser. Can you give it a try? I'll close this issue for now, if you are still experiencing the issue after the update, please comment here and I'll reopen the issue.
