### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1139]
Nightly builds are failing (Chrome):

```
Publish condition not met: To publish your item, you must provide mandatory privacy information. This can be done in the new Developer Dashboard.
```

This probably blocks cutting the next release.

**Comment by rwwagner90** [comment]
@chancancode I believe Firefox is unhappy with us as well. I don't think we should be publishing nightly versions perhaps. When we were manually cutting releases, we did not have these issues.

**Comment by chancancode** [comment]
It is not related to publishing nightly builds or not. This is a new requirement from the Chrome Web Store. Publishing manually wouldn't make a difference, we would just have found out about the problem much later without the nightly builds. Either way, both the nightly and the main inspector extension is marked as not publishable until this is resolved.

**Comment by rwwagner90** [comment]
@chancancode I was talking about Firefox. Never had an issue with publishing before, and now they are wanting a bunch of info like how to produce the minified output, what fastboot-fetch is etc.

**Comment by chancancode** [comment]
We don't publish nightly builds to AMO (I would like to, but we haven't worked out how to make it work yet), so it's not related. Generally, the browser vendors are all tightening up the requirements for extensions. Given what they have access to and what they can do, I think it's good that they do that, we'll just have to work with them on these issues.

Anyway, I'll work on this with @wycats next week to unblock publishing to Chrome; it looks like you may have replied to Firefox's requests? If not, I'm happy to help there too, just let me know.

**Comment by rwwagner90** [comment]
Yes, I replied, but have not heard back yet.

**Comment by chancancode** [comment]
We added the following to the Chrome Web Store developer dashboard:

* * *

### SINGLE PURPOSE

**Single Purpose Description:** Tool for debugging Ember applications.

### PERMISSION JUSTIFICATION

**Host Permission**: This extension runs code on every page to detect the presence of Ember applications and provide debugging functionality in the presence of an Ember application.

**Remote Code**: This extension doesn't use remote code, but the bundler that we use for JavaScript (webpack) packages JavaScript bundles as static strings that are loaded using eval().

* * * 

I tried running the webstore cli locally and confirmed that it cleared the warning. If the nightly build runs fine tomorrow, we can try tagging and publishing a new version.

**Comment by rwwagner90** [comment]
Awesome, thanks @chancancode! Do we need to do something similar for FF?

**Comment by chancancode** [comment]
I don’t _think_ so, the extension was still listed as approved, I guess we will find out when publishing it again

**Comment by chancancode** [comment]
We are published on the Chrome store again!
