### ISSUE TITLE
Implement Keyboard Navigation in the Component Tree

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-inspector#1142]
## Issue and Steps to Reproduce

  - Describe your issue, stack trace, etc.

Left, Down, Up, Right arrows do not close, move down, move up, or open the component tree

  - Can you tell us how to reproduce it? Is there a site we can go to, [Ember Twiddle](https://ember-twiddle.com), [CodeSandbox](https://codesandbox.io)?

Point at component, try navigating via arrow keys

## Your environment

Ember version, browser, etc.

3.12.1 / chrome

## Screenshots

closed source :(

**Comment by kangax** [comment]
Would love to have this as well. Coming from React devtools, this is much needed for quick navigation within a tree (including collapsing/expanding subtrees).

**Comment by rwwagner90** [comment]
@NullVoxPopuli @kangax do either of you have time to give implementing this a try? I'm happy to help with guidance on how it could be implemented, but I won't be able to take a look at it myself for at least a couple weeks.

**Comment by nummi** [comment]
I'll take it. :wave:

**Comment by nummi** [comment]
@NullVoxPopuli https://github.com/emberjs/ember-inspector/pull/1153 — if you have time please review!

**Comment by NullVoxPopuli** [comment]
@nummi I can provide feedback once released. My weekend computer isn't great at dev yet. (still trying to figure that out)

**Comment by kangax** [comment]
Thanks for adding this! Would love a new release with this change, thank you ❤️
