### ISSUE TITLE
No render times shown on Firefox

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-inspector#1143]
When using the "Render performance" section in Firefox (latest Ember Inspector version), no render times are shown at all for me. I see entries coming in, but "Render time" is always "-". It works for the same app in Chromium for me.

## Issue and Steps to Reproduce

- Go to "Render performance" in Firefox
- Click "Reload...." to start capturing render performance
- See items come in, but they have no time attached

## Your environment

Firefox on Ubuntu
Ember Inspector@3.13.1
Ember@3.16.1
Using Octane & Glimmer components

**Comment by RobbieTheWagner** [comment]
I just checked Firefox and Chrome on MacOS and the Render Performance tab seems to be mostly identical. I am going to close this, but please let us know if you are still having issues!
