### ISSUE TITLE
Inspector breaks filestack.com account dashboard

### ISSUE THREAD

**Issue by joshjeppson** [emberjs/ember-inspector#1145]
## Issue and Steps to Reproduce

 - install ember inspector
 - go to https://www.filestack.com/
 - sign up for an account and login
 - none of the graphs are rendered, some links break, etc.
 - similar to issue #1133 - workaround of enabling for specific sites only is not viable given that localhost is not considered a valid web address
 - I initially opened an issue with Filestack themselves. They of course blamed ember inspector. I've encouraged them to mitigate the issue on their side.

## Your environment

ember inspector 3.13.1
windows 10 pro 1909
chrome 79.0.3945.130

**Comment by chancancode** [comment]
Will try to cut a new release this week

**Comment by chancancode** [comment]
Hi @joshjeppson! We released a new version that should have fixed the issue, it's been published to the chrome/firefox store and should auto-update in your browser. Can you give it a try? I'll close this issue for now, if you are still experiencing the issue after the update, please comment here and I'll reopen the issue.

**Comment by joshjeppson** [comment]
This does appear to solve the issue. Thanks so much!
