### ISSUE TITLE
Upgrade to latest ember-{source,cli,data}

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1148]
Our daily build just failed because the browser took too long to start. In recent ember-cli, it changed the default in testem.js to set a longer timeout, so it should have with that (on top of just generally good to be using the latest stable release).

**Comment by rwwagner90** [comment]
@chancancode do you want me to update things or should we leave for new contributors?

**Comment by chancancode** [comment]
@rwwagner90 up to you! if you have time definitely feel free to do it, I'm just adding the label in case someone else wants to pick it up

**Comment by Windvis** [comment]
I'll give it a go!
