### ISSUE TITLE
Is it possible use ember-extension to dev chrome extension with emberjs

### ISSUE THREAD

**Issue by flyingsky** [emberjs/ember-inspector#115]
Hi,

Actually I tried to dev chrome extension with emberjs, but I cannot use the ember-extension to debug my chrome extension. Do you know how to do it?

BTW: do you use ember-extension to help you to dev ember-extension?

**Comment by rwwagner90** [comment]
Does anyone here have ideas on how to make iframes/extensions work?

**Comment by rwwagner90** [comment]
We will support extensions via the standalone app #881.
