### ISSUE TITLE
Cannot navigate to Data tab

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#1156]
## Issue and Steps to Reproduce

- Go to https://deprecations.emberjs.com/
- Try to click Data tab
- :boom: cannot navigate to Data tab

I think there is an issue when no models or data have been loaded. If you navigate to one of the deprecation pages the Data tab works.

**Comment by chancancode** [comment]
Still an issue as of v4.1.0, needs investigation

**Comment by roberkules** [comment]
also having this issue with version `4.3.4`

---

in my case I have a host app that's pretty bare bone and an engine app that contains the models, etc
trying to _hack_ it I also added ember-data and a dummy model to the host app, with no success.

**Comment by rwwagner90** [comment]
@roberkules inspector does not support engines, so that could be part of the problem for your case.

**Comment by jkallman** [comment]
I'm experiencing this after upgrading an app from Ember 3 to Ember 4. Our models are stored in an npm package referenced in the `devDependencies` of the app. They data tab worked previously when inspecting the Ember 3 version of the app. Could it be related to the new build system in Ember 4?

I'm happy to help with a pull request if anyone could point me in the direction of the code related to the Data tab. 😀

**Comment by rwwagner90** [comment]
@jkallman I don't think anything changed with builds in Ember 4. If you update to Embroider that might change things though. This is where data stuff lives https://github.com/emberjs/ember-inspector/blob/main/ember_debug/data-debug.js

**Comment by RobbieTheWagner** [comment]
I seem to be able to access the data tab on the deprecations page now, so going to close this. If anyone is still having issues, please let us know!
