### ISSUE TITLE
Error message: routeHandler.get is not a function

### ISSUE THREAD

**Issue by siva-sundar** [emberjs/ember-inspector#1173]
**Describe the bug**

Getting the following error while switching to the Routes tab of the inspector. No data is being shown on the Routes tab due to this error.

**To Reproduce**
1. Open Ember inspector 
2. Click on Routes
3. See the error `routeHandler.get is not a function` on the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/15258941/79546366-efdb9a00-80af-11ea-8882-10d620075327.png)

![image](https://user-images.githubusercontent.com/15258941/79546395-fd911f80-80af-11ea-827e-b002937727a1.png)

**Environment**
Ember version: 3.4.8
Browser: Chrome 80.0.3987.163

**Comment by rwwagner90** [comment]
The relevant code for this is here https://github.com/emberjs/ember-inspector/blob/f1ab36afb6abcdba53fb0180af5ed0203432dd73/ember_debug/route-debug.js#L166

@chancancode @pzuraq any reason why `getHandler` would be giving back a result that does not have a `get` method?

**Comment by VasylMarchuk** [comment]
I have this issue as well, and I thought it might be related to using `ember-engines`

<img width="371" alt="Знімок екрана 2020-04-23 о 23 10 05" src="https://user-images.githubusercontent.com/493875/80145290-9ea03e80-85b8-11ea-9233-0cfff25df175.png">

**Comment by rwwagner90** [comment]
@siva-sundar are you using engines as well?

**Comment by siva-sundar** [comment]
@rwwagner90 Yes

**Comment by siva-sundar** [comment]
The issue is that the routes tab will try to list all the route instances. But we are getting this error while trying to list the routes of an engine which is not mounted.

**Comment by siva-sundar** [comment]
The possible solution would be to lazily list the routes of engine once its mounted.

**Comment by rwwagner90** [comment]
@siva-sundar I do not know anything about engines, but if you have a fix in mind, we would welcome a PR to make this work! There is a lot to do to support engines in general, and we would love help from someone who uses them and knows about them.

**Comment by steventsao** [comment]
Supporting engines would resolve this issue. https://github.com/emberjs/ember-inspector/issues/632

`routeHandler.get is not a function` errors because `routeHandler` is an unresolved `Promise`.

**Comment by rwwagner90** [comment]
I don't know how to support engines. There was a spike by @cyril-sf at one point, but I don't think we ever got anything over the finish line. @chancancode I would be happy to pair with someone on engines support, I just have no idea how to make things work myself.

**Comment by cyril-sf** [comment]
@rwwagner90 Sorry for never finishing the feature. You can find my code (at least when I stopped) here : https://github.com/cyril-sf/ember-inspector/commit/ff5f26655130ba2eff61366f4bc39ce94185023f
