### ISSUE TITLE
Use of reopen clashes with an action of the same name

### ISSUE THREAD

**Issue by amk221** [emberjs/ember-inspector#1177]
**Describe the bug**
In our app we have a component that displays a Task (an ED model)
Tasks can completed, and reopened.

In the component there is an action called `reopen`

```javascript
@action
reopen() {
  // make PUT request...
}
```

There is a click handler to reopen a task.

I noticed that a PUT request was being made to reopen the task, even though I hadn't clicked anything.

After a bit of digging, it seems that there is some confusion between my reopen action, and Ember's Classic Object method `reopen`, and Ember inspectors usage of it. 

**To Reproduce**
Unsure, I tried to make a demo repo, but was unsuccessful.

**Expected behavior**
My reopen action should not be called. (I can fix this, by renaming it `reopenTask`, or uninstalling the Ember inspector)

**Screenshots**
<img width="532" alt="Screenshot 2020-04-29 at 13 53 00" src="https://user-images.githubusercontent.com/382061/80598666-9b2a0e80-8a21-11ea-854c-22d30a4c59d1.png">

**Environment**
Ember 3.16.1, Chrome 81

**Additional context**
N/A

**Comment by rwwagner90** [comment]
We've hit some issues before where people are trying to use a built in Ember method name as their own, and I believe our stance has been to recommend against using those names in your app. Can you confirm @chancancode @rwjblue?

**Comment by chancancode** [comment]
Hmm seems like we can just check for instanceof Ember.Object here?

**Comment by rwwagner90** [comment]
@chancancode arent't the retainedObject instances here components and such?

**Comment by chancancode** [comment]
Yes, but `Ember.Component` is a subclass of `Ember.Object` so it will work. More importantly, this code really is expecting the `reopen` method and semantics from `Ember.Object` specifically (and `willDestroy` as well),  so we should guard accordingly IMO.

That being said, I have some doubts about the correctness and necessity of this piece of code as written, I suspect we can refactor that into something better, e.g. doing the `isDestroyed` check when the object is being read, or just wrap `willDestroy` on the object directly (it's not using `this._super`, so I don't think `reopen` is adding a lot of value here). But we don't have to let this hold up the quick `instanceof` fix.

**Comment by rwwagner90** [comment]
@chancancode how does the `instanceof` check fix this problem? It sounds like @amk221 wants to have a method called `reopen` on an Ember component, so it would check if it's an instance of `Ember.Component`, and it still would be, so it would still call the method right?

**Comment by chancancode** [comment]
Oh, I am assuming @amk221 is talking about a *glimmer component*, which does not have a `reopen` method (which is why the guard will work). On the other hand, if you override an existing Ember.Object method and give it completely different semantics, then yes, all hell will break loose 💣

**Comment by amk221** [comment]
The component in question is actually:

```javascript
import Component from '@ember/component
import { action } from '@ember/object';
export default class TaskModalComponent extends Component {
  @action
  reopen() { }
}
```

**Comment by chancancode** [comment]
Eh, in that case, definitely don't do that! It's the same problem as naming an action `init`, `willDestroy`, `_super`, etc. `reopen` is a method that exists on the super class (`Ember.Object`) that has a specific meaning, if you override it and do something completely different and/or not call `super`, things will break. So this is probably going to be a won't fix.

That being said, we probably still want to add the `instanceof` guard (and tests) in this place and others that we are assuming `Ember.Object` semantics, so we don't break glimmer components or other POJOs that happen to have an unrelated method with the same name.

**Comment by amk221** [comment]
That's fine, thanks.

I guess originally I thought `@action` would be doing something like the old `actions` hash under the hood, thereby keeping is separate from the _actual_ `reopen`. But, now I understand more about it. Makes sense, I'll just rename it.

Thanks

**Comment by rwwagner90** [comment]
@amk221 to my knowledge, the `@action` decorator solely binds the `this` context. Closing this, since overriding built in component methods is not supported.
