### ISSUE TITLE
Proposal: left column shrink on breakpoint

### ISSUE THREAD

**Issue by ansmonjol** [emberjs/ember-inspector#1183]
**Is your feature request related to a problem? Please describe.**
Difficulties to make my window fit both application and ember-inspector while it's expanded on a small screen.

<img width="400" alt="Screenshot 2020-05-02 at 15 18 29" src="https://user-images.githubusercontent.com/5517077/80866003-afbe0f00-8c8c-11ea-8832-1860fb66174e.png">

**Describe the solution you'd like**
I would love the left bar in ember-inspector to be automatically shrink on some conditions.

<img width="400" alt="Screenshot 2020-05-02 at 15 16 02" src="https://user-images.githubusercontent.com/5517077/80866025-cd8b7400-8c8c-11ea-94ae-e2b64ab166d8.png">

**Describe alternatives you've considered**
Want to shrink the left sidebar bellow a certain devtools width
AND
When `inspectorExpanded` is true (while digging into a data row attributes for example c.f. screenshot 1)

**Additional context**
The breakpoint to shrink the sidebar would be 885px (750+135)
I chose this one regarding the width when Chrome devtools moves the CSS section from the bottom to the right of the devtools container (750px) in `Elements` section. 
And the hidden part of the sidebar that will be visible again after `750px` in `ember-inspector` section (135px).

<img width="200" alt="Screenshot 15 16 02" src="https://user-images.githubusercontent.com/5517077/80866472-265c0c00-8c8f-11ea-8d94-ca87df4a5a71.jpg">

I would also love to have another breakpoint when the inspector is fully expended  (`inspectorExpanded === true`) and if the `ember-inspector` width in below `1125px`. I have chosen this width regarding the situation where I can have 3 data columns displayed and the inspector fully expended.

<img width="600" alt="Qonto - dev 2020-05-02 16-14-37" src="https://user-images.githubusercontent.com/5517077/80866656-26104080-8c90-11ea-86d4-127a0a0d2e16.png">

Also, we should not forget to add a `title` to the sidebar section links so we can find the section name while hovering the icons.

We can directly interact with the first `Ui::DraggableColumn` in `application.hbs`.

And I would be very happy to do it !

**Future possibilities**
 Some other ideas for the future.

I was wondering if you guys have ideas regarding making `ember-inspector` fully responsive or make a full redesign of it.

**Comment by rwwagner90** [comment]
@nummi recently mocked up a collapsed column and some new ideas around responsive design. Please feel free to work together on a solution here 😄

**Comment by nummi** [comment]
Here are the latest mockups:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/3692/81005109-46f8a300-8e02-11ea-8c8c-f61698062770.png">
<img width="182" alt="image" src="https://user-images.githubusercontent.com/3692/81005125-4eb84780-8e02-11ea-889b-c501f27ca208.png">

<img width="57" alt="image" src="https://user-images.githubusercontent.com/3692/81005241-7ad3c880-8e02-11ea-878a-24693fb9f33b.png">

**Comment by ansmonjol** [comment]
Awesome ! Let me know how I can help. 
I'm on discord with the same name if you want.

**Comment by nummi** [comment]
This was implemented a while back 🥳
