### ISSUE TITLE
Make Available to Opera?

### ISSUE THREAD

**Issue by WMeldon** [emberjs/ember-inspector#119]
I'm not sure if this is known, but the Chrome Version of this works perfectly on Opera.

```opera:extensions```, and then the exact steps for Chrome and you're good to go.  

They have an extensions gallery so it would be pretty cool to add it there.  At the very least, it's probably something worth documenting.

**Comment by acorncom** [comment]
@WMeldon Is this something you'd still be interested in working on or should we close the issue for now?

**Comment by locks** [comment]
@WMeldon I will be closing this in one week as we still don't have enough bandwidth to take this head.

**Comment by jjff55** [comment]
Opera has reappeared in the browser market. After fist days of usage I have to say, it is really fast and is more enchanting than others now, at least for me. So I'm missing the ember-inspector.

**Comment by locks** [comment]
You can install Chrome extensions in Opera, can you try that and see if it works?
