### ISSUE TITLE
Component tree: input component arguents serialization

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember-inspector#1191]
![image](https://user-images.githubusercontent.com/1360552/81323009-68c18680-909d-11ea-944e-3c7d3f0fded4.png)

ARGS looks confusing for non exp devs & non-inspectable

can be tests in <https://ember-twiddle.com/a1a1448823aad56dfdd4615b0e5bf0b8?openFiles=templates.components.mega-input%5C.hbs%2C>

**Comment by lifeart** [comment]
Also, `_TextField` looks like private component, and I think it shoul be filtered.

Additional checks: `<Textarea />` component

**Comment by chancancode** [comment]
I’m not 100% sure what to do about this. It doesn’t seem great to just hide this.

**Comment by rwwagner90** [comment]
@chancancode perhaps we could show built in components differently somehow?
