### ISSUE TITLE
Inspecting query params objects errors

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1192]
Clicking on the `@query` argument in `<LinkTo @query={{...}}>` errors. This is probably not specific to query params, but any `Object.create(null)` in general. The problem seems to be that somewhere we are expecting the object to have a `toString()`.

**Comment by rwwagner90** [comment]
@chancancode any chance the fix from https://github.com/emberjs/ember-inspector/pull/1189/files also fixes this?

**Comment by chancancode** [comment]
Ah, quite possible. I will try after the nightly build ships!

**Comment by chancancode** [comment]
I can confirm that this has been fixed in v4.1.0. Thanks @patricklx and @rwwagner90!
