### ISSUE TITLE
Component Tree - dissapears if modal-dialog used and focused using component explorer

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember-inspector#1195]
Issue is: part of component tree disappearing after focus on component.

* all items outside ember-wormhole

----

![image](https://user-images.githubusercontent.com/1360552/81430096-89561300-9167-11ea-9d6b-f16b3498e8ff.png)
![image](https://user-images.githubusercontent.com/1360552/81430148-a12d9700-9167-11ea-8d49-b73386bf623d.png)

---

Step 1:
![image](https://user-images.githubusercontent.com/1360552/81428233-a89f7100-9164-11ea-8527-d2b44c785876.png)

Step 2: 
select visuble part of component using component selection button (inside EmberModalDialogPositionedContainer)
![image](https://user-images.githubusercontent.com/1360552/81428294-bf45c800-9164-11ea-80b5-25a6276a1261.png)

![image](https://user-images.githubusercontent.com/1360552/81428465-f4521a80-9164-11ea-8fb1-1496e8120148.png)

Step 3:
See part of tree disappeared
![image](https://user-images.githubusercontent.com/1360552/81428560-10ee5280-9165-11ea-8c15-e9315a7be8c2.png)

Test:
http://31.184.253.199/
admin@admin.com / admin
and open http://31.184.253.199/groups/2/series/2/exercise/10/task/10

**Comment by lifeart** [comment]
after "glitch" data tab remains broken 
![image](https://user-images.githubusercontent.com/1360552/81431365-af7cb280-9169-11ea-9098-361aabdf7311.png)

(no rows)

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/81431522-eeab0380-9169-11ea-9642-dc6abb20d2ca.png)

**Comment by chancancode** [comment]
According to @lifeart this is indeed fixed by #1196!
