### ISSUE TITLE
Upgrade to eslint-plugin-ember latest (v8)

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-inspector#1197]
I had to remove that part from #1196 because there were too many failures to triage, but we should get on the latest, even if it means we have to add a bunch of pending files to the config and move one bit at a time! Definitely help wanted!

**Comment by rwwagner90** [comment]
@chancancode I plan to work on updating all the things to latest and greatest Octane and glimmer components, so tackling this would be a good first step. I'll do some of this in the coming week.

**Comment by chancancode** [comment]
@rwwagner90 Nice! We can land any changes that you have incrementally too, so don't feel like you have to do it all at once.
