### ISSUE TITLE
Support for Ember Apps used in chrome extensions

### ISSUE THREAD

**Issue by oliw** [emberjs/ember-inspector#1234]
**Is your feature request related to a problem? Please describe.**
I'm developing a chrome extension that is an Ember App; as far as I can tell the Ember Inspector isn't able to detect it as an ember app because the chrome extension is served with the `chrome-extension://` URL, and Ember Inspector only likes `http://` and `file://`

**Describe the solution you'd like**
It would be cool if the Ember Inspector recognized Ember Apps used in Chrome Extension pages.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/1246970/83359867-fc4f4580-a331-11ea-8e59-32cb16ca8615.png)

**Comment by patricklx** [comment]
that will not be possible. Ember Inspector already injects itself into all supported urls: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#all_urls
the only way is with the bookmarklet

**Comment by apellerano-pw** [comment]
I think this could be possible, but not automatic. Each browser extension would have to integrate special code and opt-in.

They could communicate to ember-inspector via a public API listening at `runtime.onMessageExternal`, and provide whatever context ember-inspector needs to do its job.

**Comment by RobbieTheWagner** [comment]
I'm going to close this for now, but if anyone wants to take a stab at figuring it out, please feel free!
