### ISSUE TITLE
Feature request: route search 

### ISSUE THREAD

**Issue by okolehao** [emberjs/ember-inspector#129]
Nearly every page would be nice to have a generic text search or filter option.   As the amount of 
data collects, it would be nice. 

![image](https://f.cloud.github.com/assets/3718695/2401445/24153276-aa16-11e3-99ef-64ca9c33a2e3.png)

**Comment by lauraannwilliams** [comment]
Just adding my +1 for this. Finding the route/components used is a little difficult when there are a lot of items in the list.

**Comment by stefanpenner** [comment]
Ya this is a great idea, just a reminder to folks. Ember-inspector is itself an ember-app, if you can write and ember-app you may actually have fun adding this to the ember-inspector.

**Comment by nummi** [comment]
@rwwagner90 close?

**Comment by rwwagner90** [comment]
@nummi we do not have search in the routes tab. I'll see if I can add it real quick

**Comment by rwwagner90** [comment]
This is done now. Thanks @nummi!
