### ISSUE TITLE
View Tree completely empty

### ISSUE THREAD

**Issue by nickfedoroff** [emberjs/ember-inspector#135]
I'm not sure when I lost it, but as some point, the View Tree stopped showing anything at all. The other tabs (Routes, Data, Promises) all work as expected. 

In a different project, the View Tree works fine.Are there know scenarios in which the View Tree will break?

![screen shot 2014-03-18 at 5 06 04 pm](https://f.cloud.github.com/assets/1442451/2455245/d9488baa-aefa-11e3-8532-f9bc59cb17d3.png)

**Comment by adambuczynski** [comment]
It seems this issue is still impacting us. Anything I can do to check what's happening?

The command listed above triggers an error:
```js
window.Ember.Debug.viewDebug.viewTree()
```

VM25018:2 Uncaught TypeError: Cannot read property 'viewDebug' of undefined(…)
