### ISSUE TITLE
Info tab no longer reporting my addon

### ISSUE THREAD

**Issue by k3n** [emberjs/ember-inspector#1351]
**Describe the bug**
My addon (+version) is no longer being reported in the `Info` tab.

**To Reproduce**
1. Go to `Info`
2. Observe missing app

**Expected behavior**
Previously, it reported my addon (which is being served as an app) in the libraries, e.g. `MyApp v1.2.3`.

**Environment**
Ember v3.4.8, latest Chrome on Mac

**Additional context**
This was working on Ember v2.18, but after upgrading it appears to have gone missing. I see recommendations to use `Ember.Libraries.register(name, version)`, but that's something we've never had to do previously, so this feels like a bug.

**Comment by rwwagner90** [comment]
@k3n I'm not sure I understand your setup. How is an addon served as an app? Versions of all addons are not shown in info by default. Were you using https://github.com/ember-cli/ember-cli-app-version to add the version?

**Comment by k3n** [comment]
> Were you using https://github.com/ember-cli/ember-cli-app-version to add the version?

D'oh! That was it. Sorry for the support question, don't know how that slipped my mind. Thank you.
