### ISSUE TITLE
Component tree does not allow inspecting of template-only components' args (but does allow inspecting single-arg non-primitives)

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-inspector#1387]
**Describe the bug**
- Clicking a template only component does not open the sidebar 
- clicking args on template only components does not open the sidebar
   - UPDATE: non-primitve args show up in the sidebar

![template-only-component-no-sidebar](https://user-images.githubusercontent.com/199018/97241664-25ccaa00-17c8-11eb-992c-7f3c63551293.gif)
The template-only component is `<NestedComponent />`

**To Reproduce**
1.  create a template-only component, pass some args
2. inspect it with ember-inspector
3. click on the component -- sidebar doesn't open
4. click on an arg -- sidebar doesn't open (handy moreso for non-primitive args)

**Expected behavior**
Sidebar opens the same way it does for class-backed components

**Environment**
Ember 3.18.x
FireFox 83.0b3 (as I inspect this, I see I have a pending update! woo!)

**Comment by NullVoxPopuli** [comment]
From Discord discussion, if not opening the sidebar for template-only components is intended (because no instance to inspect), it'd be helpful to have that shown somewhere -- right now there is no feedback after clicking.

That just leaves the issue of template-only arg inspection

**Comment by NullVoxPopuli** [comment]
I confirm that if the arg is a non-primitive that the sidebar opens, and I can inspect it.

So _now_ the only issue remaining is that when there are lots of args on a component, there is no way to inspect them all (which could be handy for horizontal scrolling avoidance)

**Comment by NullVoxPopuli** [comment]
Ok, so here is the real issue that this Issue#1387 is about: 
![arg-inspection-issue](https://user-images.githubusercontent.com/199018/97242331-f9b22880-17c9-11eb-8765-39ffa98cf563.gif)

**Comment by MrChocolatine** [comment]
I noticed the same issue, the sidebar does not open up when clicking on a Template-Only component from the tree view.

**Comment by rwwagner90** [comment]
I believe this is not something we can fix, since there is no backing class for template only componenets. @chancancode please confirm.

**Comment by MrChocolatine** [comment]
@rwwagner90 I never looked at the codebase but, just a quick idea (perhaps silly), since the tree view render the Template-Only components, like any other component, with the arguments `@someArg={{...}}`, isn't possible to use that and generate what is necessary in the sidebar?
