### ISSUE TITLE
Unable to see model or controller name in ember-inspector

### ISSUE THREAD

**Issue by v--b** [emberjs/ember-inspector#1395]
**Describe the bug**
Recently upgrade ember version to 2.2 and unable to see model or controller name in the ember-inspector tab. clicking on $E doesn't work either.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6865263/98507703-f9c31700-2212-11eb-8fc7-4e449dd06d89.png)

**Environment**
Ember version 2.2 browser- chrome
**Additional context**

**Comment by rwwagner90** [comment]
@chancancode since Ember 2.2 is quite old now, do we intend to still provide support and fixes?

**Comment by chancancode** [comment]
Yeah I think unfortunately we probably don't have the resources to look into that, especially since Ember.js 2.2 itself hasn't been supported by the core team for a long time. Sorry!
