### ISSUE TITLE
Use resolvers lookup description for generated routes/controllers/etc

### ISSUE THREAD

**Issue by ulisesrmzroche** [emberjs/ember-inspector#140]
https://github.com/emberjs/ember.js/issues/4654

**Comment by locks** [comment]
This should be currently addressed as we're using the resolver's [`describe`](https://github.com/emberjs/ember-inspector/blob/44e820f1a21090ea081c4c8fca9a79840a0a9ded/ember_debug/route-debug.js#L80)
