### ISSUE TITLE
Unable to toggle or resize columns

### ISSUE THREAD

**Issue by yemartin** [emberjs/ember-inspector#1401]
**Describe the bug**
Trying to resize or toggle columns does not work:
- for resizing, the cursor does not change to a drag cursor when hovering over the column separator, and attempting to drag anyway does nothing.
- right-clicking on the column headers shows the browser right-click menu instead of the column selector.

**To Reproduce**
1. Go to the Routes tab
2. Hover over a column delimiter (cursor does not change)
3. Attempt to drag a column delimiter (column does not resize)
4. Right click on a column header (browser right-click menu appears)

**Expected behavior**
In 2.: the cursor to change to a drag cursor
In 3.: the column to resize
In 4.: the column selection popup to appear

**Screenshots**
<img width="491" alt="ember-inspector-cannot-toggle-columns" src="https://user-images.githubusercontent.com/139002/99161366-ed6c1c00-2734-11eb-832a-d61bebcffb1a.png">

**Environment**
OS: macOS Catalina 10.15.7
Browser 1: Firefox Developer Edition 83.0b10
Browser 2: Chrome 86.0.4240.193
Ember-Inspector: 4.3.4

**Additional context**
The following issue seems relevant, but it was fixed in 2018: #815

**Comment by RobbieTheWagner** [comment]
@yemartin sorry for the extremely long time not responding to this. Resizing seems to be working as intended for me. Did we ever support toggling columns on and off? cc @patricklx

**Comment by RobbieTheWagner** [comment]
@yemartin what version of Ember are you on?

**Comment by yemartin** [comment]
@RobbieTheWagner 

Ember itself is probably ancient, since it's a fairly old project. Here is a screenshot:

<img width="566" alt="Screenshot 2024-05-03 at 13 00 01" src="https://github.com/emberjs/ember-inspector/assets/139002/4e16e5dd-0f33-41fc-8eeb-ccd0fac34ec6">

Intersetingly, I see Ember Inspector in this screenshot shows `1.10.0`, even though the browser extension version is `4.11.0`. Not sure if that's normal (is there a server-side component to Ember Inspector?).

**Comment by RobbieTheWagner** [comment]
> @RobbieTheWagner 
> 
> 
> 
> Ember itself is probably ancient, since it's a fairly old project. Here is a screenshot:
> 
> 
> 
> <img width="566" alt="Screenshot 2024-05-03 at 13 00 01" src="https://github.com/emberjs/ember-inspector/assets/139002/4e16e5dd-0f33-41fc-8eeb-ccd0fac34ec6">
> 
> 
> 
> Intersetingly, I see Ember Inspector in this screenshot shows `1.10.0`, even though the browser extension version is `4.11.0`. Not sure if that's normal (is there a server-side component to Ember Inspector?).

@yemartin yes, we lock versions and older versions don't get any updates. So any apps on less than 3.16 will not get any of the newer changes.
