### ISSUE TITLE
Current model actions

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember-inspector#143]
- [ ] save
- [ ] delete

**Comment by rwwagner90** [comment]
@locks @stefanpenner @teddyzeenny  what is this issue about?

**Comment by teddyzeenny** [comment]
I don't recall, could it be adding the ability to save/delete ED model instances from the inspector directly?

**Comment by rwwagner90** [comment]
@stefanpenner do you remember what this is about?

**Comment by rwwagner90** [comment]
We're going to assume this meant implement save and delete for models in the Inspector. We think this could be a good idea, and will look into it.

**Comment by rwwagner90** [comment]
We're closing this in favor of #480
