### ISSUE TITLE
Use while debugger paused

### ISSUE THREAD

**Issue by neverfox** [emberjs/ember-inspector#146]
Maybe this isn't possible given that the extension itself is code running in the browser, but it would be nice to have more functionality while the debugger is paused. I'd love to be able to view the Routes, Data and Promises tab when I hit a breakpoint, but that doesn't seem to work. If you're already on one of the tabs, it doesn't go blank, but if you switch tabs, you cannot switch back (with the exception of the View Tree tab, for some reason). Currently, the inspector is only really useful during periods when the app is naturally at rest, rather than during transitions etc. where you'd need to pause to catch what's going on.

**Comment by locks** [comment]
This seems untenable at the moment. As there's other work with more priority, we're shelving this for a future research.
