### ISSUE TITLE
Object inspector visibility is not persisted

### ISSUE THREAD

**Issue by kangax** [emberjs/ember-inspector#1536]
**Describe the bug**
When navigating through the tree of components/routes/etc. the object inspector closes for some of them. It's unclear why or when this happens.

**To Reproduce**
1. Go to https://ember-super-rentals.netlify.app/
2. Navigate and focus on `<Rental ...` component
4. Observe the object inspector getting hidden

**Expected behavior**
I would expect object inspector to be visible unless explicitly hidden (using a toggle on the right).

**Screenshots**
![Screen Shot 2021-03-23 at 13 15 59](https://user-images.githubusercontent.com/383/112191402-5c261e00-8bdc-11eb-97d7-15292039f337.png)
![Screen Shot 2021-03-23 at 13 15 50](https://user-images.githubusercontent.com/383/112191404-5cbeb480-8bdc-11eb-8120-32307b3f7c10.png)

**Environment**
Ember inspector 4.3.5, Ember 3.25.3

**Comment by rwwagner90** [comment]
@kangax this is likely due to https://github.com/emberjs/ember-inspector/issues/1387. Template only components have no backing class, so they sidebar does not open for them.

**Comment by rwwagner90** [comment]
I suppose we could think about keeping it open, but showing a message like `template only components are not supported in object inspector at this time` or something. @chancancode @pzuraq @nummi any thoughts?
