### ISSUE TITLE
Better keyboard navigation & devtools consistency

### ISSUE THREAD

**Issue by kangax** [emberjs/ember-inspector#1537]
**Is your feature request related to a problem? Please describe.**

The recently added keyboard navigation in the components inspector is great but is often hard to work with because it doesn't follow the behavior of devtools that many developers are used to. Not only is it inconsistent but it also lacks functionality that makes it easy to navigate to the parent with one keypress in chunks of trees with many children.

**Describe the solution you'd like**

To mimic devtools behavior: 
- in collapsed view **right arrow** should expand the element (this is implemented)
- in expanded view **left arrow** should collapse the element (this is implemented)
- in expanded view **right arrow** should jump to the first child
- in collapsed view **left arrow** should jump to the parent

Note that both Chrome and Firefox have the same behavior.

**Comment by nummi** [comment]
@kangax Thanks for the feedback. Would you be interested in submitting a PR for this?

**Comment by kangax** [comment]
@nummi I'd love to look into this but unsure I'll have much time in the near future. I'll post here if something changes.

**Comment by rwwagner90** [comment]
@kangax happy to help if you have questions on this. Would love to get a PR going!

**Comment by kangax** [comment]
Not a problem. Thanks for contributing!

**Comment by geneukum** [comment]
OK, I opened up a PR with a first cut at the changes here: https://github.com/emberjs/ember-inspector/pull/1959. 

I'm definitely happy to make any changes that are desirable to get this integrated. Thanks all!!

**Comment by geneukum** [comment]
@rwwagner90, I think that this could be closed out, but it might be nice just to have @kangax sanity check the changes just to make sure that the updated keybindings work as expected?

**Comment by kangax** [comment]
@geneukum I can check but not sure if master was cut into a release yet?

**Comment by geneukum** [comment]
@kangax Ah, yeah, it doesn't look like it. I think that you'd need to [build from source and then install that](https://github.com/emberjs/ember-inspector/blob/master/README.md#installation) in order to be able to test these changes out.

I understand that's definitely a bit more involved though... We could always just close this issue out and then file a separate issue if there are any additional desired changes in the future.

**Comment by rwwagner90** [comment]
Closing this issue for now. Will try to get a release out soon.
