### ISSUE TITLE
Ember App Not Detected Chrome 

### ISSUE THREAD

**Issue by Sergio16T** [emberjs/ember-inspector#1539]
Ember Application is not detected in chrome. Was working a couple weeks ago. No longer detecting application.

**Comment by rwwagner90** [comment]
@Sergio16T what site is it? Is it public? Without a reproduction, there is not much we can do.

**Comment by Sergio16T** [comment]
I updated my google-chrome browser and that resolved the issue. It was for a private project in development. Thank you.

**Comment by chasegiunta** [comment]
@Sergio16T @rwwagner90 Also got this btw. New ember dev tools couldn't detect app on `Version 89.0.4389.90 (Official Build) (x86_64)`. Updating to `Version 90.0.4430.212` seemed to fix it.

**Comment by chasegiunta** [comment]
Though, considering how old this issue is, it might have just been the browser needed a restart. Ignore me.
