### ISSUE TITLE
Allow Column Resizing in inspector

### ISSUE THREAD

**Issue by JasonAllenCorns** [emberjs/ember-inspector#161]
Steps to Reproduce
 1. access an Ember SPA
 2. open inspector to Ember tab
 3. access "View Tree" or "Routes" tab
 4. observe columns and related headers

Expected
 * Column widths are customizable (resizable) via click-and-drag

Actual
 * Column widths are fixed, obscuring text for nested routes, practically any model name, controller name, etc.
![screen shot 2014-05-20 at 10 46 27 am](https://cloud.githubusercontent.com/assets/3839416/3030936/c1b9f4b0-e046-11e3-87b2-864b4cc037f8.png)

**Comment by koryteg** [comment]
this would be amazing. it would also be nice to show show hide and show different columns.

**Comment by knownasilya** [comment]
Any way to help implement this?

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/574
