### ISSUE TITLE
Ember Inspector tests failing with Ember 4.x

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#1704]
We seem to be getting `Ember is not defined` for all tests for beta and canary, which are currently 4.x.

**Comment by rwwagner90** [comment]
@vlascik you are correct that Ember globals are gone, but you are not correct that we use them extensively. We use a util to require the module when available https://github.com/emberjs/ember-inspector/blob/master/ember_debug/utils/ember.js

**Comment by vlascik** [comment]
That just masks the issue, you'd still have to fix all imports anyway. 

https://github.com/ember-codemods/ember-modules-codemod might be able to help?

**Comment by rwwagner90** [comment]
@vlascik no it does not, it fixes the issue. I'm not sure you are understanding how inspector works. For ember_debug it uses the Ember version from your app, so it has to use `requireModule` or `window` to get Ember from your app, normal imports you are referring to are not correct.

**Comment by vlascik** [comment]
Opening the inspector on an app with ember 3.28 just shown 37 deprecation warnings similar to these

`DEPRECATION: Using computed.equal has been deprecated. Instead, import the value directly from @ember/object/computed:
  import { equal } from '@ember/object/computed'; [deprecation id: deprecated-run-loop-and-computed-dot-access]
`

`DEPRECATION: Using computed.or has been deprecated. Instead, import the value directly from @ember/object/computed:
  import { or } from '@ember/object/computed'; [deprecation id: deprecated-run-loop-and-computed-dot-access]`

`DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead. [deprecation id: ember-global] See https://deprecations.emberjs.com/v3.x/#toc_ember-global for more details.`

So, not sure this is fixed already.

There is now a check on Ember global to prevent from destructuring from the global object too, and there is plenty of code using that in ember-debug.

https://github.com/emberjs/ember-inspector/blob/ebe7393c04b70ba9846b9daa412cde29afb08ff4/ember_debug/container-debug.js#L3-L6

I imagine this is the cause.

Anyway, I really have no idea how inspector works or how to fix these, just tried to point out that the current way of accessing the Ember object also floods the console with deprecations.

**Comment by rwwagner90** [comment]
@vlascik once again, ember_debug is the way it is for a reason. It must use Ember from the app. Your suggestions are impossible.
