### ISSUE TITLE
Boiler plate for Cross browser extensions

### ISSUE THREAD

**Issue by rvramesh** [emberjs/ember-inspector#175]
I have heard good things about ember-inspector from https://hacks.mozilla.org/2013/12/ember-inspector-on-a-firefox-near-you-2/ . Wondering if you can create a boilerplate or a starter project for writing cross browser extensions and publish basic guidelines on architecture it would be great for newbies to get into extension development.

Thanks

**Comment by locks** [comment]
Hi @rvramesh. Sorry for the late reply, but at the moment we don't have bandwidth to create and maintain such a project, though I believe someone made an addon that solves that problem. Check [Ember Observer](https://emberobserver.com/)!
