### ISSUE TITLE
4.5.2 seems to be broken

### ISSUE THREAD

**Issue by pomm0** [emberjs/ember-inspector#1797]
**Describe the bug**
Ember inspector addon remains white when opening in chrome. In addons console I see this error:

```
Uncaught Error: Could not find module `element-resize-detector` imported from `ember-inspector/modifiers/did-resize`
```

**To Reproduce**
1. Open ember inspector

**Expected behavior**
The ember inspector works as usual 

**Screenshots**
![image](https://user-images.githubusercontent.com/6084030/142372657-d35ace4b-3ae2-4ff9-8a77-d28d88153b17.png)
(Right console is that from the addon)

**Environment**
Ember version: 3.20.7
Browser version: Version 95.0.4638.69 (Official Build) (64-bit)
Ember-inspector: 4.5.2

**Additional context**
-

**Comment by eduscrakozabrus** [comment]
Yes. Release has bug

VM1561:9888 Uncaught TypeError: Cannot read properties of undefined (reading 'VERSION')
    at <anonymous>:9888:28
    at triggerOnce (<anonymous>:9973:7)
    at <anonymous>:9984:7
    at runLoadHooks (lazy_load.js:75)
    at index.js:507
    at internalRequire (loader.js:54)
    at require (loader.js:87)
    at rsvp.js:2493
    at rsvp.js:2493

**Comment by Andrik264** [comment]
Chrome is up to date
Version 96.0.4664.45 (Official Build) (x86_64)
Ember Inspector version 4.5.2
```
VM126:9888 Uncaught TypeError: Cannot read properties of undefined (reading 'VERSION')
    at <anonymous>:9888:28
    at triggerOnce (<anonymous>:9973:7)
    at <anonymous>:9984:7
    at runLoadHooks (lazy_load.js:75)
    at Module.callback (index.js:520)
    at Module.exports (loader.js:106)
    at requireModule (loader.js:27)
    at r (loader.js:176)
    at get (index.js:10)
    at get (index.js:41)
  ```
![image](https://user-images.githubusercontent.com/69592267/142391116-77365378-28c1-4d47-8ab8-3f26a42cff9d.png)
![image](https://user-images.githubusercontent.com/69592267/142391182-f2cfde63-c3f1-46a1-90bd-ef9e856b2bf2.png)

**Comment by drallieiv** [comment]
Is there any way to force the extension to a previous version ?

**Comment by artursmirnov** [comment]
@drallieiv probably the most straight forward way would be to download the extension source code from the [releases page](https://github.com/emberjs/ember-inspector/releases/tag/v4.5.0), unpack it, build and install following the [guide in README](https://github.com/emberjs/ember-inspector#chrome).

**Comment by NullVoxPopuli** [comment]
Looks like the chunks aren't loading: 
![image](https://user-images.githubusercontent.com/199018/142434972-dc1b7b08-7aac-4bb3-a9ad-78cd61e46bca.png)
