### ISSUE TITLE
Multiple Ember apps on the same page

### ISSUE THREAD

**Issue by ramybenaroya** [emberjs/ember-inspector#180]
My web app is instantiating 3  Ember apps (on the same page) and the inspector can inspect only the app that is created last. Is there any way to force the inspector to inspect a specific app by modifying some global variables on the page? Or in another way?
Thanks,
Ramy

**Comment by hbrysiewicz** [comment]
+1 working in another code base with several apps - would be nice to have an option to pick which app in the inspector

**Comment by meirish** [comment]
I'd love to help with this, but don't have any knowledge of the codebase. Would you be willing to give an outline of how you see it working / list of things that would need to be done and then I could take a pass at it?

**Comment by rwwagner90** [comment]
Does anyone still need this and have the bandwidth to help implement it? I think that it might be easier to just run your apps separately, and inspect that way.

**Comment by rwwagner90** [comment]
We feel that engines are the path forward for running multiple apps in one page, so we are going to focus our efforts there.
