### ISSUE TITLE
Clicking any Ember Data model throws error

### ISSUE THREAD

**Issue by pjcarly** [emberjs/ember-inspector#1812]
**Describe the bug**
When trying to inspect the Ember Data store through Ember Inspector, I click the data tab, see a list of models present. If I then click any of the models in the list, an error is thrown by Ember Inspector, and the model is not loaded in the right panel.

**To Reproduce**
1. Open any Ember app with data in the store
2. Click on the Data tab
3. Select a model in the list view

**Stack trace**

```
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
Stack trace: TypeError: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
    at isInternalProperty (<anonymous>:4708:101)
    at addProperties (<anonymous>:4619:11)
    at ownProperties (<anonymous>:4596:12)
    at n.mixinDetailsForObject (<anonymous>:4384:21)
    at n.mixinsForObject (<anonymous>:4430:31)
    at n.sendObject (<anonymous>:4260:26)
    at n.inspectModel (<anonymous>:791:30)
    at b (https://getflights.com/assets/vendor-475803ed4a10495a95beaf31401ccdf4.js:1835:40)
    at n.trigger (https://getflights.com/assets/vendor-475803ed4a10495a95beaf31401ccdf4.js:2624:266)
    at <anonymous>:5079:16
```

**Environment**
Ember version: 3.24.4
Ember data: 3.24.2
Ember Inspector: 4.5.3

**Additional context**

**Comment by rwwagner90** [comment]
This does not seem like an issue with inspector, since we don't have `LEGACY_OWNER` anywhere in our code. I am guessing `isInternalProperty` is something in ember-data itself? @runspired do you happen to know?

**Comment by Windvis** [comment]
I think it _is_ an Ember inspector error: https://github.com/emberjs/ember-inspector/blob/5cf62aeeab56c13752e27e3f8c8a7c5fd072f086/ember_debug/object-inspector.js#L1027-L1032
That code seems to have been introduced with this PR: https://github.com/emberjs/ember-inspector/pull/1721 so it's fairly recent.

It calls `any` on an array, but that only works if prototype extensions is enabled. Converting that to the `some` equivalent should fix it I think?

It doesn't only happen when clicking on records, but all things that should open the sidebar with extra properties.

**Comment by pjcarly** [comment]
Small update, it seems to happen on about anything I try to load in the right panel

- A service through container -> services
- A router or Controller through Routes
- A component through Components

**Comment by rwwagner90** [comment]
Ah, thanks @Windvis, you are correct! Yes, converting to `.some` should work. Would you be interested in opening a PR?

**Comment by Windvis** [comment]
@rwwagner90 Sure thing! I wonder why this wasn't caught in CI though. It looks like there is a [job which disables the prototype extensions](https://github.com/emberjs/ember-inspector/blob/7001198197b73038071537c7affb628798bd935d/.github/workflows/build.yml#L95) already. Are there tests which check if clicking rows opens the sidebar? Any idea why that piece of code wouldn't have been hit during that job?

**Comment by rwwagner90** [comment]
@Windvis My guess would be that our tests don't adequately test things or are setup incorrectly.

**Comment by Windvis** [comment]
@Windvis I think it's because of this filter: https://github.com/emberjs/ember-inspector/blob/7001198197b73038071537c7affb628798bd935d/.github/workflows/build.yml#L116

Only the `Ember Debug` prefixed tests are run. When I run the tests locally with `NO_EXTEND_PROTOTYPES` enabled more things seem to break. I assume it wasn't noticed since disabling the prototype extensions probably isn't that common.

**Comment by rwwagner90** [comment]
@Windvis that is on purpose. ember_debug is what runs in the context of your Ember app. All the inspector app code itself we control and it shouldn't have these issues.

**Comment by kevinkehl** [comment]
@rwwagner90 can we get a release with this fix? The failure mode is pretty impactful :(

**Comment by rwwagner90** [comment]
@kevinkehl I have been trying, but we have some flaky things happening in CI, so releases haven't been succeeding.
