### ISSUE TITLE
Error: Module: 'ember-debug/utils/ember/array' not found.

### ISSUE THREAD

**Issue by mjuniper** [emberjs/ember-inspector#1841]
**Describe the bug**
When I try to use ember inspector it says, "Ember application not detected!" and I see errors in the console (Error: Module: 'ember-debug/utils/ember/array' not found). This is an application that we have been developing for years and this only started happening recently.

**To Reproduce**
1. Go to 'https://hubqa.arcgis.com/'
2. Open dev tools
3. Click the Ember tab
4. Observe the "Ember application not detected" message
5. Go to the console tab
6. Observe script errors

**Expected behavior**
Ember inspector loads and no errors in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/942837/145858536-63ea8f0a-e3b2-4ef7-a565-a8ccaf133bd6.png)

**Environment**
Ember 3.16.6
Chrome 96.0.4664.55

**Additional context**

**Comment by rwwagner90** [comment]
@mjuniper what inspector version?

**Comment by mjuniper** [comment]
> @mjuniper what inspector version?

4.5.3

**Comment by MrBuBBLs** [comment]
We seem to have a similar issue here :
![image](https://user-images.githubusercontent.com/130635/146013162-e77dcbdb-ef76-488d-bf6f-4853c12f5b31.png)

We tried with the latest (dev) inspector.

**Environment**
Ember-inspector [DEV] 4.5.7
Ember 3.12.2
Chrome 96.0.4664.93

**Comment by rwwagner90** [comment]
I see that it looks like both of you are getting these errors from jquery. @chancancode do we need to ship `@ember/jquery` as part of inspector so we don't break things for users still relying on `Ember.$` etc?

**Comment by rwwagner90** [comment]
I was able to reproduce this issue and opened a PR with the fix.

**Comment by mjuniper** [comment]
Yeah, we've moved away from jquery for any new development but it's gonna be a while before we can completely remove it. Also, I think we may use some addons that still require it. Thanks for addressing this!

**Comment by mjuniper** [comment]
I see that the PR was merged and there was a release. I'm wondering when we can expect to see this actually show up in the chrome extension (i don't have any idea what is involved in that)?

**Comment by rwwagner90** [comment]
@mjuniper there has not been a release. We've been having a lot of problems with releases not working. I do not have an ETA on when we'll have it sorted out.
