### ISSUE TITLE
No entries for model in Data tab after infinite revalidation error

### ISSUE THREAD

**Issue by ross-kahn** [emberjs/ember-inspector#1869]
**Describe the bug**
There's a bug in my code I'm trying to figure out (description [here](https://stackoverflow.com/questions/70560915/infinite-revalidation-error-in-model-hook-when-changing-routes-ember-js)) that's causing an infinite revalidation error. When this error occurs, I have Item records loaded in the store. The application is using the records just fine, but the inspector is showing nothing in the store for that model.

**To Reproduce**
The error comes from calling findRecord in an unrelated model hook (e.g. finding Items in the Inventory route) in a loop on more than one record which hasn't already been loaded into the store. 

**Expected behavior**
It might be expected that the error would cause inconsistencies in the inspector, in which case this bug can be closed. But I thought the fact that the inspector shows 18 records loaded in the Model Types column and nothing in the actual data pane was strange.

**Screenshots**
![Infinite revalidation error](https://i.imgur.com/o7wwCPA.png)
![Emebr inspector](https://i.imgur.com/QVRmwMN.png)

**Environment**
Ember                 : 3.26.2
Ember Data            : 3.26.0
Ember Model Validator : 3.10.0
EmberFire             : 3.0.0-rc.6
Firebase              : 7.20.0
Chrome: 96.0.4664.110 x64

**Comment by rwwagner90** [comment]
@ross-kahn I think once you fix the bug in your code, things should be fixed in inspector, so I would be inclined to say this is not an inspector bug.

**Comment by ross-kahn** [comment]
That's fair, I'll close this. Thanks!
