### ISSUE TITLE
The inspector seems to influence Ember Data record creation

### ISSUE THREAD

**Issue by Windvis** [emberjs/ember-inspector#1898]
**Describe the bug**
We have a route that creates certain records when they don't exist yet. We assign them default values on creation by passing data into the `createRecord` method. For example; 
```js
store.createRecord('model-name', {
    someAttribute: 'Hello',
});
```
I noticed that sometimes the initial values aren't set correctly and I couldn't figure out why. Eventually I realized it's caused by having the inspector open when the page loads. If I close the dev tools, reload, open the data tab and look at the values, everything works. If I do the same without first closing the dev tools, the values aren't set. What's even more strange is that it only seems to happen for the first record that's created this way. The second one _does_ have the values we pass into it.

It's also not just a visual bug, the value hasn't actually been stored in the record so `record.someAttribute` will return undefined.

Another thing I noticed is that first creating the record before setting the value doesn't have the same issue:
```js
let record = store.createRecord('model-name');
record.someAttribute = 'hello';
```

That will always work, no matter if the dev tools are open when reloading. If you then create a second record with the initial value object, that still works as expected which makes me think it might be a timing issue?

I'll try to create a reproduction to see if it's related to our setup or not.

**To Reproduce**
1. Create new records with initial values 
2. Reload the page with the dev tools activated
3. Go to the data tab and verify that not all default values have been set.

**Expected behavior**
The dev tools do not affect application code.

**Screenshots**
Reloading the page with the dev tools closed:
![image](https://user-images.githubusercontent.com/3533236/151978050-75636516-21e9-446d-a135-7295e75a6c9a.png)

Reloading the page with the dev tools open ("Primary" is missing)
![image](https://user-images.githubusercontent.com/3533236/151977971-3019382a-fa3a-45d0-b927-0987357f7e33.png)

**Environment**
Ember version, browser, etc.
Ember 3.26, Firefox 96

**Additional context**

**Comment by lifeart** [comment]
May be related to: https://github.com/emberjs/ember-inspector/issues/1875

**Comment by patricklx** [comment]
the fixes for #1875 should also fix this

**Comment by schorke** [comment]
Just had the issue with:

- Ember Inspector 4.9.1
- "ember-data": "~3.27.1"

This bug should be re-opened 🤷‍♂️

**Comment by patricklx** [comment]
I think you need at least ember data 3.28, which includes the fix
