### ISSUE TITLE
Ember Debug - Route Tree | Route tree test occasionally fails

### ISSUE THREAD

**Issue by geneukum** [emberjs/ember-inspector#1999]
**Describe the bug**
When running the "Route tree" test case from the "Ember Debug - Route Tree" test suite, I occasionally see failures with the assertion:
```
50: assert.equal(name, 'route:routeTree');
```
where the diff reported is:
```
Expected: | "route:routeTree"
Result: | "view:renderTree"
```

**To Reproduce**
Use `yarn run test` or `ember test -s` to run this test case several times, it will probably end up failing at least once.  

**Expected behavior**
The test should pass consistently. 

**Screenshots**
n/a

**Environment**
master branch, Chrome Version 101.0.4951.54 (Official Build) (x86_64 translated)

**Comment by geneukum** [comment]
After stepping through the issue a bit, it appears that we are not guaranteed to receive the "view:renderTree" message  before we:
```
47: run(EmberDebug.port, 'trigger', 'route:getTree');
```

If the "view:renderTree" message has come in before we trigger "route:getTree", the test seems to pass. Otherwise, the "view:renderTree" message can come in after the "route:routeTree" message and overwrite the stashed result which eventually causes the failed assertion.

**Comment by rwwagner90** [comment]
@geneukum I think your fix sounds great!
