### ISSUE TITLE
Output to JSBin/JSFiddle

### ISSUE THREAD

**Issue by leepfrog** [emberjs/ember-inspector#2]
Not sure if fiddle or jsbin has an API, but it would be pretty rad if you could export your current controller/view/route to jsbin/fiddle.

Not quite sure how this would work -- or even the specifics of it.  But the goal is to try to get some useful template / starting point with relevant code into a fiddle for diagnosis.

**Comment by kavika13** [comment]
http://doc.jsfiddle.net/use/gist_read.html - this tells how to create a fiddle once you've created a gist, so exporting to a gist would definitely get us there.

**Comment by locks** [comment]
Hi, thanks for the feedback.
As @eccegordo mentions, this doesn't sound like a plausible feature to be implemented. I'm closing this issue, we'll revisit if a way forward pops up.
