### ISSUE TITLE
Clear button on Deprecations Toolbar  does not clear deprecations

### ISSUE THREAD

**Issue by geneukum** [emberjs/ember-inspector#2000]
**Describe the bug**
When I navigate to the "Deprecations" tab and force a deprecation in my app, it will show up in the deprecations panel as expected. However, if I click the 'clear' button (the prohibition sign), the deprecation remains visible in the deprecations panel. 

**To Reproduce**
1. Open the ember inspector
2. Navigate to the deprecations tab 
3. Cause a deprecation to occur in your application, observe that it appears in the deprecations panel 
4. Click the "clear" button in the toolbar, notice that deprecation is still showing 

**Expected behavior**
I would expect this button in the deprecations toolbar to clear all of the deprecations shown in the panel, similarly to how this button works in the "Promises" tab for example.

**Screenshots**
Here is a gif showing the behavior in the deprecations tab versus the behavior in the promises tab.
![deprecate](https://user-images.githubusercontent.com/50264607/167321991-0b9a2e64-a086-454d-ac6c-0d74b16d53f6.gif)

**Environment**
ember: 4.2.0,  chrome: Version 101.0.4951.54 (Official Build) (arm64)

**Additional context**
n/a

**Comment by rwwagner90** [comment]
@geneukum any errors in the console or anything indicating why it might not be triggered? Was the deprecations toolbar something we recently converted to glimmer or anything?

**Comment by geneukum** [comment]
@rwwagner90, sorry about that, there was a console error that I missed. The following shows up after clicking the clear button:
```
Uncaught TypeError: this.currentModel.clear is not a function
    at DeprecationsRoute.clear (deprecations.js:70:1)
    at Router.triggerEvent (router.js:1380:1)
    at PrivateRouter.triggerEvent (router.js:214:1)
    at PrivateRouter.trigger (router_js.js:2285:1)
    at Router.send (router.js:595:1)
    at DeprecationsController.send (action_handler.js:191:1)
    at Backburner._run (backburner.js:1052:1)
    at Backburner._join (backburner.js:1028:1)
    at Backburner.join (backburner.js:779:1)
    at join (index.js:168:1)
```

I took a stab at resolving this over in https://github.com/emberjs/ember-inspector/pull/2008, but any and all feedback is definitely welcome!
