### ISSUE TITLE
object inspector closes when i click anything on the website

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember-inspector#2013]
The object inspector closes when i click on anything on the website which i am debugging.
It should stay open so I can inspect the values in the component while interacting with the website.

**Expected behavior**
The Object Inspector should always be open.

**Environment**
Ember version: 4.4.0

the issue is probably here: 
https://github.com/emberjs/ember-inspector/blob/master/ember_debug/libs/view-inspection.js#L323
where hide is called if a component is pinned, and notification to the inspector is sent, which also hides the object inspector.
can we disable the notification?

**Comment by rwwagner90** [comment]
@patricklx when you say click on anything, do you mean clicking a component to inspect it or do you mean interacting with your app in general? I'm not entirely sure I am following the problem.

**Comment by patricklx** [comment]
I mean interacting with my app

**Comment by patricklx** [comment]
weird, it closes for me when i click on something. I noticed now that it does not close if the tooltip if the current selected component is NOT showing.
If there is a tooltip, then when i click somewhere, it closes the tooltip and the open object inspector

**Comment by patricklx** [comment]
https://user-images.githubusercontent.com/1332320/169776106-69e395f3-2207-43bb-b330-b688847a7bbc.mp4

**Comment by patricklx** [comment]
Any update on this?

**Comment by patricklx** [comment]
@rwwagner90 , probably the click handler in the file i pointed out earlier. https://github.com/emberjs/ember-inspector/blob/9aac4888c9de795a86a41d4105dd8c4a1c8d3cac/ember_debug/libs/view-inspection.js#L249.

and here https://github.com/emberjs/ember-inspector/blob/master/ember_debug/libs/view-inspection.js#L323 
It also checks if its inspecting. So probably component inspection enabled. But in the not inspecting case it also closes the object  inspector
