### ISSUE TITLE
Ember inspector not working unless I silent a deprecation 

### ISSUE THREAD

**Issue by dbendaou** [emberjs/ember-inspector#2014]
**Describe the bug**
My Ember inspector isn't working unless I add the following line to my `deprecation-workflow` file 
`{ handler: 'silence', matchId: 'ember.built-in-components.import' },`

At least 4 people are affected by the same issue in my company on this project 

Chrome Version 101.0.4951.64 (Official Build) (arm64)
Ember inspector version Version 4.5.11

**To Reproduce**
1. Go to any ember app on chrome 
2. Open inspector 
3. The Ember tab is showing this 
<img width="926" alt="Screenshot 2022-05-19 at 10 30 27" src="https://user-images.githubusercontent.com/15218861/169251330-b75655f2-bc09-4724-acbd-8602f8d8dd09.png">

**Expected behavior**
It should work without silencing the `{ handler: 'silence', matchId: 'ember.built-in-components.import' },`

**Environment**
Chrome Version 101.0.4951.64 (Official Build) (arm64)
Ember Inspector | 4.5.11
Ember | 3.28.9
Ember Data | 3.27.1

**Comment by rwwagner90** [comment]
Hi @dbendaou do you have a public facing app we can debug with? I tried going to https://music.apple.com/us/browse and the inspector is working as intended.

**Comment by aoumiri** [comment]
@rwwagner90 I wonder if the deprecation workflow is only available in dev mode? If that's the case, this can't be reproduced on https://music.apple.com/us/browse 🤔 

On my side, I can reproduce it on localhost, but on the production build the ember inspector works great.

**Comment by gerryster** [comment]
@dbendaou, what is your setting for `throwOnUnhandled` in your deprecation workflow? One observation in my application is that if I set this to `false` then the Inspector works. My theory is that the Inspector itself has the `ember.built-in-components.import` deprecation which becomes an exception based on the deprecation workflow setting. Note that [@ember/component/text-field](https://github.com/emberjs/ember-inspector/blob/v4.5.11/app/components/object-inspector/property-field.js#L1) is used by the inspector and not `@ember/legacy-built-in-components` as described in [the deprecation docs.](https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-import)

**Comment by dbendaou** [comment]
Yeah indeed mine is setup on `throwOnUnhandled: true,`

**Comment by wagenet** [comment]
@aoumiri this is because deprecations are stripped in production.
