### ISSUE TITLE
Ember application not detected!

### ISSUE THREAD

**Issue by melriffe** [emberjs/ember-inspector#2106]
**Describe the bug**
Opening the Ember Inspector on a locally running Ember application reports "Ember application not detected!".

**To Reproduce**
N/A

**Expected behavior**
I expect the Ember Inspector to detect the locally running Ember application.

**Screenshots**
<img width="1440" alt="Screen Shot 2022-08-18 at 13 50 46" src="https://user-images.githubusercontent.com/2241/185462349-69df8e79-6aec-4cad-b116-13f4f0ac3759.png">

**Environment**
Ember Inspect: 4.6.1
Ember: 3.24.6
Firefox: 103.0.2 (64-bit)
OS: macOS 12.5 (21G72)

**Additional context**
I believe this happened from a recent update. I noticed, when searching for extensions in FF the extension had been recently updated. I say this because yesterday the extension worked just fine.

**Comment by robertosequeira** [comment]
Same issue with

Ember: 3.23.0
Chrome: 104.0.5112.101
OS: macOS 12.5

**Comment by dylandpowers25** [comment]
Same issue with 

Ember: 3.12.4
Chrome: 104.0.5112.101
OS: macOS 12.5.1

**Comment by dylandpowers25** [comment]
Looks like this was fixed with https://github.com/emberjs/ember-inspector/pull/2105

**Comment by melriffe** [comment]
Looks like I just need to wait for 4.6.2 to propagate to my end of the internet. 😟

**Comment by dylandpowers25** [comment]
@melriffe https://github.com/emberjs/ember-inspector/issues/2104 provides a good workaround using a bookmarklet :) worked for me!

**Comment by melriffe** [comment]
Will give it a try. Thanks for the suggestion @dylandpowers25 

Closing this ticket.

**Comment by rwwagner90** [comment]
The release will never pass. We have to fix our Chrome token. We're well aware and have been manually uploading releases.

**Comment by melriffe** [comment]
Rather than reopen this ticket, since the team is well-aware of the problems, I just want to add the use of the bookmarklet didn't work for me. :(
