### ISSUE TITLE
Ember inspector not working in Chrome.

### ISSUE THREAD

**Issue by DhivyaJanakiraman** [emberjs/ember-inspector#2107]
**Describe the bug**
Ember inspector is not working in Chrome. 

**To Reproduce**
1. Install "Ember Inspector" chrome plugin.
2. Go to any website that is built using EmberJs (Eg www.linkedin.com)
3. Click on 'Ember' in dev tools
4. I see the "Ember application not detected!" message

**Expected behavior**
Ember inspector plugin used to work by displaying the tree view/components/routes etc for an ember application.

**Screenshots**
<img width="1072" alt="Screen Shot 2022-08-18 at 5 13 50 PM" src="https://user-images.githubusercontent.com/14121614/185516134-fdfe102f-de06-43fe-8dd7-c839df9782aa.png">

**Environment**
Ember - '3.28.9'
Browser - Chrome 104.0.5112.79

**Comment by latha-karbonhq** [comment]
Same for me.

**Comment by zion** [comment]
Noticed this today as well. Was working for me a few days ago though.

**Comment by sivaramanj95** [comment]
Same for me.

**Comment by DhivyaJanakiraman** [comment]
Yes not working in Firefox as well and it was working fine for me till couple of days back.
For now, I installed older version of ember-inspector 4.6.0 to get the plugin to work

**Comment by jamalrefaideen** [comment]
same for me

**Comment by reiallenramos** [comment]
For everyone affected by this, I got in touch with the devs and he said 4.6.2 is on Google's review process. I don't know how long that takes but if you are blocked you can install the zipped version manually.

https://github.com/emberjs/ember-inspector/releases/tag/v4.6.2

**Comment by Ganapathy77** [comment]
Does the older versions work fine

**Comment by chsanch** [comment]
I've just installed 4.6.2 but is not working (Firefox, Brave), meanwhile I'm just using the bookmarklet workaround commented here: https://github.com/emberjs/ember-inspector/issues/2104#issue-1342658879

**Comment by kprasadpvv** [comment]
@Ganapathy77 ,
Yes the older version 4.5.11 is working in chrome.

Follow below steps:
Download https://github.com/emberjs/ember-inspector/releases/tag/v4.5.11 the zip file and extract it.
Navigate to the folder in terminal and 
run yarn install
run yarn build to build the dist directory

Visit chrome://extensions/ in Chrome
Make sure Developer mode is checked
Click on 'Load unpacked extension...'
Choose the dist/chrome folder in the cloned repo
Close and re-open developer tools if it's already open

**Note:**
make sure only the manually loaded extension is only enabled. (i.e., disabled the 4.6.2)

**Comment by reiallenramos** [comment]
I'm still having issues despite updating to 4.6.3 and cannot perform kprasadpvv's workaround as my Chrome is managed by my admin.

**Comment by rwwagner90** [comment]
@reiallenramos are you sure you are on 4.6.3? It should work.

**Comment by reiallenramos** [comment]
@rwwagner90 hi, yes I'm on 4.6.3 and haven't been able to make it work again. Have tried reinstalling the extension with no luck.

![image](https://user-images.githubusercontent.com/26242729/186037755-fbda3473-d588-4926-8ff8-e8671855698e.png)
![image](https://user-images.githubusercontent.com/26242729/186037797-83920632-7f09-4c10-8336-684b5f2e4379.png)

**Comment by rwwagner90** [comment]
@NullVoxPopuli any ideas what would be different on Ubuntu?

**Comment by NullVoxPopuli** [comment]
on Firefox, I see no issues running on Ubuntu with 4.6.3
on Chrome, I see no issues running on Ubuntu with 4.6.3.

I tested with https://limber.glimdown.com -- which is running ember-source 4.6.0

**Comment by reiallenramos** [comment]
Tested also with https://limber.glimdown.com/ and it works! At least I know the bug is somewhere in our project setup. Thanks for the help @rwwagner90 @NullVoxPopuli

**Comment by rwwagner90** [comment]
@reiallenramos What Ember version are you on?

**Comment by reiallenramos** [comment]
@rwwagner90 Ember.VERSION 3.17.13

**Comment by reiallenramos** [comment]
In case someone, somewhere would have this issue too.
The app is throwing the following error. Removing the `ember` node module from package.json and rebuilding removed the warning and fixed Ember Inspector as well.
![image](https://user-images.githubusercontent.com/26242729/194990685-7d6da55f-552d-4759-aa38-777e2d78adc2.png)
