### ISSUE TITLE
embr inspector is not working in chrome. ember application not found is cuming.

### ISSUE THREAD

**Issue by reshmaresh02** [emberjs/ember-inspector#2110]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Ember version, browser, etc.

**Additional context**

**Comment by kprasadpvv** [comment]
Duplicate of https://github.com/emberjs/ember-inspector/issues/2107

Find the mitigation steps here.
https://github.com/emberjs/ember-inspector/issues/2107#issuecomment-1220695725
