### ISSUE TITLE
> $E  should print the toString of the object before letting chrome decide what to print

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember-inspector#214]
this will result in more helpful output.

**Comment by maheshsenni** [comment]
@stefanpenner @teddyzeenny something like this?

![screen shot 2015-04-04 at 6 41 33 pm](https://cloud.githubusercontent.com/assets/1472437/6992770/fa5a9a54-dafa-11e4-859c-1b2769506bd4.png)

**Comment by arjunkathuria** [comment]
@locks ping! 
got some time on my hands next 1-2 days, can you please define the issue for me, like you do. 😼

**Comment by locks** [comment]
@arjunkathuria you need to find the place where the logic of the `$E` binding to the console is, and make it also log the `toString` of the object, so we have a better idea what it is.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/614
