### ISSUE TITLE
Detect Ember Application in jsbin and jsfiddle

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#22]

**Comment by kavika13** [comment]
This seems to be broken again, in both (at least on Chrome 39.0.2171.95 (64-bit) it is):

- http://jsfiddle.net/j1njm36w/ (recent fiddle I created to update main Ember CONTRIBUTING.md)
- http://emberjs.jsbin.com/

The inspector does not detect the Ember app in either for me, but does detect it properly if run against my local Ember-Cli app server.

**Comment by kavika13** [comment]
It's working fine in Firefox 34.0.5 though.
I'm running on OSX for both.

**Comment by teddyzeenny** [comment]
I just tried it. You need to click "Run" in jsfiddle after the inspector is opened.  As for JS bin, you need live preview: http://emberjs.jsbin.com/dojowe

**Comment by kavika13** [comment]
Yep, you're right, and it is working for me. I didn't realize those were required for it to work.
