### ISSUE TITLE
ember inspector stops responding, error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember-inspector#2200]
**Describe the bug**
inspector stops responding to any interaction, error in inspector is 
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
- While rendering:
  -top-level
    application
      app-detected
        component-tree
          scroll-container
            vertical-collection

**To Reproduce**
inconsistent, hard to reproduce consistently 

happens when children are being removed from the component tree.
This seems to happen when there are many renders.
I have a clock which updates a few times per second. When addition interaction is done it increases the likelihood

**Comment by patricklx** [comment]
i can now reproduce it everytime:
steps:
1. have a render tree with many children
2, scroll down such that the parent of the children is out of view
3. interact with the page such that the children should disappear 
-> observe that the children did not disappear from the component tree
then scroll up and try to collapse the parent -> it will cause this issue

**Comment by rwwagner90** [comment]
@patricklx was this one of the things you had a PR for?

**Comment by patricklx** [comment]
No, i was unable to solve it or make a good reproduction...
