### ISSUE TITLE
Including the `ember` npm package in app's dependencies breaks Ember Inspector

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember-inspector#2217]
# Describe the bug

Subj.

Yes, this ember package should have never been installed into the app, but it's absolutely benign and should not be breaking anything.

# To Reproduce

1. `npm i -S ember`

# Expected behavior

Ember Inspector keeps working.

# Screenshots

![image](https://user-images.githubusercontent.com/200884/198565901-beaab6b0-bbdf-497c-bb34-9b86afc26a8e.png)

# Environment

* `ember`: 1.0.3 😎 
* Ember Inspector: 4.9.0
* `ember-source`: 3.24.4
* `ember-cli`: 3.24.0
* Chrome: 106

**Comment by patricklx** [comment]
actually, your app should also have problems when having this package installed. at least if somewhere `import 'ember'` is used. which ember-inspector does for backwards compatibility.
 ember test helpers also import it. https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/-internal/build-registry.ts#L7

**Comment by rwwagner90** [comment]
I think this is something we don't need to fix. This is the behavior I would expect from installing any package and then trying to fake an import to that package.
