### ISSUE TITLE
in-page-script.js inserted into Wordpress editor

### ISSUE THREAD

**Issue by jlami** [emberjs/ember-inspector#2243]
**Describe the bug**
`<script src="chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/scripts/in-page-script.js" type="text/javascript"></script>` is inserted into the Wordpress editor and saved to the database. 

**To Reproduce**
1. Edit a page/post in Wordpress with the old/classic editor enabled and the 'Visual' mode as default. (classic-editor plugin is enabled on the sites I tested)
2. Click on the 'text' mode for the editor and see that the script is inserted

I don't know if the new gutenberg editor also has this problem, but I guess that every editor that uses iframes is effected.

**Expected behavior**
ember-inspector should not insert the in-page-script in the editor

**Comment by tdwesten** [comment]
Hello, version 4.9.1 is still injecting "<script src="chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/scripts/in-page-script.js" type="text/javascript"></script>" in the WP editor. Is this already released?

**Comment by patricklx** [comment]
No, it's not released. You can try the nightly:
https://chrome.google.com/webstore/detail/ember-inspector-nightly/ibdbkmdgflhglikhjdbogjjflkialpfi
