### ISSUE TITLE
Safari Pop-Up

### ISSUE THREAD

**Issue by tonycoco** [emberjs/ember-inspector#244]
Safari blocks the pop-up for the bookmarklet... any fixes other than turning that feature off in the preferences?

**Comment by devinrhode2** [comment]
Is this in safari 8 on yosemite?

**Comment by btecu** [comment]
It would be nice if we could get native Safari extension.

**Comment by tonycoco** [comment]
I tried a bunch of options, but it will take some work, since Safari block IFRAME talk and their extension window API is terrible.

**Comment by joostdevries** [comment]
@tonycoco while not developed for this UC, you could also use the [remote-inspector](https://github.com/joostdevries/ember-cli-remote-inspector) addon if you're working on an Ember CLI app. It works with websockets and allows the inspector to be openend in another window or even browser.

**Comment by tonycoco** [comment]
Yeah, I've used that with success. Track the Safari/WebKit Web Inspector bug here I just created a new one - https://bugs.webkit.org/show_bug.cgi?id=140816

**Comment by tonycoco** [comment]
Looks like they're making progress on something for Safari on the Webkit Issue tracker. I'll try to update this thread with any information.

**Comment by teddyzeenny** [comment]
Thanks @tonycoco!

**Comment by locks** [comment]
Any resolution on this, @teddyzeenny @tonycoco ?

**Comment by tonycoco** [comment]
Not yet @locks. The WebKit bug was never resolved but there was talk of a developer extension API

**Comment by rwwagner90** [comment]
Where does this stand now? Does anyone use Ember Inspector in Safari with success?

**Comment by tonycoco** [comment]
WebKit team hasn't started implementation of an API yet. No progress.

**Comment by rwwagner90** [comment]
I'm going to attempt to work on a native Safari extension. Apple does not make this easy at all. Does anyone have experience with Safari extension development? I've loosely been following http://frontendbabel.info/articles/developing-cross-browser-extensions/ and https://github.com/kritollm/chrome-extension-api-for-safari-and-firefox but both are pretty old.

**Comment by rwwagner90** [comment]
This is the branch I started https://github.com/emberjs/ember-inspector/tree/safari-extension

**Comment by devinrhode2** [comment]
Might be easier to take a firebug-style approach, where the inspector is
INSIDE the webpage. This could be a great starting point for making ember
more debug-able everywhere. This could hook into ember-cli somehow, or
perhaps you could just inject the script into the webpage via a safari
extension. Perhaps users could put the injected "ember-inspector.js" in
their vendor file, and the extension would attempt to inject
`location.origin + '/vendor/ember-inspector.js'

Come to think of it, probably better than putting a file into vendor, would
be to actually have an accompanying ember-addon, which defines a function,
`window.activateEmberInspector`, and then the safari extension simply has
to figure out a way to call it. Probably inject a script which just calls
it (literally just `window.activateEmberInspector()`)

(I don't have experience with native safari extensions, but

**Comment by devinrhode2** [comment]
Injecting a file would mean that mainstream usage does not get memory bloat
from defining the function. Then again, the function could be defined in
such a way that uses very very little memory. (Basically get the source
code as a string from somewhere _locally_ and eval it. Also saves parse
time for mainstream usage.)

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>

**Comment by devinrhode2** [comment]
what does it lack? are there some specific browser extension api's that are
missing? Why couldn't ember inspector be made to work firebug-style?

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>

**Comment by rwwagner90** [comment]
@devinrhode2 if you have a specific Safari implementation in mind, you are welcome to take a stab at it, but Safari extensions are a huge mess.

The current plan is to do like React and Vue are doing and make a standalone app for anything other than Chrome and Firefox.
