### ISSUE TITLE
Breaks on ember 5.2 w/ staticEmberSource: true

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-inspector#2457]
**Describe the bug**

Visit: 
- https://limber.glimdown.com
- or locally at http://localhost:4201/
- open the inspector
- observe: `Uncaught TypeError: _computed.readOnly is not a function`

**Screenshots**

![image](https://github.com/emberjs/ember-inspector/assets/199018/1218cae8-26e1-41a0-ba8b-d3ad37f70bcc)

Refreshing with the inspector open and "pause on exceptions" checked gives the actual problem code:

![image](https://github.com/emberjs/ember-inspector/assets/199018/654702a1-109a-437d-94c0-861f67768c39)

![image](https://github.com/emberjs/ember-inspector/assets/199018/97184df0-d0f1-424b-82d8-dc2a9ee35aba)

**Environment**
ember-source 5.2, all browsers

**Comment by patricklx** [comment]
It looks like all computed.x are undefined at that point?
I'm also on 5.2 and it's working... is that always happening or does it work sometimes after a few refresh?
Maybe something special with your setup?
 Is that a public repo that we can test on?
It looks like ember did not fully boot and ember debug already loads. Though i fixed that some time ago, so i might have a look at this

**Comment by patricklx** [comment]
Ah, probably because of staticEmberSource

**Comment by NullVoxPopuli** [comment]
I thought the ember inspector uses its own ember-source :thinking: I guess -- why does it care about if I've svelte'd away parts of ember-source or not?

**Comment by patricklx** [comment]
Nope, the ember_debug part relies on the apps ember source. 
Probably to minimize size?
But it should definitely be possible now. If we can make a static build of ember_debug witn static ember source.

**Comment by patricklx** [comment]
You could adda file like this to your project 
```js
import * as runloop from '@ember/runloop';
define('@ember/runloop', () => runloop);
```
Would need more defines ofc

**Comment by RobbieTheWagner** [comment]
It needs to use the app's Ember because it lives alongside the app and is used to debug apps. It wouldn't make sense to drop in a way different version of Ember and expect the ember_debug side of things to work, as your app uses what it uses.

**Comment by NullVoxPopuli** [comment]
@RobbieTheWagner is the access of `computed` stuff needed? I would expect that If I (and none of my addons) use computed.readonly, that it wouldn't be in the build -- how should the inspector handle this scenario?

**Comment by patricklx** [comment]
> @RobbieTheWagner is the access of `computed` stuff needed? I would expect that If I (and none of my addons) use computed.readonly, that it wouldn't be in the build -- how should the inspector handle this scenario?

Even if ember_debug uses as much as possible of ember directly. There will be some parts that it needs from the app itself.

**Comment by patricklx** [comment]
It doesn't matter , they are not in the module because of dead code elimination

**Comment by patricklx** [comment]
@NullVoxPopuli 
this is what i have in my app to get inspector to start
```js
import * as computed from '@ember/object/computed';
import * as runloop from '@ember/runloop';
import * as metal from '@ember/-internals/metal';
import * as inst from '@ember/instrumentation';
import * as view from '@ember/-internals/views';
import * as ref from '@glimmer/reference';
import * as val from '@glimmer/validator';
import ember from 'ember';
define('ember', [], () => ember);
define('@ember/object/computed', [], () => computed);
define('@ember/runloop', [], () => runloop);
define('@ember/-internals/metal', [], () => metal);
define('@ember/instrumentation', [], () => inst);
define('@ember/-internals/views', [], () => view);
define('@glimmer/reference', [], () => ref);
define('@glimmer/validator', [], () => val);
```

**Comment by NullVoxPopuli** [comment]
that makes my app bigger tho

**Comment by patricklx** [comment]
Probably importing ember is the culprit. 
Will it be smaller if that is removed.
 I think there we could probably to remove that usage if specific imports are available

**Comment by RobbieTheWagner** [comment]
This should probably be a build time thing with embroider etc. Like all of the things should be shipped for inspector to work in dev mode at least. If you want to opt out in production, that is fine.

**Comment by patricklx** [comment]
I think all of those required things are actually in your app. But just not exposed

**Comment by NullVoxPopuli** [comment]
What if the inspector just doesn't access things that aren't available?

A graceful degradation (with messaging) sort of behavior?

**Comment by Ralica** [comment]
Just chiming in to report that:
Using only 
`import * as computed from '@ember/object/computed';`
Fixed the Inspector crashing when trying to open the Data tab.
Using
"ember-data": "^5.3.2",
