### ISSUE TITLE
View rendering times are inaccurate, add warning

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember-inspector#249]
The times reported in the view rendering pane, though helpful for comparison between views and discovering issues, are known to be skewed and inaccurate due to the instrumentation required.

I propose adding a sticky warning to the top of the rendering pane:

![](https://api.monosnap.com/image/download?id=CgENICZvjDGmpOvJ5qYtwde6RNYvSQ)

I imagine something like the yellow block here:

![](https://api.monosnap.com/image/download?id=0FRHdKD3BU9LHIW2Nzg9oBEArogXx9)

We've seen people reporting these numbers back to the Ember repo and discuss as if they were accurate and additional profiling was not discovered, and this is to be discouraged.

/cc @stefanpenner

**Comment by arjunkathuria** [comment]
@locks got some time on my hands this week, can give a shot.

**Comment by locks** [comment]
@arjunkathuria yes, please! :) Reach us in on Slack for any help.

**Comment by arjunkathuria** [comment]
@teddyzeenny @locks what issue ? :trollface:

**Comment by locks** [comment]
Merged! :D
