### ISSUE TITLE
Ember inspector 4.10 not working with 3.28

### ISSUE THREAD

**Issue by IBRAHIMDANS** [emberjs/ember-inspector#2491]
**Describe the bug**

since the last version ember inspector no longer detects the project

**To Reproduce**

1. Go to localhost
2. open inspector

 "ember-cli": "~3.28.6",
    "ember-data": "~3.28.6",
    "ember-source": "^3.28.6",

**Screenshots**
![image](https://github.com/emberjs/ember-inspector/assets/25392908/e11b2f9e-3468-4622-ad34-55e0bb472011)

**Comment by patricklx** [comment]
hi, do you now of any site that has that exact version?
it's working on [ember](https://emberjs.com/), which is using version v3.28.8

**Comment by IBRAHIMDANS** [comment]
i look this 
I think some dependencies are missing

![image](https://github.com/emberjs/ember-inspector/assets/25392908/6dac349f-71d7-48d7-a2dc-2056efcfc44b)
![image](https://github.com/emberjs/ember-inspector/assets/25392908/d57d9ecc-81f8-4752-8ca8-293e7a898e61)

**Comment by patricklx** [comment]
if you type `module` in the console, do you get a result?

**Comment by patricklx** [comment]
i think this is caused by define.amd, which causes source-map to try to require fs and path... can you confirm that define.amd is set?

**Comment by IBRAHIMDANS** [comment]
@patricklx  
![image](https://github.com/emberjs/ember-inspector/assets/25392908/85365ba3-e7cd-4b58-a370-145eb86aaa74)

**Comment by patricklx** [comment]
strange, can you debug and find out which module is missing 🙏

**Comment by patricklx** [comment]
Also, this is on an electron app, right?

**Comment by robertpbaxter** [comment]
I too am encountering a similar issue, but it is worse than just ember 3.28. Inspector v4.10 was not detecting any of our live apps. The original post at least has the tab stating that no app is detected. I couldn't get the ember tab to appear in the devtools for our modern and legacy apps:

ember 3.28.12 w/ ember-data 3.28.10
ember 3.4.8 w/ ember-data 3.4.4
ember 1.11.4 w/ ember-data 1.0.0-beta.14.1

Chrome v119.0.6045.105 (Official Build) (x86_64)

I have had to rewind back to 4.9.1 to access my tools again.

**Comment by patricklx** [comment]
is there any online ember app where inspector does not load? it's hard to debug without an example

**Comment by patricklx** [comment]
> Understandable. I have both inspectors installed simultaneously for demonstration purposes: <img alt="image" width="1281" src="https://user-images.githubusercontent.com/40548269/280781393-1c81f2c5-a01b-4e5d-8a28-bfd97d81b301.png">
> 
> Only 4.9.1 detects ember in my browser.

Strange, it's working for me. Maybe if you remove and re-install the ember inspector?

**Comment by patricklx** [comment]
Difference of security settings?

**Comment by robertpbaxter** [comment]
@patricklx It has to be my local environment. My personal machine detects the ember.js app with 4.10, and my work machine just displayed a malfunction within macOS. It took too long for me to compare machines. Rookie troubleshooting mistake. 

Thanks a prompt response though.

**Comment by RobbieTheWagner** [comment]
> Understandable. I have both inspectors installed simultaneously for demonstration purposes: <img alt="image" width="1281" src="https://user-images.githubusercontent.com/40548269/280781393-1c81f2c5-a01b-4e5d-8a28-bfd97d81b301.png"> Only 4.9.1 detects ember in my browser.
> 
> Edit: I turned on error collection for the inspector v4.10. Found the point of failure for my particular situation. It occurs in the background.js file. <img alt="image" width="1053" src="https://user-images.githubusercontent.com/40548269/280802198-617d3d56-d145-45b1-9966-6407471e2cab.png">

Looks like this is a separate issue? It says what do to there to fix the onClick
