### ISSUE TITLE
>$E not working in conjunction with emacs impatient-mode

### ISSUE THREAD

**Issue by bhyde** [emberjs/ember-inspector#250]
Emacs impatient-mode enables live editing by kicking the browser to render the page after each keystroke.  Tis delightful.  I was stepping thru the ember tutorial; I installed the ember-inspector; I clicked on the cute little >$E; I was sad that I got "$E is not defined.":
![image](https://cloud.githubusercontent.com/assets/19701/4851205/8a8b42dc-6070-11e4-9c83-d9b00d075ab2.png)
Eliminating little Emacs httpd server and whatever magic impatient-mode is doing fixed that.

**Comment by makmanalp** [comment]
Weird! I just hit this without the emacs part. Was working yesterday so I have no idea why it decided to happen now. Was broken on chrome 50.0.2661.86 and after a restart it updated to 50.0.2661.94 at which point it started working, though I don't know if it was just the restart that fixed it.
