### ISSUE TITLE
Consider implementing iOS8 App Extension

### ISSUE THREAD

**Issue by denisnazarov** [emberjs/ember-inspector#253]
The new iOS8 has a new app extension API which can allow us to do basically what Chrome extensions do on the desktop today.

https://developer.apple.com/app-extensions/
https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/

It allows you to inject javascript into a page and communicate back to the extension's container app. Could be awesome for mobile benchmarks/debugging, etc.

cc/ @stefanpenner

**Comment by locks** [comment]
@joostdevries @stefanpenner @lukemelia @denisnazarov do you have someone that can work on this? Otherwise we'll have to close due to lack of resources.
