### ISSUE TITLE
Inspector Becomes Unresponsive When Left Open for a Few Minutes

### ISSUE THREAD

**Issue by kdagnan** [emberjs/ember-inspector#2532]
**Describe the bug**
This has started occurring with the 4.10.X series, it was fine a few weeks ago on 4.9.X.

After opening the inspector, it works as expected for a few minutes. Within a few minutes of opening and leaving unattended, it becomes unresponsive. Clicking anywhere does nothing most of the time, occasionally it will switch from your previous page to all grey:
![Screenshot 2023-12-19 at 3 36 35 PM](https://github.com/emberjs/ember-inspector/assets/44090970/5bdcd5f5-d4bb-438e-91c8-43f77c1734ef)

**To Reproduce**
1. Open the Inspector
2. Let it sit for 3-5 minutes
3. Return to find that none of the functionality works
4. Close DevTools & re-open to get it working again

**Environment**
Tested on:
- MacOS 14.0 (Apple Silicon) Chrome 120.0.6099.109 & Firefox 120.0.1
- Windows 11 (Intel) Chrome 120
- MacOS 14.0 (Apple Silicon) Chrome 120

Tested with:
- All 4 of our company's applications, running Ember-source 3.28
- A fresh `ember init` application running Ember-source 5.X

**Comment by patricklx** [comment]
I was trying to reproduce it on emberjs site. But it was working after 1h... But i noticed that sometimes it hanged after switching tabs for a while... Inspector was then disconnected from the site.

When it happens can you inspect ember-inspector (right-click inspect works there too) and check the logs for any errors?

**Comment by patricklx** [comment]
looks like service workers can be shutown after idle time... with manifest V3
https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle#idle-shutdown

so this only happens when not using the inspector for a while?

**Comment by kdagnan** [comment]
Somehow, this morning I am having a much harder time replicating. It was happening consistently before, if I left the window open in the background for more than a minute or 2, it happened every single time. Now, it's happening more inconsistently, but still happening. This is the error I think associated:

```
chrome-extension://b/….html#/route-tree:1 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at i.sendMessage (ember-inspector.js:699:435)
    at n.send (ember-inspector.js:726:296)
    at ember-inspector.js:562:208
    at vendor.js:3947:5
    at new C (vendor.js:3947:73)
    at o.model (ember-inspector.js:562:130)
    at o.deserialize (vendor.js:1981:119)
    at M.getModel (vendor.js:3783:26)
    at vendor.js:3765:623
    at _ (vendor.js:3929:12)
```

**Comment by patricklx** [comment]
Right, so it's about the background process getting killed. Inspector needs a way to reconnect

**Comment by patricklx** [comment]
Right, so it's about the background process getting killed. Inspector needs a way to reconnect
