### ISSUE TITLE
CPU Usage Increase in Firefox

### ISSUE THREAD

**Issue by darvelo** [emberjs/ember-inspector#259]
When the Ember Inspector 1.5.0 plugin is enabled in Firefox (Linux), my Firefox process's CPU usage hovers around 20% until the plugin is disabled. I've got a recent Intel Core i7 processor and about 150 tabs open (yeah, i know...) but only one tab has to actually be loaded for this to take effect.

**Comment by teddyzeenny** [comment]
@darvelo is the cpu issue still there on the current FF?

**Comment by darvelo** [comment]
@teddyzeenny Yes, just checked. Ember Inspector 1.6.4. FF 35.0.1.

**Comment by gee-forr** [comment]
Hey guys,

Apologies on bumping this ancient thread, but I can confirm that Firefox 38 on Mac OSX has similar problems.

Irrespective of tab count, or whether the current tab is an Ember app or not, the CPU usage is the same.

Let me know if there's any instrumentation I can run on my side to help you zero in on this issue.

**Comment by ur5us** [comment]
Hey, 

This is a huge problem for me as well. I use both, FF standard and dev edition, on OSX and lots of tabs, yes even more than 150 many times. With Ember Inspector my CPU will be 100% all the time. Upon deactivating the addon the CPU usage drops big time, in my case to 10 – 20% which is ok given how many tabs FF is managing. I'm using the latest version of Ember Inspector. Let me know how I can help. I haven't developer a FF add-on yet but I'm keen to get involved to resolve this issue.

**Comment by locks** [comment]
I use Firefox Dev Edition and couldn't reproduce, can someone confirm this is on-going?
