### ISSUE TITLE
Unable to update boolean config bit

### ISSUE THREAD

**Issue by jessicashaver** [emberjs/ember-inspector#2594]
**Describe the bug**
Ember inspector updated to version 4.13. Since the update, unable to update any boolean value. 

**To Reproduce**
1. Go to 'Components'
2. Click on 'application route'
3. Select 'config'
4. Search for property that's a bool that you want to change
5. Click into value to edit 

**Expected behavior**
Clicking the bool for the config you want to change opens the field. You can switch the value to be true or false. 

**Actual behavior**
Clicking the bool for the config you want to change only highlights the bool value. User can go to Console and change the config value there using `Ember.set(config, 'valueOne', false)`

**Environment**
Ember version 4.13 
Chrome Version 127.0.6533.73

**Comment by patricklx** [comment]
I guess we need to add type-boolean here:
https://github.com/emberjs/ember-inspector/blob/e17d105c3196c5e954ade15cf2f4b797bde52b98/app/components/object-inspector/property.ts#L125

**Comment by RobbieTheWagner** [comment]
@patricklx sounds like we need more test coverage here as well.
