### ISSUE TITLE
messaging to indicate ember-extension conflicts with performance tuning

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember-inspector#272]
1. the instrumentation needed to display the render speed tab itself currently skews results, although likely uniformly in that app and that version of ember, and should only be used to indicate "hot views"
2. the mere act of having ember-extension open will cause various instrumentation hooks and modes to be enable which slow down your app. Also some of the instrumentation consumption code (Which can be slow) leaks into profiles
3. In many cases the numbers we see are almost just measuring the cost of instrumentation rather then that which they should instrument.

Ultimately the inspector should be used to find `hot spots` but actual perf work needs to be done using a /dev/null profile (or an incognito window with no extensions installed)

**Comment by locks** [comment]
@teddyzeenny I was pretty sure we added a disclaimer?

**Comment by teddyzeenny** [comment]
@locks yes we did.

![screen shot 2017-01-05 at 11 54 46 am](https://cloud.githubusercontent.com/assets/1061742/21676300/cb65522e-d33d-11e6-9643-82c40e2ddd4d.png)
