### ISSUE TITLE
Ember data tab showing two of every model type when extending models from ember-cli addon directory. 

### ISSUE THREAD

**Issue by arenoir** [emberjs/ember-inspector#274]
I have broken my application in three "fp-desktop", "fp-mobile" and "fp-common".

The models shared between the "fp-mobile" and "fp-desktop" applications are in most cases identical. So I figured I could inherit each model from a common ember-cli addon.

Like so:

```
//fp-common/addon/models/address.js
import DS from 'ember-data';
  var attr = DS.attr;
  export default DS.Model.extend({
    lineOne: attr('string'),
    city: attr('string'),
    state: attr('string'),
    zip: attr('string'),
});

//fp-mobile/models/address.js
import Address from 'fp-common/models/address';
export default Address;

//fp-desktop/models/address.js
import Address from 'fp-common/models/address';
export default Address.extend({
  desktopOnlyProperty: true
});

```

Everything seems to work as expected but the ember inspector shows two of every model type. Eventually the model count will diverge between the two versions of each model type.

![screen shot 2014-12-09 at 8 20 26 pm](https://cloud.githubusercontent.com/assets/113590/5384673/61c0f8d6-8070-11e4-83df-5a7726a301ad.png)

I [originally](https://github.com/stefanpenner/ember-cli/issues/2721) thought this was an ember-cli issue but I am now thinking it may be related to the inspector. 

version info:

ember-inspector: 1.6.3
ember-cli 0.1.4 
ember: 1.10-beta-1
ember-data: canary

**Comment by teddyzeenny** [comment]
PR submitted https://github.com/ember-cli/ember-resolver/pull/82
