### ISSUE TITLE
Causes AW SNAP crashes in Chrome on Linux

### ISSUE THREAD

**Issue by ultimatemonty** [emberjs/ember-inspector#281]
Linux Mint 17.1
Chrome 39.0.2171.95 (64-bit) (installed via package manager)
Ember Inspector 1.6.4

LOVE this extension! However, I randomly get AW SNAP crashes while browsing. This tends to happen after the browser has been open for a while and/or I have 10+ tabs open. I can consistently repro on many Yahoo.com sites (news articles crash regularly). I've disabled/re-enabled my extensions one by one and Ember Inspector looks to be the issue.

I can provide Chrome crash dumps if needed and am available for additional troubleshooting

**Comment by teddyzeenny** [comment]
@ultimatemonty thanks for reporting this. It happens even if the inspector is not open?
If the inspector is causing the crash, either [content-script.js](https://github.com/emberjs/ember-inspector/blob/master/dist_chrome/content-script.js) or [in-page-script.js](https://github.com/emberjs/ember-inspector/blob/master/shared/in-page-script.js) is the cause since they're the only two files executed while the inspector is closed. So the good thing is there isn't a lot of code to cover.

This is hard to reproduce, I wonder how we should tackle this. Do you have the time to clone the repo and try to isolate the issue through elimination? @stefanpenner any ideas?

**Comment by ultimatemonty** [comment]
@teddyzeenny yes it happens even when the inspector isn't open. If you can provide some rough instructions on how to go about troubleshooting I'll be happy to see if I can narrow it down. I don't have any consistent testing but it feels like this issue occurs more often on sites that have a heavy amount of advertising/tracking. @stefanpenner agreed that nothing reasonable should cause this as it's only an issue on Linux - my windows env never has problems. I'm glad to post on the chrome issue tracker but I'm pretty sure the response will be "it's an extension issue" because it doesn't occur if the inspector is disabled.

**Comment by teddyzeenny** [comment]
@ultimatemonty you can check the [readme](https://github.com/emberjs/ember-inspector#chrome) for instructions to run it from source instead of the published extension.  Once you are using the extension from source (and disabled the published extension), you will be able to modify the two files I mentioned above, and see the effect. You'll want to reload the extension (in `chrome://extensions`) whenever you modify the content-script (or you can install an "extension reloader" extension that adds a "Reload Extensions" button to your browser).

Since you can't reproduce it consistently, I expect this might not be easy :(
If you think I can help (considering I can't reproduce it) let me know. Good luck!

**Comment by ultimatemonty** [comment]
@teddyzeenny I've been able to reproduce the issue in several different situations. The commonalities between the reproductions are at least 9 tabs open (one of which is Yahoo and others are Yahoo affiliated - GrindTV and ProFootballTalk in two cases, some random news articles in the other).

The first instance involved 41 tabs over 2 windows with the Inspector open. An article on AndroidPolice (not an Ember app) would crash in this instance if DevTools was open and Ember Inspector was enabled.

The second instance is a little stranger. It definitely involves having DevTools open and Ember Inspector enabled but the behavior itself is inconsistent. 20 tabs over 2 windows, open Bustle and launch DevTools. Either Bustle or DevTools crashes.

The 3rd was 9 tabs in 1 window with DevTools open on Bustle. Same behavior as the others - everything is fine and dandy as long as DevTools isn't open.

As a baseline I tried commented out everything in `content-script.js` and `in-page-script.js` and the issue still occurred. It's highly likely I had another DevTools instance open last night and didn't realize it when I reported the issue occurred even with DevTools closed.

Also another oddity - my compiled from source version of Ember Inspector is v1.6.2 but the Chrome Web Store version is 1.6.4

Unsure where to proceed from here.

**Comment by teddyzeenny** [comment]
@ultimatemonty when you say "DevTools open and Ember Inspector enabled" do you mean in addition to opening DevTools you clicked on the "Ember" tab and the Ember Inspector is running (showing the view tree for example)? 

There are four different cases:

- Devtools open or closed (doesn't matter), but the Ember Inspector extension is disabled in `chrome://extensions` or not installed.
- Devtools open or closed (doesn't matter), but you didn't click on the "Ember" tab,
- Devtools open and you clicked on the "Ember" tab but you have "Ember Application not detected",
- Devtools open and you clicked on the "Ember" tab and the Ember Inspector has detected an Ember application (you can see the view tree).

Don't worry about the versioning, the compiled source is the latest version, the version numbers are wrong.

**Comment by ultimatemonty** [comment]
@teddyzeenny DevTools open but I didn't have to click on the Ember tab. The crash would occur as long as DevTools was open with the extension enabled.

* Devtools open or closed (doesn't matter), but the Ember Inspector extension is disabled in chrome://extensions or not installed. 
     **No crashes occur in this scenario**

* Devtools open or closed (doesn't matter), but you didn't click on the "Ember" tab. 
    **Both browser and DevTools crashes would occur in this scenario**

* Devtools open and you clicked on the "Ember" tab but you have "Ember Application not detected"
**Browser crashes would occur in this scenario**

* Devtools open and you clicked on the "Ember" tab and the Ember Inspector has detected an Ember application (you can see the view tree).
    **Browser crashes would occur in this scenario**

Clear as mud?

**Comment by teddyzeenny** [comment]
"Devtools open or closed (doesn't matter), but you didn't click on the "Ember" tab." means it's only the content-script or background-script. AFAIK nothing else is executed unless you click on the "Ember" tab.

I guess what's left is checking which of [these](https://github.com/emberjs/ember-inspector/blob/master/dist_chrome/manifest.json#L18-L27) is the culprit.  You could try to remove all of them from the manifest, without them it's just an empty extension. (Don't forget to reload the extension after changing the manifest).  
You should also be able to safely delete the `dist_chrome/panes` and `dist_chrome/ember_debug` directories as long as you're not clicking on the "Ember" tab.

**Comment by ultimatemonty** [comment]
@teddyzeenny I've been trying to isolate this for a bit now and the more I work with it the more I think it's an issue with Chrome and not the Inspector. Best guess is whatever is up with Chrome is exacerbated by  but not directly caused by Inspector. I've had several crashes recently that occurred with Inspector disabled. Not sure how to go about reporting to Google as I can't reliably reproduce the problem. Closing this issue. Thanks for all the support along the way!

**Comment by ultimatemonty** [comment]
FYI - was searching Chrome user forums and ran across https://productforums.google.com/forum/#!topic/chrome/PIMlbEwJegQ which is very similar to what I'm experiencing.

**Comment by teddyzeenny** [comment]
@ultimatemonty np :) Hope your issue will be resolved soon, and thanks for investigating.
