### ISSUE TITLE
Trigger observers when editing controller property

### ISSUE THREAD

**Issue by QuantumInformation** [emberjs/ember-inspector#282]
It would be nice if controller observers were triggered when editing a controller property (own properties) in the ember inspector. Currently this doesn't happen for me.

**Comment by teddyzeenny** [comment]
The observers should be firing.  Can you link to me a jsbin example where they don't fire?

**Comment by QuantumInformation** [comment]
This is my bower, if its supposed to work I'll put it down to an unlucky one, its too much work to set up in jsbin.

```js
{
  "name": "home-move-cli",
  "dependencies": {
    "handlebars": "1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.11",
    "ember-data.model-fragments": "0.2.2",
    "ember-resolver": "~0.1.7",
    "loader.js": "stefanpenner/loader.js#1.0.1",
    "ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "pickadate": "~3.5.4",
    "font-awesome": "~4.2.0",
    "bootstrap": "~3.3.1",
    "moment": "~2.8.4",
	  "amplify":"~1.1.2",
	  "awesome-bootstrap-checkbox":"0.2.3",
    "ember-select2":"*"
  }
}
```

**Comment by teddyzeenny** [comment]
bower.json won't be enough for me to reproduce. I assume this is what you mean by trigger observers: http://emberjs.jsbin.com/peveya ?  This jsbin is working, your case might be specific so I will need more info to reproduce (anything online or clear steps to reproduce).

**Comment by teddyzeenny** [comment]
@QuantumInformation were you able to find out what the issue is?

**Comment by locks** [comment]
Closing this due to lack of response from OP.
