### ISSUE TITLE
Unknown mixin name

### ISSUE THREAD

**Issue by elidupuis** [emberjs/ember-inspector#284]
Just curious: when I inspect Controllers or Routes that use a Ember.Mixin, the properties from that mixin are grouped in a section (which is great) but the section title says **Unknown mixin**.

Is there anything I can do in my codebase to have the sections named based on which mixin they are from? FYI, I'm using Ember CLI so the only name these mixins have would be the filename.

Thanks for your input.

**Comment by teddyzeenny** [comment]
This specific case (importing a mixin module) is not simple.  Here's how we currently name classes:

- When attached to a namespace (`App.MyMixin`), we're able to name the mixin by looping over the namespace properties and naming every attached object as the key name (`MyMixin`).
- When getting classes through the container (`container.lookupFactory('model:user')`), we are able to name the mixin based on the the argument passed to `lookupFactory`.

A mixin in a module based resolver is neither attached to a namespace nor goes through the container (it is imported using `import` and mixed in to the classes).

> Is there anything I can do in my codebase to have the sections named based on which mixin they are from?

Yes, but it's not pretty:
```javascript
// app/mixins/my-mixin.js
import Ember from 'ember';
var MyMixin = Ember.Mixin.create({
  //.. mixin properties
});
MyMixin[Ember.NAME_KEY] = 'MyMixin';
export default MyMixin;
```

**Comment by elidupuis** [comment]
Thanks for the input. Makes sense.

I added your code snippet to my mixin but I still **Unknown mixin**. It's not really a big deal—I just thought I'd ask.

**Comment by teddyzeenny** [comment]
I can't think of a reason why it wouldn't work... Just tried it locally and it's working.  I'm happy to look into it if you can provide a sample repo with the issue.  Although not exactly the same case, you can inspect `IndexController` in this [jsbin](http://emberjs.jsbin.com/cogupi) and see `MyMixin`.

**Comment by elidupuis** [comment]
My controller is an `Ember.ObjectController`. That's why mine didn't work. If I change it to `Ember.Controller` it works fine.

Thanks for the help!

**Comment by teddyzeenny** [comment]
No problem :) `ObjectController` should work just the same though: http://jsbin.com/cogupi/2

**Comment by rwjblue** [comment]
Also, `Ember.ObjectController` will be deprecated in 1.11.

**Comment by elidupuis** [comment]
@teddyzeenny Hmm. Now it does seem to work with `ObjectController`. All good, I guess

@rwjblue I am aware of that but thanks for the heads up. I really appreciate the Ember team's commitment to openness and community awareness :smile:
