### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by tosunilgupta** [emberjs/ember-inspector#289]
Getting Error:
Ember Inspector ($E):  TypeError: Cannot read property 'hasOwnProperty' of undefined
    at u (http://localhost:8080/wro/libraries.js?minimize=true:176:387260)
    at null.<anonymous> (http://localhost:8080/wro/libraries.js?minimize=true:176:387553)
    at a.T._set (http://localhost:8080/wro/libraries.js?minimize=true:176:98578)
    at a.T.set (http://localhost:8080/wro/libraries.js?minimize=true:176:98167)
    at new n (http://localhost:8080/wro/libraries.js?minimize=true:176:242554)
    at Function.k.create.create (http://localhost:8080/wro/libraries.js?minimize=true:176:245395)
    at Ember.Object.extend.buildRecord (http://localhost:8080/wro/libraries.js?minimize=true:176:430646)
    at Ember.Object.extend.recordForId (http://localhost:8080/wro/libraries.js?minimize=true:176:426662)
    at Ember.Object.extend._load (http://localhost:8080/wro/libraries.js?minimize=true:176:429482)
    at Ember.Object.extend.push (http://localhost:8080/wro/libraries.js?minimize=true:176:430022)

Code:
```js
App.DockeyRoute = Ember.Route.extend({     
  model: function(){
    return Ember.RSVP.hash({
      dokumenteprimarynavtemplate:  this.store.find('Mainmenukey'),
      dockeymaindatatemplate:  this.store.find('Dockeymaindata')
    }); 
  },
  renderTemplate: function(controller, model){
    this.render('dockey');
    this.render('dockeyprimarynavtemplate', {outlet: 'dockeyprimarynavtemplate', into: 'dockey', model: model.dokumenteprimarynavtemplate});
    this.render('headerkeytemplate', {outlet: 'headerkeytemplate', into: 'dockey'});
    this.render('headerfiltertemplate', {outlet: 'headerfiltertemplate', into: 'dockey'});
    this.render('submenukeytemplate', {outlet: 'submenukeytemplate', into: 'dockey'});
    this.render('maindockeytemplate', {outlet: 'maindockeytemplate', into: 'dockey', model: model.dockeymaindatatemplate});
    this.render('filterbuttontemplate', {outlet: 'filterbuttontemplate', into: 'dockey'});
  } 
});
```

HSB File:
```handlebars
{{#each item in model}}
	<div id ='div-' data-toggle='modal' data-target='#complete-dialog-' class='item-section docTiles shuffle-item filtered shadow-z-2n withripple' data-groups='[&quot;document&quot;,&quot;]' data-title='' >
	 	<div class='item-section__title'>
			<div class='thumbdata'>
				<h3>item.response.length</h3> 
			</div>
		</div>
	</div>
{{/each}}
```
FIXTURES File: storeData is cached data from session storage
```js
storeData = JSON.parse(sessionStorage.getItem("storeData"));
App.Dockeymaindata = DS.RESTAdapter.extend();
App.Dockeymaindata = DS.Model.extend({
	id:		DS.attr("string")
});

App.Dockeymaindata.FIXTURES = [
 	{ 
    id: "965085",
    response: [
      storeData
 	]
 	}
];
```

**Comment by teddyzeenny** [comment]
Thanks for reporting this. The error message starts with 'Ember Inspector ($E):'.  This is printed when you click on `$E` in the Ember Inspector.  Are you sending an error from the inspector? Where was that error in the inspector?

In case it's possible, we could probably track the problem faster if you can reproduce it in a [Jsbin](http://emberjs.jsbin.com/?html,css,js,output) or anything else online.

**Comment by tosunilgupta** [comment]
Hello Ted, 

There is not any jsbin code for this problem, I am facing this problem with my local project and this is not to put on any live environment due to some privacy. 

But Yes, some problem, i am facing a same error from the inspector.

Help me on it. Please....

**Comment by teddyzeenny** [comment]
The log looks like it was sent manually from the inspector by clicking on $E. Which $E did you click on in the inspector? Was it a specific property, view, controller..?  A screenshot of which $E you clicked on might help.

**Comment by teddyzeenny** [comment]
@tosunilgupta any updates?

**Comment by tosunilgupta** [comment]
Hey Tedd!

That issue was resolved through difference approach.
