### ISSUE TITLE
EMBER_DIST is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by chigur** [emberjs/ember-inspector#295]
I am not quite sure how to report this issue. The [value](https://github.com/emberjs/ember-inspector/blob/master/package.json#L12) for `build:chrome` key in the `scripts` option of `package.json` file throws an error, the error is mentioned in this issue's title. Shouldn't the value be something like following.
```EMBER_DIST=chrome; ember build --output-path dist_chrome/panes```

**Comment by rwjblue** [comment]
The command is correct, but may not work on non [posix](https://en.wikipedia.org/wiki/Posix) platforms (I am not sure). Prefixing a command with `KEY=value` assignments set environment variables for that particular command.

**Comment by chigur** [comment]
Thanks, I didn't know that prefixing a command `EMBER_DIST=chrome` would set the environment variable. I am using `MingGW` on Windows and I couldn't find a way of setting an environment variable value, though I could successfully build the chrome distribution by running `set EMBER_DIST=chrome` and then `ember build --output-path dist_chrome/panes`. To avoid such problems of compatibility isn't it better to pass the distribution option value as a command line parameter?

**Comment by teddyzeenny** [comment]
@chigur thanks for looking into this. We need `EMBER_DIST` as an environment variable to access it from the Brocfile, config, and from addons. Is there a way to set the environment variable through npm scripts that works on all platforms?

**Comment by locks** [comment]
Hi @chigur, we are closing this as only the production build needs env vars, and in all likelihood only the maintainers need to run it to publish the extension. If you feel like you have some free time to help us with this, reopen and ping us. Thanks!
