### ISSUE TITLE
The Ember Inspector 1.7.0 does not detect my ember 1.4 app on rails

### ISSUE THREAD

**Issue by Mannaio** [emberjs/ember-inspector#297]
I am running my Ember app on rails, and since you have released  the new inspector 1.7.0, my ember-inspector chrome extension does not detect my ember app ( 1.4), in the new Ember Inspector  1.7.1 you are planning to fix this bug:
[BUGFIX] Fix the inspector for Ember < 1.4

My Ember app is built on version is 1.4, but still the Inspector does not detect it
![error](https://cloud.githubusercontent.com/assets/1617078/6026068/bc308be6-abd7-11e4-8c5d-0098eef5ef76.png)
![error_file](https://cloud.githubusercontent.com/assets/1617078/6026070/bee65b0e-abd7-11e4-8bb4-567c3b704664.png)

**Comment by teddyzeenny** [comment]
1.7.1 has been released.  What version are you on?

**Comment by Mannaio** [comment]
Nice! it works, I have also noticed that anytime i have an app error the ember inspector stops detecting the app, is this normal?

**Comment by teddyzeenny** [comment]
If the error happens before the app boots successfully, it's normal.

**Comment by Mannaio** [comment]
Yes it does and the app boots successfully but the console says  that the Ember Inspector is active. This is my console log
![console-log](https://cloud.githubusercontent.com/assets/1617078/6031997/43f870ee-ac04-11e4-9a9d-bc9790437f35.png)

![vm72666](https://cloud.githubusercontent.com/assets/1617078/6031940/b4ff9dea-ac03-11e4-85fb-924fab9eece3.png)

**Comment by tmquinn** [comment]
![image](https://cloud.githubusercontent.com/assets/251802/6069467/5381f310-ad39-11e4-8ecf-12d422ded7cb.png)
Also getting undefined is not a function at line 5940 in the above image

**Comment by tmquinn** [comment]
requireModule is undefined, btw

**Comment by teddyzeenny** [comment]
@tmquinn this is another issue, @Mannaio's current error is in his application code not the inspector. Do you mind opening a separate issue?

**Comment by teddyzeenny** [comment]
@Mannaio I'm closing this issue since it has been resolved. Feel free to open an issue about the application error breaking the inspector. I'm happy to look into this as a separate issue.
