### ISSUE TITLE
Data tab does not show any models

### ISSUE THREAD

**Issue by seawatts** [emberjs/ember-inspector#298]
I'm using:
ember-cli 0.1.7 with POD structure
ember 1.10.0-beta.4
ember-data 1.0.0-beta.12
handlebars 2.0.0
ember-inspector 1.7.1

When I load the page I don't see anything in the Data tab. 
I saw that you added a fix for this:
https://github.com/emberjs/ember-inspector/blame/master/CHANGELOG.md#L16

However, it still doesn't work for me.

**Comment by teddyzeenny** [comment]
You need to use ember-resolver master: https://github.com/ember-cli/ember-resolver (or wait until a new version is released)

**Comment by seawatts** [comment]
Hmm, tried to add that but got this error:

`Uncaught Error: Assertion Failed: The initializer 'container-debug-adapter' has already been registered`

I might just wait till the release a new version.

**Comment by teddyzeenny** [comment]
It seems like you included it twice.  It is included by default, did you replace the original one in `bower.json`?

**Comment by seawatts** [comment]
Sorry, I edited my comment. It looked like I did add it twice. I removed the second instance of it. However, the data tab still doesn't show anything.

**Comment by teddyzeenny** [comment]
The build files haven't been commited to master yet, so bower is still using the old version. You can use master when https://github.com/ember-cli/ember-resolver/pull/83 is merged.

**Comment by seawatts** [comment]
Awesome! Thanks

**Comment by teddyzeenny** [comment]
Merged. You can use ember-resolver master now. 
`bower install git@github.com:ember-cli/ember-resolver.git#575fbeb3d9798b5bd77979962892f0ea47655b2c --save` should be all you need to do.

**Comment by seawatts** [comment]
Great! This worked. Thanks.

**Comment by teddyzeenny** [comment]
np :)

**Comment by Dynasty9** [comment]
+1 Works for me too!
