### ISSUE TITLE
Ember Inspector 1.7.1 routes not available w/ ember#canary

### ISSUE THREAD

**Issue by Yazjiira** [emberjs/ember-inspector#299]
Hi,

When attempting to view routes in ember inspector while on ember canary no routes come up.
![screen shot 2015-02-04 at 11 29 03 am](https://cloud.githubusercontent.com/assets/8998571/6047852/0e535d70-ac61-11e4-984e-f2a7382d50db.png)

Also, when you try to activate the routes view it generates a type error.
![screen shot 2015-02-04 at 11 26 05 am](https://cloud.githubusercontent.com/assets/8998571/6047844/014c6b58-ac61-11e4-9838-655e6151646f.png)

setup using ember-cli 0.1.12
canary setup using bower:

    bower install --save ember#canary
    bower install --save handlebars#~2.0.0

thank you

**Comment by maxkazar** [comment]
Issue in [file](https://github.com/emberjs/ember-inspector/blob/4f04e0842d3c8a330ae526b17da77cf4afa6f374/ember_debug/route-debug.js#L77)

Look like in cannary build __container__ hasn't rosolver property

**Comment by teddyzeenny** [comment]
As @maxkazar said it looks like the container is missing a resolver property. This is definitely a bug.
