### ISSUE TITLE
1.7.1 now requires console to be open before ember app is initialized.

### ISSUE THREAD

**Issue by photonerddan** [emberjs/ember-inspector#300]
If I am in my ember app before I open the console Ember Inspector does not detect there is an Ember App, unless I refresh. I don't think I experienced this before upgrading. Not sure if this is a bug or expected with the new release.

**Comment by teddyzeenny** [comment]
This should be happening. What libs/versions are you on (the inspector's info tab has all the versions). Are you using ember-cli or globals? Can you reproduce this somewhere I can access (Jsbin, online app, public repo..)?
Are you using Chrome devtools/Firefox devtools/bookmarklet?

**Comment by photonerddan** [comment]
Ember Inspector
1.7.1
Ember
1.2.1
Handlebars
1.1.2
jQuery
1.10.2
Using Globals. If you are expecting this to be happening, why do we need to try and reproduce it?
This is in Chrome devtools. Thanks!

**Comment by teddyzeenny** [comment]
Sorry I meant this should **not** be happening :)

**Comment by teddyzeenny** [comment]
Is it possible you are calling `YouApp.deferReadiness()` after the app has booted? What is the value of `YourApp._readinessDeferrals` the moment you open your inspector?

**Comment by photonerddan** [comment]
-1 The code does not belong to me, and I'm not familiar with every bit of it. I can investigate further, especially if others are not experiencing this.

**Comment by teddyzeenny** [comment]
The value should be 0. My first guess is there is a `deferReadiness()` call somewhere being called after the app has booted (which would mean the call has no effect).

**Comment by jschilli** [comment]
@teddyzeenny I believe it would be advanceReadiness - it decrements `_readinessDeferrals`

I got bit by this and did find a superfluous call to `advanceReadiness` in my code

**Comment by photonerddan** [comment]
This was it. Thank you @teddyzeenny @jschilli
