### ISSUE TITLE
Ember-data deprecations

### ISSUE THREAD

**Issue by ultimatemonty** [emberjs/ember-inspector#303]
Is it possible to add Ember-Data deprecations to the Deprecations tab? I just noticed where `store.find('type')` and `store.find('type', 'query')` were deprecated in beta14.1 but I don't see anything referencing this in the deprecations tab.

**Comment by teddyzeenny** [comment]
The deprecations tab just detects `Ember.deprecate` calls, which includes Ember Data :)  When https://github.com/emberjs/data/pull/2728 is merged and released the deprecations tab should start showing them.

**Comment by ultimatemonty** [comment]
thanks! Didn't realize that wasn't merged yet - that's going to be a BIG change for a lot of folks, myself included.

**Comment by teddyzeenny** [comment]
No problem. I wouldn't worry too much about the change, the [transition](https://github.com/emberjs/data/pull/2728/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR12) seems straight forward if I understand correctly.

**Comment by ultimatemonty** [comment]
Yeah the transition is definitely straight forward. However the code coverage for me is quite large. :neutral_face:
