### ISSUE TITLE
Firefox Release

### ISSUE THREAD

**Issue by Globegitter** [emberjs/ember-inspector#309]
It would be great to get the latest 1.7.x releases published on facebook. Contains some very useful updates :)

**Comment by teddyzeenny** [comment]
1.7 has been submitted to Firefox about a week ago, but FF addons need to go through a review process and need to be approved first. Can I ask what you mean by published on Facebook?

**Comment by stefanpenner** [comment]
> Can I ask what you mean by published on Facebook?

i suspect typo or autocomplete fail

**Comment by stefanpenner** [comment]
> 1.7 has been submitted to Firefox about a week ago, but FF addons need to go through a review process and need to be approved first

maybe this should be included in the description on the FF store :P

**Comment by Globegitter** [comment]
@teddyzeenny Thanks for getting back so quickly - yep that was a total brain fail :P

And yeah, adding that to the FF store description could help :)

**Comment by teddyzeenny** [comment]
@Globegitter np :) I created an issue to remember to add the note https://github.com/emberjs/ember-inspector/issues/310
