### ISSUE TITLE
Inspector doesn't work with EXTEND_PROTOTYPES=false

### ISSUE THREAD

**Issue by omghax** [emberjs/ember-inspector#312]
I have an app that disables Ember's prototype extensions, which seems to break the inspector. When I try to open the tab, I get `Uncaught TypeError: undefined is not a function` because of the following code (in "ember-debug/libs/source-map"):

```js
      sourceMapCache: function() {
        return {};
      }.property(),
```

**Comment by teddyzeenny** [comment]
Yes this should be:
```javascript
var computed = Ember.computed;
// ...
sourceMapCache: computed(function() {
  return {};
}),
```
Do you have time to try this on your app and submit a PR?

**Comment by omghax** [comment]
Done, see #316. Thanks :)
