### ISSUE TITLE
Ember.View.addMutationListener is not a function

### ISSUE THREAD

**Issue by MartinMalinda** [emberjs/ember-inspector#315]
I am using ember beta with HTMLBars and inspector 1. 7. 2. This error prevents loading of both the inspector and the ember app. Without the inspector, the app runs fine.

This happens in unstable version of chrome 2.0.2298.0 dev (64-bit)
In firefox its the same error but the app continues to run.
In stable chrome, the app runs but I get different errors: 

```
Uncaught TypeError: undefined is not a function
VM201:2771 Ember.Object.extend.viewListener
```
```
Uncaught TypeError: Cannot read property 'updateDurations' of undefined
VM201:2345 __exports__.default.Ember.Object.extend._updateViewTree
```

These errors started to occur after I upgraded to ember-cli 0.1.5 and Ember Beta 1.11. I have also some minor issues with liquid-fire now so its possible that this is not at all related to ember inspector.

This is the error in unstable chrome and firefox
![devtools screenshot]
(http://i.imgur.com/hMKZoQA.png)

**Comment by teddyzeenny** [comment]
Looks like `View.addMutationListener` has been removed by a recent refactor. https://github.com/emberjs/ember.js/pull/10412 just exposed the issue.

**Comment by backspace** [comment]
Just happened to me too. Glad there’s a solution on the way. Is there some quick way I could fix this temporarily? People agreed to develop on the beta of Ember 1.11 but I don’t know that canary would go over well hehe

**Comment by teddyzeenny** [comment]
You can upgrade to Ember canary to remove the error.

**Comment by backspace** [comment]
Okay, thanks!

**Comment by kriswill** [comment]
This also happens in Chrome Canary with:
```sh
Ember                       : 1.10.0
Ember Data                  : 1.0.0-beta.15
jQuery                      : 2.1.3
Ember Simple Auth           : 0.7.3
Ember Simple Auth OAuth 2.0 : 0.7.3
```

**Comment by teddyzeenny** [comment]
@kriswill can you reproduce this in a jsbin?

**Comment by kriswill** [comment]
I'm using ember-cli, but I will attempt to.  I'm also going to try installing as a developer extension in chrome by building the repo locally.  This might be something you've already fixed?

**Comment by teddyzeenny** [comment]
@kriswill the issue was in Ember core, not in the inspector repo. But afaik 1.10 isn't affected by this.

**Comment by kriswill** [comment]
it seems to work in JSBin http://emberjs.jsbin.com/qitowa/3, but it's not my whole app, so it must be some other variable, I will try pulling in all of the libs I use.

**Comment by teddyzeenny** [comment]
@kriswill a link to an online app, or a repo that I can clone would also work

**Comment by kriswill** [comment]
yeah it's a proprietary app, still under heavy development.  I won't be able to show you it's source, but I will try to reproduce the effect in JSBin.

**Comment by kriswill** [comment]
I tried to build with node 0.12.0, so that I can actually see the un-minified code for the extensioin in chrome, but got:

```sh
kris git[master] ~/src/oss/ember-inspector 
→ npm run build:chrome

> ember-inspector@1.8.0 build:chrome /Users/kris/src/oss/ember-inspector
> EMBER_DIST=chrome ember build --output-path dist_chrome/panes

version: 0.1.12
Building...
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/kris/src/oss/ember-inspector/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/kris/src/oss/ember-inspector/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:137:17
    at setToStringTag (/Users/kris/src/oss/ember-inspector/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:93:13)
    at /Users/kris/src/oss/ember-inspector/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:631:3
    at /Users/kris/src/oss/ember-inspector/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:647:2
    at Object.<anonymous> (/Users/kris/src/oss/ember-inspector/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:2260:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by kriswill** [comment]
ok, building with legacy node (0.10) works:

```sh
kris git[master] ~/src/oss/ember-inspector 
→ type ember
ember is /Users/kris/.nvm/v0.10.36/bin/ember

kris git[master] ~/src/oss/ember-inspector 
→ npm run build:chrome

> ember-inspector@1.8.0 build:chrome /Users/kris/src/oss/ember-inspector
> EMBER_DIST=chrome ember build --output-path dist_chrome/panes

version: 0.1.12
Built project successfully. Stored in "/Users/kris/src/oss/ember-inspector/dist_chrome/panes".
```

**Comment by teddyzeenny** [comment]
@kriswill thanks, good to know. I will upgrade it to 0.12 when I find some time.

**Comment by jpadilla** [comment]
Just ran into this after upgrading emberaddons.com to ember 2.0.0-beta.1(https://github.com/gcollazo/ember-cli-addon-search/pull/54).

**Comment by teddyzeenny** [comment]
@jpadilla I will fix this today.

**Comment by jpadilla** [comment]
@teddyzeenny great news, thanks!
