### ISSUE TITLE
Removing mandatory setters promotes prototype properties to own properties

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#32]

**Comment by locks** [comment]
> <teddy> the first time you inspect a controller for example, you may see 2 properties in “own properties” and the rest in inherited mixins
if you close it and re-inspect it (in the object controller) you will see that all properties were moved to “own properties"

Can we get some input on whether this is solvable, or if it even matters @krisselden?

**Comment by rwwagner90** [comment]
Is this still an issue @teddyzeenny?

**Comment by teddyzeenny** [comment]
I believe it is, yes. It's a mandatory setter issue (in Ember core), not specific to the inspector, but the inspector exposes the issue as it both adds observers to all properties and displays the properties in a way that clearly differentiates "own properties" from the rest of the properties.

**Comment by rwwagner90** [comment]
@teddyzeenny is there a fix to do here or should we open an issue in Ember itself?

**Comment by rwwagner90** [comment]
@teddyzeenny @locks @rwjblue @krisselden this is an extremely old issue. Do we still need to do anything here? If not, I am inclined to close. It must not be a huge deal, since it has been open for 5 years 😛

**Comment by rwwagner90** [comment]
Due to lack of response, I am closing this issue. If anyone would like to reopen, and this is still an issue we want to tackle, let me know.
