### ISSUE TITLE
Ember.Descriptor removed from Ember - Inspector Broken

### ISSUE THREAD

**Issue by jmurphyau** [emberjs/ember-inspector#326]
[This PR](https://github.com/emberjs/ember.js/pull/10672) removed Ember.Descriptor which is required under "ember-debug/object-inspector"

[`var Descriptor = Ember.Descriptor;`](https://github.com/emberjs/ember-inspector/blob/c220a4ce765fd60f0981f66d5ef202d721251239/ember_debug/object-inspector.js#L5)

[`if (value instanceof Descriptor)`](https://github.com/emberjs/ember-inspector/blob/c220a4ce765fd60f0981f66d5ef202d721251239/ember_debug/object-inspector.js#L23)

**Comment by stefanpenner** [comment]
cc @teddyzeenny

**Comment by jmurphyau** [comment]
@teddyzeenny how do I get this version into my browser? Or will it have to wait for another release (after 1.7.2)?

**Comment by teddyzeenny** [comment]
@jmurphyau You can follow the [readme instructions](https://github.com/emberjs/ember-inspector#chrome) to use the master branch. You'll want to keep an eye out for the next version release so you can switch back to the auto-updating extension (the store one) once it's released.
