### ISSUE TITLE
Use promises inspector without ember app?

### ISSUE THREAD

**Issue by opsb** [emberjs/ember-inspector#331]
I'm trying to debug some hanging promises in a library that I'm working on. It's using RSVP promises but not ember, is there any way to get the ember-inspector to open anyway so I can use the promises tab?

**Comment by teddyzeenny** [comment]
The inspector currently depends on Ember (though it would be nice to work with RSVP only apps). Maybe you can try including Ember during debugging? If that's an option, you can try something like:

- Include Ember.js (which includes RSVP)
- Add a dummy div to your html file: `<div id="dummy-ember-app"></div>`
- Create an Ember application `Ember.Application.create({rootElement: '#dummy-ember-app'});`

**Comment by stefanpenner** [comment]
@opsb although not as nice, you can enable the following instrumentation hooks on RSVP and get some extra context: https://github.com/tildeio/rsvp.js#instrumentation

**Comment by teddyzeenny** [comment]
:+1:

**Comment by opsb** [comment]
@stefanpenner I did have a try at that but then I realised I could just add a dummy ember app to the page and hook into Ember.RSVP for the promise implementation. Now I get the inspector! :) Would be great to have the promise inspector as a separate dev tools panel but adding a dummy ember app to the page is good enough in a pinch.

**Comment by locks** [comment]
There's now a [Promises panel in Chrome dev tools](https://developers.google.com/web/shows/ttt/series-1/debugging-promises-w-devtools?hl=en)!
We don't have enough bandwidth to do the extraction, but if it's still valuable enough for you, the code is MIT ;)
