### ISSUE TITLE
can not read full url for debugging

### ISSUE THREAD

**Issue by Leooo** [emberjs/ember-inspector#334]
Hello, Im using ember-inspector for firefox, and I'd like to understand/debug the urls for my routes, but I don't seem to be able to display the full urls, I only see the start of each of them on the window.
Thanks.

**Comment by teddyzeenny** [comment]
I just noticed FF devtools doesn't show the title attribute on hover :(

It's a bug, thanks for reporting this.

Meanwhile the first workaround that comes to mind is to copy paste the URL (triple click, cmd + c, and cmd + v somewhere). Not sure if there's a better way.

**Comment by Leooo** [comment]
Aow right, tripleclick works, better than copy/pasting the whole lines on a blank sheet.

The most innovative frameworks will always have bugs, and that's fine. Thanks for EI this makes everything very clear.

**Comment by locks** [comment]
> teddy [2:32 PM]  
> fixed by resizable columns :dancer:
