### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by dmitry-php** [emberjs/ember-inspector#335]
After click on View Tree -> View / Components item the Uncaught TypeError: Expecting a function in instanceof check, but got undefined: 
inspectValueVM2112:2015
replacePropertyVM2112:1996
addPropertiesVM2112:1975 
(anonymous function)VM2112:1973
propertiesForMixinVM2112:1863
EmberObject.extend.mixinsForObjectVM2112:1782
EmberObject.extend.sendObjectVM2112:1723 EmberObject.extend.messages.inspectByIdember.debug.js:17794
applyember.debug.js:12425
sendEventember.debug.js:28664
exports.default.mixin.Mixin.create.triggerVM2112:1564
(anonymous function)VM2112:107
(anonymous function)VM2112:106
__exports__.default.Ember.Object.extend._messageReceivedVM2112:247
(anonymous function)ember.debug.js:224
Backburner.runember.debug.js:15813
runVM2112:246 (anonymous function)

My environent:
"jquery": "~1.9",
"ember": "1.12.0-beta.1",
"ember-data": "1.0.0-beta.16.1",
"ember-template-compiler": "http://builds.emberjs.com/tags/v1.12.0-beta.1/ember-template-compiler.js"

Chrome Browser.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/327

Until a new inspector version is released, you need to use Ember Inspector master with Ember canary.
