### ISSUE TITLE
Unexpected token on main html page

### ISSUE THREAD

**Issue by alex88** [emberjs/ember-inspector#341]
When the inspector is loaded after the webapp (for some unknown reason) it throws this error
```
Uncaught SyntaxError: Unexpected token d
```

on the first line of the html page. I'm running ember-cli 0.2.3 with latest ember

![screen shot 2015-04-07 at 15 57 40](https://cloud.githubusercontent.com/assets/436888/7024788/821675a8-dd3f-11e4-80de-135b2764f4c4.png)

when loading before the app everything works fine:

![screen shot 2015-04-07 at 15 57 50](https://cloud.githubusercontent.com/assets/436888/7024795/8d6ef3c6-dd3f-11e4-80ec-b497a821dcbd.png)

This happens randomly when refreshing. The url in this case was `http://localhost:4200/d`

It's not a real bug since the inspector works fine regardless of the errors, just wanted to point that out

**Comment by teddyzeenny** [comment]
Thanks for reporting this. Can you reproduce it in a JSbin, an online app, or a public repo? It is certainly a bug if it's logging an error.
