### ISSUE TITLE
Render Performance nested cutoff

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/ember-inspector#346]
When it gets too nested in the Redner Performance tab the time can be cut off

![screen shot 2015-04-16 at 1 43 34 pm](https://cloud.githubusercontent.com/assets/5893112/7186249/b8ab761c-e43e-11e4-9cee-22ee53221861.png)

**Comment by locks** [comment]
Addressed by https://github.com/emberjs/ember-inspector/pull/599.
