### ISSUE TITLE
Ember inspector not loading, random results

### ISSUE THREAD

**Issue by hussfelt** [emberjs/ember-inspector#349]
We need some help digging down why our ember inspectors are loading infrequently.

In all our developers environments the below image is more common than a working inspector:
![screenshot 2015-05-04 08 59 38](https://cloud.githubusercontent.com/assets/168864/7449701/f9887a6c-f23b-11e4-8dd2-b49347360161.png)

This has been an issue for us for a long time, and most frequent in our largest Ember-app.

Currently running, but not limited to:

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.10.0
DEBUG: Ember Data : 1.0.0-beta.16.1
DEBUG: Firebase   : 2.2.3
DEBUG: EmberFire  : 1.4.4
DEBUG: jQuery     : 2.1.3
DEBUG: -------------------------------
```

How is it that it loads and works properly sometimes but gives this error most times?
**How can we help dig down the error that causes this?**

**Comment by morgondag** [comment]
Accessing the application thought localhost/ip/ gives the same error.

**Comment by teddyzeenny** [comment]
We should focus on one specific app and try to reproduce the failure consistently. Is it possible that if the inspector is open before the page loads it works, and if the inspector is opened after the page loads it doesn't?

If you can point me to a public repo or an online app where that issue happens we can probably solve this faster.

**Comment by teddyzeenny** [comment]
Also useful: Ember Inspector version, and Google Chrome version.

**Comment by technomage** [comment]
We are seeing this as well.  Chrome Version 42.0.2311.135 (64-bit), Ember 1.11.3, Ember Data 1.0.0-beta16.  The tomster shows in the address bar consistently, so it detects the ember app is there.  There is presumably an exception not showing on the console.

**Comment by teddyzeenny** [comment]
Do you see "Ember Inspector Active" in the console?

**Comment by technomage** [comment]
Not when it fails to load.

**Comment by teddyzeenny** [comment]
Do you call `advanceReadiness` or `deferReadiness` anywhere your code?

**Comment by hussfelt** [comment]
Chrome version:
```Version 42.0.2311.90 (64-bit)```
Ember Inspector:
```1.7.3```

We also see the Tomster, even if it has failed loading the inspector.
We don't see the "Ember Inspector Active" when it fails - have not got it to load in a while, so I can confirm we see it when it does load.


@teddyzeenny yes - we use ```advanceReadiness``` and ```deferReadiness```. Should we not do that?

**Comment by teddyzeenny** [comment]
@hussfelt you can use `advanceReadiness` and `deferReadiness`, but if you call them more than you should, or at the wrong time, the inspector will break.

- You should call `advanceReadiness` as many times as you called `deferReadiness`. This means that if you called `deferReadiness` once, you should later call `advanceReadiness` only once.
- You should not call `advanceReadiness` or `deferReadiness` after the app has booted.

These bugs are not obvious, but cause the inspector to malfunction. One quick way to make sure they are not being called incorrectly is by checking `YourApp._readinessDeferrals` while the app is booted. It should be 0. If it is < 0, you are calling `advanceReadiness` more than you are calling `deferReadiness`. If if is > 0, you are calling `deferReadiness` after the app has booted.

**Comment by technomage** [comment]
No calls to advanceReadiness or deferReadiness.

**Comment by hussfelt** [comment]
@teddyzeenny inactivating the only ```advanceReadiness``` and ```deferReadiness``` we have has no affect.

It's unclear for me what states a "booted app", are there any docs available that defines this? :-)

Part-pseudo-code for where we have the deferral in our code - if that helps:

```javascript
import config from '../config/environment';

export function initialize(container, application) {
    // Wait until all of the following promises are resolved
    application.deferReadiness();

    application.inject('route', 'sessionService', 'service:session');
    application.inject('controller', 'sessionService', 'service:session');
    application.inject('component', 'sessionService', 'service:session');
    application.inject('adapter', 'sessionService', 'service:session');
    application.inject('serializer', 'sessionService', 'service:session');
    application.inject('view', 'sessionService', 'service:session');

    // Get session-service
    var session = container.lookup('service:session');

    // Find the current customer, use promise to reflect to other controllers
    if (session.hasSession()) {
        // Get the store
        var store = container.lookup('store:main');

        // Fetch the user
        store.find('Customer', session.get('userId')).then(function(customer) {
            // Set customer to application controller
            session.set('user', customer);

            // preload the application
            session.preloadApplication();

            // Continue the Application boot process, allowing other Initializers to run
            application.advanceReadiness();
        }, function() {
            // Kill sesion object
            session.set('authToken', '');

            // Unload all data
            store.unloadAll('...');

            // Continue the Application boot process, allowing other Initializers to run
            application.advanceReadiness();
        });
    } else {
        // Continue the Application boot process, allowing other Initializers to run
        application.advanceReadiness();
    }
}

export default {
    name: 'session-service',
    after: 'store',
    initialize: initialize
};
```

**Comment by anlumo** [comment]
I'm seeing the same here with all of my Ember projects. Chrome version 42.0.2311.135.

A temporary workaround is to close the inspector, close the browser window, and then open everything. Then it has a chance to work again, just reloading the page does not work.

**Comment by hussfelt** [comment]
We're seeing major improvements after bumping ember-data, firebase and jquery.
I have no idea why.

We have not touched any relevant code, and I can confirm that checking out a previous commit gives the same improved result!

````
-------------------------------
Ember      : 1.10.0
Ember Data : 1.0.0-beta.17
Firebase   : 2.2.4
EmberFire  : 1.4.4
jQuery     : 2.1.4
-------------------------------
````

**Comment by teddyzeenny** [comment]
Is anyone still having issues here?

**Comment by locks** [comment]
Closing from inactivity. Please let us know if this is still a problem.
