### ISSUE TITLE
Drop failed promises into console

### ISSUE THREAD

**Issue by vvs-code** [emberjs/ember-inspector#350]
Hi

As I understand when some Ember promise failed Inspector catch this and display it at Promises tab. And console still clear. Is any option to throw errors into console?

**Comment by teddyzeenny** [comment]
Using the inspector (in the Promises tab):
If the failure is an `Error`, you should see a "stack trace" link next to the error. If the failure reason is not an error, you should see a "$E" link next to it. Clicking either link will send it to the console.

By code:
If the promise has an error handler, add a log to the promise's failure callback:
```js
promise.catch(e => {
  console.log(e.message, e.stack);
});
```
If the promise's failure is not handled, Ember should automatically log the error to the console. It uses RSVP's error event. You can also listen to the error event yourself:
```js
// This will log all failed promises that don't have an error handler.
Ember.RSVP.on('error', e => {
  console.log(e.message, e.stack);
});
```

Let me know if this is what you're looking for.

**Comment by stefanpenner** [comment]
We already do this logging in ember. No need to add anything, unless your app disabled it or you are using an old version of ember
