### ISSUE TITLE
[Glimmer] Render perf - add better descriptions for nodes that don't have a view instance

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#354]
After the glimmer update, render nodes that don't have a view instance show up as "unknown view". This will require updates to [Ember core](https://github.com/emberjs/ember.js/blob/fd3d54d02f532f00776a957ef663bc8bc4f93511/packages/ember-htmlbars/lib/system/instrumentation-support.js) instrumentation and to the [Ember Inspector](https://github.com/emberjs/ember-inspector/blob/0022e4e4b409e0722ab8a9976cab7b8bb2f763d7/ember_debug/models/profile-node.js#L15-L24).

**Comment by locks** [comment]
Should no longer apply due to changes in Glimmer design.
