### ISSUE TITLE
View/Template link is blank 

### ISSUE THREAD

**Issue by elidupuis** [emberjs/ember-inspector#356]
Any idea why some of my components don't show up in the inspector? They are in the list but the View/Template column is blank which makes it harder to inspect...

![screen shot 2015-05-11 at 4 04 45 pm](https://cloud.githubusercontent.com/assets/196410/7576094/98bddfc6-f7f7-11e4-9595-f4918f684e5c.png)

Just trying to figure out if this is caused by something on my end—I've seen this happen a couple of times and it's consistent when it does happen. Thoughts?

**Comment by teddyzeenny** [comment]
I think it's because the view name ends with `view`, the replace regex has a bug. I am currently rewriting this part of the code to support glimmer and I have already encountered and fixed this bug. Will be resolved in the next release.

**Comment by elidupuis** [comment]
Awesome, thanks!
