### ISSUE TITLE
Deprecation warning with Ember 1.12.0

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember-inspector#361]
Seeing deprecation warning after updating:

`DEPRECATION: Using the same function as getter and setter is deprecated.` from: [ember_debug/promise-debug.js:92](https://github.com/emberjs/ember-inspector/blob/a344132d71f0d2ee23a813667a477e3e5538c2f6/ember_debug/promise-debug.js#L92-L98)

**Comment by joshhornby** [comment]
I am seeing this as well, it seems to be getting the incorrect lines numbers. 

For example

![screen shot 2015-05-14 at 16 52 02](https://cloud.githubusercontent.com/assets/5455767/7635554/91c893aa-fa59-11e4-9d52-43d7be3a0404.png)

And lines 6 and 7 of subscription are:

![screen shot 2015-05-14 at 16 52 34](https://cloud.githubusercontent.com/assets/5455767/7635569/a3d02bda-fa59-11e4-9bd3-f72e49c9f0b0.png)

**Comment by teddyzeenny** [comment]
@SaladFork we need to use the computed polyfill https://github.com/emberjs/ember-inspector/blob/0022e4e4b409e0722ab8a9976cab7b8bb2f763d7/ember_debug/models/promise.js#L1

@joshhornby the line numbers are correct. `attr` and `belongsTo` are triggering the deprecation. It's Ember Data.

**Comment by joshhornby** [comment]
Ah ok! Thanks

**Comment by SaladFork** [comment]
@teddyzeenny Should we use the computed polyfill or upgrade Ember Inspector's Ember version to 1.12.0 and use [the implemented new syntax](http://emberjs.com/blog/2015/05/13/ember-1-12-released.html#toc_new-computed-syntax)?

**Comment by teddyzeenny** [comment]
@SaladFork Ember Inspector needs to support all 1.x versions. We can't use the new syntax. We need to use the old syntax for < 1.12, and the new syntax for >= 1.12, which is what the polyfill does.

**Comment by teddyzeenny** [comment]
ember-debug runs on your app's Ember version, not the one we specify here, so we have no control over the Ember version

**Comment by SaladFork** [comment]
@teddyzeenny That makes sense!

Sent a PR for an attempt to fix -- note I don't currently have an environment to test this change.
