### ISSUE TITLE
Component rendered with {{component}} inside {{#each}} cannot be inspected

### ISSUE THREAD

**Issue by ramybenaroya** [emberjs/ember-inspector#365]
Components which rendered with the [{{component}} helper](http://emberjs.com/blog/2015/03/27/ember-1-11-0-released.html#toc_component-helper) are not shown in the components inspection view

**Comment by teddyzeenny** [comment]
Thanks for reporting this! Can you add a screenshot of the inspector's Info tab?

**Comment by ramybenaroya** [comment]
Apparently, this happens inside {{#each}} when iterating over an array with dynamic component names.
Here's a fiddle: [code](https://jsfiddle.net/4hq2un16/10/), [output](https://jsfiddle.net/4hq2un16/10/embedded/result/).
 Ember Inspector Info:
![issue365](https://cloud.githubusercontent.com/assets/4154801/7703427/97b1abc2-fe40-11e4-9e4b-746bb6512056.png)

**Comment by teddyzeenny** [comment]
It looks like any component inside an `{{each}}` isn't included in the view tree. Not just the `{{component}}` helper.

**Comment by Glavin001** [comment]
I am also experiencing this issue.

**Comment by ef4** [comment]
This breaks the view tree for anybody using liquid-fire, because all those helpers use `{{#each}}` internally.

**Comment by teddyzeenny** [comment]
Should be fixed by https://github.com/emberjs/ember-inspector/pull/428
