### ISSUE TITLE
Error message: Failed to execute 'postMessage' on 'MessagePort': An object could not be cloned.

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember-inspector#366]
also on ember cli 0.2.5 and ember-inspector 1.8.0 and google chrome Version 42.0.2311.152 (64-bit), this happens when clicking promises tab

```

DEBUG: -------------------------------
ember.js:3935DEBUG: Ember                     : 1.9.1
ember.js:3935DEBUG: Ember Data                : 1.0.0-beta.16.1
ember.js:3935DEBUG: Handlebars                : 2.0.0
ember.js:3935DEBUG: jQuery                    : 1.11.3
ember.js:3935DEBUG: Ember Simple Auth         : 0.7.3
ember.js:3935DEBUG: Ember Simple Auth Testing : 0.7.3
ember.js:3935DEBUG: -------------------------------
VM168:80 Ember Inspector Active

VM168:93 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Failed to execute 'postMessage' on 'MessagePort': An object could not be cloned.
Stack trace: Error: Failed to execute 'postMessage' on 'MessagePort': An object could not be cloned.
    at Error (native)
    at BasicAdapter.default.extend.sendMessage (<anonymous>:274:31)
    at exports.default.Ember.Object.extend.send (<anonymous>:194:26)
    at exports.default.Ember.Object.extend.send (<anonymous>:2673:27)
    at exports.default.Mixin.create.sendMessage (<anonymous>:1637:24)
    at exports.default.EmberObject.extend.promisesUpdated (<anonymous>:2855:12)
    at exports.default.EmberObject.extend.getAndObservePromises (<anonymous>:2838:12)
    at exports.default.EmberObject.extend.messages.getAndObservePromises (<anonymous>:2751:14)
    at apply (http://localhost:4200/provider/assets/vendor.js:34729:27)
    at sendEvent (http://localhost:4200/provider/assets/vendor.js:29187:13)
```

**Comment by null-null-null** [comment]
Also on the Deprecations tab. If a the Deprecations tab is open and a new deprecation is triggered, this error comes up:

    Uncaught TypeError: Cannot read property 'split' of undefined

This error isn't triggered if the Deprecations tab is never opened.

**Comment by Fed03** [comment]
+1

**Comment by notmessenger** [comment]
Experiencing the same thing when accessing this code at http://localhost:4200 : https://github.com/notmessenger/sl-ember-translate/tree/4f856915628def11995914d6135e6d4528686521

Environment:

* Ember CLI 1.13.1
* Ember 1.13.3
* OS X 10.10.4
* Chrome Version 43.0.2357.132 (64-bit)

**Comment by oriSomething** [comment]
+1

**Comment by notmessenger** [comment]
Also experiencing on:

* Ember CLI 1.13.6
* Ember 1.13.5
* OS X 10.10.4
* Chrome Version Version 43.0.2357.130 (64-bit)

**Comment by FutoRicky** [comment]
Happening to me also with an Ember-cli 1.13.1 addon

**Comment by teddyzeenny** [comment]
Anyone can consistently reproduce this on a Jsbin or public repo?

**Comment by notmessenger** [comment]
@teddyzeenny https://github.com/softlayer/sl-ember-translate/tree/EmberCLI-1.13.6

**Comment by teddyzeenny** [comment]
Looks like Chrome is refusing to clone `Ember.A()`. If I'm not mistaken, everyone experiencing this issue has Ember prototype extensions disabled.  I'm working on a workaround.

**Comment by rwjblue** [comment]
> everyone experiencing this issue has Ember prototype extensions disabled

By default Ember CLI disables prototype extensions while developing addons, so it is a much more common thing that it used to be...

**Comment by Asherlc** [comment]
I'm getting this error with v2.0.5 when clicking the "Render Performance" tab
