### ISSUE TITLE
Deprecation in console not showing up in inspector

### ISSUE THREAD

**Issue by sarus** [emberjs/ember-inspector#367]
I have a deprecation showing up in the console that does not show up in the ember inspector.

Here's the deprecation (note the deprecation is thrown before the ember version information)

```
DEPRECATION: Using the same function as getter and setter is deprecated. See http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter for more details.
        at Descriptor.ComputedProperty (https://neontetra.breach/assets/vendor.js:21378:17)
        at computed (https://neontetra.breach/assets/vendor.js:21840:14)
        at <anonymous>:2798:26
        at requireModule (<anonymous>:40:28)
        at requireModule (<anonymous>:36:24)
        at <anonymous>:6614:45
        at triggerOnce (<anonymous>:6646:7)
        at Object.runLoadHooks (https://neontetra.breach/assets/vendor.js:42142:14)
        at https://neontetra.breach/assets/vendor.js:13752:12
ember.debug.js:4888 DEBUG: -------------------------------
ember.debug.js:4888 DEBUG: Ember             : 1.12.0
ember.debug.js:4888 DEBUG: Ember Data        : 1.0.0-beta.17
ember.debug.js:4888 DEBUG: jQuery            : 1.11.3
ember.debug.js:4888 DEBUG: Ember Simple Auth : 0.8.0-beta.2
ember.debug.js:4888 DEBUG: -------------------------------
```

![image](https://cloud.githubusercontent.com/assets/306319/7757651/123efe3e-ffd2-11e4-94c2-b426ab4b080b.png)

Here is the only deprecation I see in the inspector:

![image](https://cloud.githubusercontent.com/assets/306319/7757681/38fa1b58-ffd2-11e4-92af-b6cf51474c99.png)

You'll  notice the deprecation shown is for the one other deprecation warning I have in the console.  I'm actually having a hard time figuring out where the mystery getter/setter deprecation is in in my own code (the deprecation that doesn't show up in the inspector)

Any ideas on why this isn't being picked up by inspector and/or where the actual deprecation could be.  It's really bothering me that I can't find it in my code haha.

Thanks!

**Comment by rwjblue** [comment]
My guess is that this *might* be being triggered by the inspector itself.  The deprecation was recently fixed in https://github.com/emberjs/ember-inspector/pull/362, but off the top of my head I don't think it has been released just yet...

**Comment by sarus** [comment]
Ah thanks!  haha.  I'll stop looking for it in my code.
