### ISSUE TITLE
Show angle-bracket components

### ISSUE THREAD

**Issue by cjroebuck** [emberjs/ember-inspector#369]
Maybe I'm jumping the gun here a little but is the latest version of the inspector supposed to show angle bracket components in the View Tree? If so, they aren't showing up for me. (v1.8.0)

**Comment by teddyzeenny** [comment]
Did you check the "components" checkbox in the view tree? It's supposed to be working. Can you reproduce this in a jsbin?

**Comment by teddyzeenny** [comment]
Is it possible the component is inside an `{{#each}}`?

**Comment by locks** [comment]
Since angle brackets components were only in Ember for one beta version and are currently being revamped, I'm closing this issue.
