### ISSUE TITLE
Move ember-debug code to ES6

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#377]
Refactor [ember-debug](https://github.com/emberjs/ember-inspector/tree/c6a4efc9a4e2486aab0a5b3558300404aaf1c078/ember_debug):

- Replace all `var` with `const` and `let`
- Use arrow function for callbacks (instead of using the self/bind approach)
- Use destructuring to import Ember classes: const { RSVP, computed, run, Route } = Ember.
- Use the new method definition syntax in object literals: { foo() {} }

Part of https://github.com/emberjs/ember-inspector/issues/360

**Comment by Mawaheb** [comment]
This is almost complete, will raise a  PR soon.

**Comment by teddyzeenny** [comment]
Done in https://github.com/emberjs/ember-inspector/pull/387
