### ISSUE TITLE
Add comment blocks to classes/methods/properties

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#378]
Part of https://github.com/emberjs/ember-inspector/issues/360

Use YUIDoc format to comment on all classes/methods/properties.

Classes, methods, and properties should have a detailed description above them about what they do and how they are used. If a method/property is clearly self descriptive, no description is needed.

Classes need the `@namespace` and `@class` keywords.
Methods need the `@method method-name`, `@param {Type} name Description`, `@return {Type} Description` keywords.
Properties need  the `@property property-name`, `@type {Type}`, `@default default-value`.

Computed properties are `@property` (not `@method`).

Example:

``` js
// app/adapters/basic.js

const { Object: EmberObject } = Ember;

/**
 * This is the parent adapter to be extended by all other adapters. 
 * It provides an abstraction to keep the code browser/environment agnostic. 
 * Adapters are instantiated and injected into Ember objects automatically. 
 * Properties and methods in this parent class need to be overridden.
 * 
 * @namespace Adapters
 * @class Basic
 */
export default EmberObject.extend({

  /**
   * Inspect a specific DOM element. This usually means using
   * the current environment's tools to inspector the element in the DOM tree.
   *
   * For example, in Chrome, `inspect(elem)` will open the Elements tab in dev tools
   * and highlight the element.
   *
   * @method inspectElement
   * @param {DOM Element} elem
   */
  inspectElement function(/* elem */) {},

  /**
   * Indicates whether the current environment
   * supports opening up a specific file for debugging.
   * An example is opening up a resource in the Chrome
   * Devtools "Sources" panel.
   *
   * @property canOpenResource
   * @type {Boolean}
   * @default false
   */
  canOpenResource: false
});
```

**Comment by pete-the-pete** [comment]
@teddyzeenny I'd like to help with this, it would be a good way to get to know the code.

**Comment by locks** [comment]
@pete-the-pete are you still interested?

**Comment by pete-the-pete** [comment]
Yes, still interested, but obviously got busy and forgot about this.  I
haven't worked on in since that PR.  I can start contributing again next
week, but it someone else is ready to take it, I don't want to be in the
way.

**Comment by locks** [comment]
@pete-the-pete no worries, this is in the "nice to have" camp so you're not blocking work. See you next week!

**Comment by ynotdraw** [comment]
I'd love to lend a hand here!

**Comment by rwwagner90** [comment]
@ynotdraw please do! There is a *lot* of magic and complex code in Inspector, so the more docs the better!

**Comment by rwwagner90** [comment]
@ynotdraw let's sync up on what you would like to work on here, and split this into more concrete and manageable chunks of work.
