### ISSUE TITLE
Replace Object And Array Controllers With Ember.Controller and remove ItemControllers

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#379]
Part of https://github.com/emberjs/ember-inspector/issues/360

`Ember.ObjectController`, `Ember.ArrayController` and `itemController` are going away. We need to replace them with `Ember.Controller`. 
- Create `app/controllers/object.js` that exports `Ember.Controller`. This will prevent Ember from automatically creating object controllers:

``` js
// app/controllers/object.js
import Ember from 'ember';
const { Controller } = Ember;
export default Controller;
```
- Replace all `Ember.ObjectController` with `Ember.Controller`. This means that properties that access model properties will need to use `model.propertyName` instead of just `propertyName` since the Controller will no longer be a proxy.
- Create `app/controllers/array.js` that exports `Ember.Controller`. This will prevent Ember from automatically creating array controllers:

``` js
// app/controllers/array.js
import Ember from 'ember';
const { Controller } = Ember;
export default Controller;
```
- Replace all `Ember.ArrayController` with `Ember.Controller`. This means that all array methods/properties called on the controller will need to be called on the model instead. Example: `this.forEach` will need to be `this.get('model').forEach`, `this.get('length')` will need to be `this.get('model.length')`. `sortProperties` will also no longer work. We would need to create a computed property that sorts the model. `{{#each}}` and `{{#each controller}}` need to be replaced with `{{#each model as |item|}}`.
- Replace `itemController` in `{{#each}}` helpers with components.  
  Old Version:

``` handlebars
{{!-- app/templates/people.hbs --}}
{{#each model itemController="person-item"}}
  {{if #canDrive}}
    Old enough to drive
  {{/if}}
{{/each}]
```

``` js
// app/controllers/person-item.js
export default Ember.ObjectController.extend({
  canDrive: computed.gte('age', 18);
});
```

New Version:

``` handlebars
{{!-- app/templates/people.hbs --}}
{{#each model as |person|}}
  {{#person-item model=person as |personItem|}}
    {{#if personItem.canDrive}}
      Old enough to drive
    {{/if}}
  {{/person-item}}
{{/each}}
```

``` js
// app/components/person-item.js
import Ember from 'ember';
const { Component, computed: { gte } } = Ember;
export default Component.extend({
  canDrive: gte('model.age', 18)
});
```

``` hbs
// app/components/person-item.hbs
{{yield this}}
```

**Comment by rwjblue** [comment]
Might want to lump `itemController` in with this one...

**Comment by teddyzeenny** [comment]
@rwjblue :+1: added item controller.

**Comment by camskene** [comment]
I can work on this.

**Comment by camskene** [comment]
@teddyzeenny should I branch off master or stable? I noticed both of those branches have ~60 failing tests.

**Comment by teddyzeenny** [comment]
@camskene hey, sorry for the mess. Regenerator library [made a breaking change](https://github.com/babel/babel/issues/1685) in a *patch* version and broke everything. Working on a fix.

To answer your question, all PRs go against master, so always branch off master.

**Comment by teddyzeenny** [comment]
Should be fixed with https://github.com/emberjs/ember-inspector/pull/384.

Make sure to `rm -rf node_modules && npm cache clean && npm install`

**Comment by teddyzeenny** [comment]
You won't be able to use block params (`{{yield this}}`) until we upgrade to Ember 1.11

**Comment by bjoska** [comment]
@camskene You working on this one?

**Comment by camskene** [comment]
@bjoska If you could pick it up that would be great! I was investigating last night and it's a bit beyond my ember foo...

**Comment by bjoska** [comment]
Got it! 

Cheers!

**Comment by teddyzeenny** [comment]
If anyone has any questions feel free to ping me (`@teddy`) on the [Ember Community slack](http://embercommunity.slack.com) #ember-inspector channel. Automated invite at https://ember-community-slackin.herokuapp.com

**Comment by zzr994** [comment]
Hi teddyzeenny,
We are using ember 1.9.1 and we want to move towards ember 2.0.0.  As an intermediate step we are using ember 1.11.3 and get rid of all the depreciation warnings.  One of the items that need to be refactored is the ArrayController and the ObjectController.  We have managed to take care of the ArrayController.  The only remaining issue is refactoring the ObjectController.

In the templates we have lot of code that looks like the following:
                {{#each runningModules itemController="module" as |module|}}
                    {{module-tab class="inline-block" module=module tagName='div'}}
                {{/each}}
The same ObjectController is used in multiple places allowing the properties defined on the ObjectController to be used multiple times. This provides an advantage of code re-use.

What do you think is the best way to refactor the code in the ObjectController so that it can be used multiple times?

**Comment by rwwagner90** [comment]
Closing this as these controller types have been removed already.
