### ISSUE TITLE
Replace inline views with components

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#380]
Part of https://github.com/emberjs/ember-inspector/issues/360

Look for cases of `{{view "my-view"}}` in templates and replace them with components. Main difference to look out for is that the context in views is the same as the template calling them, whereas components are isolated. So be sure to pass in the required info to components so they can access them in their templates.

**Comment by Mawaheb** [comment]
I will give this a shot if no one is already working on it.
