### ISSUE TITLE
 Replace bind-attr with attribute="{{prop}}".

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#381]
Part of https://github.com/emberjs/ember-inspector/issues/360

Thanks to the htmlbars rewrite, we can now just use `{{value}}` inside an attribute.

Look for usage of `bind-attr` and replace it with attribute="{{value}}". Example:

```hbs
{{!-- old --}}
<div {{bind-attr class="myClass :static-class"}}></div>
```

```hbs
{{!-- new --}}
<div class="{{myClass}} static-class"></div>
```

**Comment by camskene** [comment]
I could take a look at this.

**Comment by Mawaheb** [comment]
@camskene are you still working on this one?

**Comment by teddyzeenny** [comment]
@Mawaheb PR opened: https://github.com/emberjs/ember-inspector/pull/382. The problem is we need to update to Ember 1.12 first.

**Comment by camskene** [comment]
@Mawaheb the attributes have all been changed. I believe it can be pulled in when master is updated to 1.12.

**Comment by Mawaheb** [comment]
:+1:

**Comment by locks** [comment]
Fixed!
