### ISSUE TITLE
Error message: value.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by benedikt-d** [emberjs/ember-inspector#386]
Error message: value.hasOwnProperty is not a function
Stack trace: TypeError: value.hasOwnProperty is not a function at inspect (<anonymous>:1962:19)...

This happens when I click on a object in the store in the inspector

**Comment by teddyzeenny** [comment]
This has been resolved by https://github.com/emberjs/ember-inspector/pull/383. It be fixed in the next release.
