### ISSUE TITLE
Error message: value.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by Eptis** [emberjs/ember-inspector#388]
I'm getting this error on the latest version when clicking on a variable in the inspector.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/383. Will be fixed in the next release (this weekend).

**Comment by Eptis** [comment]
Cool thanks!


—
Met vriendelijke groet / Kind regards,


Dennis Tel
