### ISSUE TITLE
Inspector does not boot on Ember 1.13.0

### ISSUE THREAD

**Issue by martypenner** [emberjs/ember-inspector#392]
The inspector shows "Ember application not detected" when loading the inspector on a standard Ember 1.13.0 app. Versions 1.12.* are still fine. Here some jsbins demonstrating the problem:

1.12.1:
http://output.jsbin.com/tatono

1.13.0:
http://output.jsbin.com/libuvi

#### Screenshots

1.12.1:
![screen shot 2015-06-13 at 13 06 36](https://cloud.githubusercontent.com/assets/1819798/8145231/abb5ea16-11cd-11e5-8138-8cab30de709a.png)

1.13.0:
![screen-shot-2015-06-13-at-13 07 57](https://cloud.githubusercontent.com/assets/1819798/8145235/b5ecb00a-11cd-11e5-8298-ef2f3bb689d4.jpg)

**Comment by atsjj** [comment]
+1 having same issue

**Comment by teddyzeenny** [comment]
I'm fixing all the things today - this is certainly a priority.

**Comment by stefanpenner** [comment]
@teddyzeenny <3

**Comment by atsjj** [comment]
@teddyzeenny big time thanks!
