### ISSUE TITLE
Routes Panel (almost) Empty in 1.13

### ISSUE THREAD

**Issue by dpetersen** [emberjs/ember-inspector#396]
I recently upgraded a pretty simple application to 1.13. I was running ember-inspector master that I locally built on the weekend, and then I moved to what is in the chrome store today trying to troubleshoot this bug. My app only shows `application_loading` in the Routes panel. I generated a brand new app with ember-cli. I can see the routes correctly while the app is 1.12, and then they disappear (save for `application_loading`) when I switch to 1.13.

**Comment by locks** [comment]
Are you using the newest version of the Inspector? https://github.com/emberjs/ember-inspector/issues/395#issuecomment-112024062

**Comment by dpetersen** [comment]
Yup, this is in 1.8.2. When I first encountered the bug today I was still running a locally-built version from this weekend's master (which is still up-to-date as of this writing), but I went to the latest Chrome store version (just double-checked it) and still seeing the problem.

**Comment by dpetersen** [comment]
That fixed it, thank you!
