### ISSUE TITLE
Deprecation warning in console not showing up in deprecations tab (Ember v1.13.0)

### ISSUE THREAD

**Issue by sarus** [emberjs/ember-inspector#397]
After upgrading my version of ember to v1.13.0 I'm getting the following deprecation warning in the console but not in the inspector tab.

```
ember.debug.js:5442 DEPRECATION: Ember.reduceComputed is deprecated. Replace it with plain array methods
        at Descriptor.ReduceComputedProperty (https://neontetra.breach/assets/vendor.js:40073:31)
        at Object.reduceComputed (https://neontetra.breach/assets/vendor.js:40459:14)
        at https://neontetra.breach/assets/vendor.js:94607:36
        at https://neontetra.breach/assets/vendor.js:101698:4
ember.debug.js:5361 DEBUG: -------------------------------
ember.debug.js:5361 DEBUG: Ember                     : 1.13.0
ember.debug.js:5361 DEBUG: Ember Data                : 1.0.0-beta.18
ember.debug.js:5361 DEBUG: jQuery                    : 1.11.3
ember.debug.js:5361 DEBUG: Ember Simple Auth         : 0.8.0-beta.3
ember.debug.js:5361 DEBUG: Ember Simple Auth Testing : 0.8.0-beta.3
ember.debug.js:5361 DEBUG: -------------------------------
```

The warning comes before the ember information.  The last time this happened in #367 it turned out the inspector itself was throwing the deprecation.  Not sure if this is the case again but I don't think I'm using `reduceComputed` in my application anymore.  

![image](https://cloud.githubusercontent.com/assets/306319/8197739/3b263144-146a-11e5-8272-ab0e2678ba4a.png)

**Comment by jeremytm** [comment]
I'm seeing this too with some deprecations caused by Ember Simple Auth. Maybe certain deprecations are caused before the inspector can grab them?

**Comment by teddyzeenny** [comment]
Yes, deprecations thrown before the app boots cannot be caught by the inspector because the inspector boots _after_ the app boots.

**Comment by sarus** [comment]
This deprecation is actually thrown by ember-data.  The latest 1.13.0 version of Ember data removes it.  Thank you for the info!
