### ISSUE TITLE
Deprecations don't show where the error is in application code

### ISSUE THREAD

**Issue by sarus** [emberjs/ember-inspector#398]
I just updated to Ember v1.13.0 and have some new deprecations I'm working through.  I noticed that the deprecations listed under the deprecations tab don't actually show where in my code the deprecation is occurring.  It always points to a line in `Ember.debug` which isn't particularly useful for finding and fixing the deprecation issue.

I also noticed that clicking on the "Trace in Console" button doesn't seem to do anything.

Is this expected behavior?  Is the inspector supposed to provide line numbers?  Note that the deprecation warnings thrown in the console are not helpful either and do not show line numbers so this might not be an ember-inspector issue.

Thank you!

![image](https://cloud.githubusercontent.com/assets/306319/8197786/17646004-146b-11e5-88c5-5c70c6d9d79f.png)

**Comment by jeremytm** [comment]
I'm seeing this too. But I assume the trace is supposed to provide info on where the deprecation is actually coming from.

Trace in Console is working for me (Ember 1.13.0), though the trace still begins within ember.debug.js as well. So I'm confused about whether it's a deprecation coming from within Ember's own code, or if it's a genuine issue in my own code, which the trace isn't communicating very well...

**Comment by teddyzeenny** [comment]
The inspector is supposed to point you to the line _in your app_ and not to the line in the Ember.js file. However if the stack trace is not long enough to reach the app lines, the inspector cannot know the app line causing the deprecation and therefore shows the Ember.js line as a fallback.

> I also noticed that clicking on the "Trace in Console" button doesn't seem to do anything.

This may be a bug. Did you make sure it's not printing anything to the console? Can you reproduce this in a jsbin?

**Comment by sarus** [comment]
@teddyzeenny False alarm on the "trace in console".  I was being an idiot and didn't notice that clicking on the button caused output to go to console.  I think I was expecting something to visibly happen on the deprecations tab despite the name of the button which I should have picked up on.

In regards to the stack traces being "too short", is there a way to ensure that the stack trace goes all the way back to application code?  All my current deprecation warnings seem to end in ember code.

**Comment by teddyzeenny** [comment]
@sarus it would be nice if browsers would provide us with an api to open the console when the button is clicked - it is certainly confusing when you click something and nothing happens on the screen.

As for stack traces you can try setting `Error.stackTraceLimit=50` in Chrome and see if that fixes the issue. If it does, we should look into making it part of the inspector.

**Comment by sarus** [comment]
Unfortunately `Error.stackTraceLimit=50` did not seem to change the contents of the stack trace.  (I just set it from the console in chrome developer tools). 

```
Ember.ENV.RAISE_ON_DEPRECATION = true
Ember.LOG_STACKTRACE_ON_DEPRECATION: true;
```

Are both of these turned on by default?  I did not see them set by ember-cli but I'm assuming they must get turned on somewhere since I am seeing stacktraces on the deprecation warnings (even if the stacktraces don't go back to my app code).

**Comment by teddyzeenny** [comment]
@sarus did you set `Error.stackTraceLimit=50` before the deprecations were triggered? Best way to make sure is to set it in the app code (example in `app/app.js`)

**Comment by sarus** [comment]
Ah, you were right. That worked Thanks!   Just added to the top of `app/app.js`

**Comment by jherdman** [comment]
My apologies, I hate to dredge up the past, but I'm having this problem too. I've tried adjusting the stack trace limit to 100, and I've placed it at the top of my `app/app.coffee` file as such:

```cofffeescript
Error.stackTraceLimit = 100

`import Ember from 'ember'`
`import Resolver from 'ember/resolver'`
`import loadInitializers from 'ember/load-initializers'`
`import config from './config/environment'`

Ember.MODEL_FACTORY_INJECTIONS = true

App = Ember.Application.extend
  modulePrefix: config.modulePrefix
  podModulePrefix: config.podModulePrefix
  Resolver: Resolver

loadInitializers(App, config.modulePrefix)

`export default App`
```

Is there something else I could be missing?
