### ISSUE TITLE
deprecations fail to load when exception thrown

### ISSUE THREAD

**Issue by eccegordo** [emberjs/ember-inspector#400]
Not sure if this is useful. But I am able to get into a state where it says I have deprecations but won't show anything. Using version 1.8.2.

Not clear if this is due to problems in my code or ember inspector's code.

![inspector_problem](https://cloud.githubusercontent.com/assets/497659/8218712/825d46a8-14f9-11e5-82ad-c4e0d122a5eb.png)

The split error seems to come from this

```
  function fromStackProperty(stackString) {
    var chrome = /^\s*at (?:((?:\[object object\])?\S+(?: \[as \S+\])?) )?\(?((?:file|http|https):.*?):(\d+)(?::(\d+))?\)?\s*$/i,
        gecko = /^\s*(\S*)(?:\((.*?)\))?@((?:file|http|https).*?):(\d+)(?::(\d+))?\s*$/i,
        lines = stackString.split('\n'),
        stack = [],
        parts;
```

Maybe some better guards against undefined?

**Comment by sarus** [comment]
I think this is related to the issue I posted on the ember repo:

https://github.com/emberjs/ember.js/issues/11490

I get the same split error you're seeing as well.  Here's the full stacktrace for that:

```
Uncaught TypeError: Cannot read property 'split' of undefinedfromStackProperty @ VM2674:1481exports.default.EmberObject.extend.map @ VM2674:1376exports.default.EmberObject.extend.fetchSourceMap @ VM2674:877(anonymous function) @ VM2674:921exports.default.EmberObject.extend.sendPending @ VM2674:901Backburner.run @ ember.debug.js:222(anonymous function) @ ember.debug.js:490
```

**Comment by teddyzeenny** [comment]
Thanks for the report. I will investigate. I know it may not be easy, but if you can reproduce this in a Jsbin or public repo it would make fixing it much easier.

**Comment by sarus** [comment]
@teddyzeenny Thank you for looking into this.  I'll be traveling this weekend and won't have much time but will see if I can isolate the issue when I get back next week.  It only happens on one of my pages and the error is delayed (i.e., the entire page loads, and then 2 seconds later the error is thrown).  

If you have any theories that can help to narrow it down just let me know.

**Comment by eccegordo** [comment]
@teddyzeenny really hard to tell if this is inspector code or my code. I will continue to investigate and if I can narrow down anything I will post back. My app is fairly complicated Ember CLI app so not sure what the interactions are with inspector. Or where to even really start with a JSBin.

If in your research you find any possible suspects let me know.  I can even try master build of inspector on my machine with my app and report back. Basically deprecations tool is completely broken for me at the moment.

If this is related to source maps I have another idea.

I am on ember cli 0.2.7 and I always get this message upon boot up:

```
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT: no such file or directory, open '/Volumes/EmberCliRamdisk/my-app-name/tree_merger-tmp_dest_dir-EtH7DsS2.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
```

Is there any chance this could be related? There is already an old issue in route-recognizer repo.

https://github.com/tildeio/route-recognizer/issues/44

**Comment by eccegordo** [comment]
This is probably not that helpful. But here is a JSBin that explicitly causes an error.

http://jsbin.com/saqegoqego/3/edit?html,js,output

Ember Inspector doesn't even load up. Probably because of the exception that was raised. I would actually think this is expected behavior.

The error is not the same as in my project but it does cause a `match of null` exception.

```
    var nothing = null;
    var matches = nothing.match(/something/gi);
```

Again not sure if this helpful though.

**Comment by eccegordo** [comment]
Ha success! I carefully audited my code for cases where I might accidentally do a `match` and or `split` on `null` or `undefined`. Cleaning up this code solved my ember inspector issues.

@sarus You might want to carefully comb through your code for cases where exceptions could be raised. This code pattern is your friend.

```
if (Ember.isBlank(myVariable)){ 
	// do something if myVariable is null or undefined
	// perhaps return early if necessary
}
```

Also when dealing with arrays isEmpty macro is helpful.
```
if (Ember.isEmpty(myList)){ 
	// do something if array myList is empty, null or undefined
	// perhaps return early if necessary
}
```

@teddyzeenny A couple thoughts/questions come from this

1.) Should the inspector continue to try to work if there is an exception thrown in the host app? Probably not. But wondering if it makes sense to have a special mode where the inspector deliberately swallows exceptions (if that is even possible or advisable)

2.) I think quirky errors in the host app can obviously cause problems. Does it make sense to have a code path where you gracefully handle null or undefined `stackString` in that `fromStackProperty(stackString) {` method? Maybe overkill. Not that familiar with the internal plumbing of the inspector.

How do we deal with crashing apps?

**Comment by teddyzeenny** [comment]
@eccegordo it's not clear to me how an error in your code can result in an undefined `stackString` passed to `fromStackProperty`. I think that such an error should be better handled by the inspector. Do you have clear instructions on how I could reproduce that exact same error?

**Comment by eccegordo** [comment]
@teddyzeenny All I really know at this point is that I had several places in my project code that were trying to perform a regex match on a null or undefined value. In some scenarios these were with computed properties that got triggered by some data binding. When I would load up ember inspector it must have loaded some routes and caused the bindings to fire and initiate a corner case where I would try to `.match` on a variable or value that was null or undefined.

I went through my code and put guards in place to avoid these corner cases. Basically made sure I would never attempt to match on a null value, and in some cases return early in a function if that was unavoidable. 

This fixed my ember inspector woes in that I was no longer raising those specific exceptions.

I have some ideas on how I might be able to reproduce in a small ember cli project. Will keep you posted.

In the mean time can you illuminate a couple things about about how inspector works at a high level? Under what scenarios does it actually cause code paths to be executed in my app? Presumably it has to traverse a bunch of routes and so various hooks with be fired or activated. If I have a lot of data binding behavior happening, it seems like I can run into problems if I am not properly handling null values where the code will blow up if it encounters null.

Thus an exception in my code triggers a chain reaction that causes an exception in ember inspector.

At least that is my current theory.

**Comment by teddyzeenny** [comment]
Some inspector side effects I can think of: instantiating (not visiting) route objects when you open the "Routes" pane, eagerly calculating CPs and observing properties when you inspect a specific object.  

However, `fromStackProperty` is an internal inspector function called when a deprecation message is detected. This function should not in any way receive an `undefined` value since the value it receives is also created internally by the inspector, and the function is called by the inspector. The error you posted happened inside `fromStackProperty` which most definitely is an inspector bug. I don't think it's related to any guards in your app.

**Comment by rwjblue** [comment]
Unless adding the guards prevented a deprecation that was causing the error within the inspector...

**Comment by sarus** [comment]
@eccegordo Thanks for the tips.  I'll take a look and see if there are any places where a match or split is being done on a null value but I feel like that would cause an error with or without the inspector running and right now the error is only thrown when the inspector is enabled.

**Comment by teddyzeenny** [comment]
@eccegordo are you still encountering this issue?

**Comment by eccegordo** [comment]
@teddyzeenny I haven't encountered this issue since I fixed corner cases in my code that guarded against null values and data binding. You can probably close this issue. Not sure if there is anything specific to reproduce or fix at the present time.

**Comment by teddyzeenny** [comment]
Will reopen if it turns out the bug is still there.
