### ISSUE TITLE
Error message: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by denisbetsi** [emberjs/ember-inspector#402]
```
return e.replace(O,"$1_$2").toLowerCase()
```

results in

```
Stack trace: TypeError: Cannot read property 'replace' of undefined
    at Object.func (http://localhost:3000/scripts/lib/ember.js:9:643)
    at Object.r.get (http://localhost:3000/scripts/lib/ember.js:3:26675)
    at o (http://localhost:3000/scripts/lib/ember.js:8:31892)
    at Object.func (http://localhost:3000/scripts/lib/ember.js:9:131)
    at Object.r.get (http://localhost:3000/scripts/lib/ember.js:3:26675)
    at Object.u [as dasherize] (http://localhost:3000/scripts/lib/ember.js:8:31922)
    at ember$data$lib$system$normalize$model$name$$normalizeModelName (http://builds.emberjs.com/beta/ember-data.js:3459:27)
    at ember$data$lib$system$store$$Service.extend.modelFactoryFor (http://builds.emberjs.com/beta/ember-data.js:10947:29)
    at ember$data$lib$system$store$$Service.extend.modelFor (http://builds.emberjs.com/beta/ember-data.js:10913:28)
    at ember$data$lib$system$store$$Service.extend.all (http://builds.emberjs.com/beta/ember-data.js:10509:30)
```

**Comment by eccegordo** [comment]
@denisbetsi Where is that `e` variable coming from? Is this from your code?

Can you try something like this before your return statement:

```
if (Ember.isBlank(e)){ 
    // when e is null or undefined 
   debugger;
} 
```

Then when the debugger comes up try to reason about why `e` is not defined in that particular scenario. Might be a corner case where is not defined yet. In which case you would not be able to perform the replace.

**Comment by denisbetsi** [comment]
This is happening inside ember library internally, nothing I am passing to the function directly, it happens indirectly. You can see the stack trace above.

**Comment by teddyzeenny** [comment]
@denisbetsi which action on the Ember Inspector triggered this error?

**Comment by teddyzeenny** [comment]
@denisbetsi can you also please provide a screenshot of the "Info" pane in the Ember Inspector? Having the versions of everything will make it easier to reproduce the error.

**Comment by denisbetsi** [comment]
@teddyzeenny just going to Ember inspector tab triggers it,the one section in Ember inspector that doesn't work when that error is on is Data the others pull up fine. So I suspect issue with ember-data.

Also this is using current beta release of ember-data if I revert back to older versions, this error disappears.

**Comment by teddyzeenny** [comment]
@denisbetsi which Ember version are you on?

**Comment by denisbetsi** [comment]
@teddyzeenny 
Ember 1.8.1

**Comment by teddyzeenny** [comment]
ember-cli?

**Comment by denisbetsi** [comment]
@teddyzeenny no

**Comment by denisbetsi** [comment]
I reverted back to older Ember-data , let me see if I can quickly put the newer ember-data back get screenshot

**Comment by teddyzeenny** [comment]
You should be seeing this assertion with ember-data >= beta.19: https://github.com/emberjs/data/blob/0a4aba5642355ad82e3a2be81b5f646f7fa003eb/packages/ember-data/lib/system/debug/debug-adapter.js#L57

**Comment by denisbetsi** [comment]
@teddyzeenny  No assertion messages just this
```
Deprecations were detected, see the Ember Inspector deprecations tab for more details.
```

![screen shot 2015-06-20 at 4 11 11 pm](https://cloud.githubusercontent.com/assets/598112/8269067/386bed5e-1767-11e5-87d3-2dcdf3f90c8b.png)

This is with the new ember data that's causing Ember Inspector error. Also just a minor correction, that error appears after I attempt to click on Data tab in Inspector.

**Comment by teddyzeenny** [comment]
Is it possible you are running a production build of Ember?

**Comment by denisbetsi** [comment]
Anything is possible. How can I check?

**Comment by teddyzeenny** [comment]
Not sure if there's a better way, but you can run `Ember.assert === Ember.K` in the console. If the result is true, you're probably running the production build.

**Comment by denisbetsi** [comment]
> Ember.assert === Ember.K
< true

**Comment by teddyzeenny** [comment]
Looks like you're using the production build. Are you using this file in development or are you trying to inspect a production app? You should use the [debug build](http://builds.emberjs.com/tags/v1.8.1/ember.js) during development for helpful error messages, and the [production build](http://builds.emberjs.com/tags/v1.8.1/ember.min.js) during production for better performance. 

Can you try using the Data tab with the debug build? You should get an assertion telling you to upgrade to Ember >= 1.13 to use the inspector with this version of ember-data.

**Comment by denisbetsi** [comment]
Let me give it a shot.

**Comment by denisbetsi** [comment]
Moved to Ember version 1.13 debug. Data tab works and there's no model name errors. It just works like as if nothing happened.

**Comment by teddyzeenny** [comment]
Great :) You should also be getting better error messages in general since you're now on the debug build.

**Comment by Yorer** [comment]
If you don't want to downgrade your project I you can insert an is starement in the node_modules to the file: node_modules/electron-forge/dist/util/forge-config.js, that if the something is undefined then skip it. It did the job perfectly fine and ember electron installed correctly after that.
