### ISSUE TITLE
Ember Inspector and Safari (OS X and iOS)

### ISSUE THREAD

**Issue by eccegordo** [emberjs/ember-inspector#404]
Has implementing this inspector for Safari been considered? Was it too much hassle or painful given Safari's extension architecture?

I still think Safari is an awesome browser and it looks like upcoming debugger tools in Safari are going to get a whole lot better, with some really cool new features. In particular their type profiling tool in their web inspector.

https://developer.apple.com/videos/wwdc/2015/?id=505

I would be interested in trying to take a stab at an implementation if only to learn ember inspector's internals better and make something viable for my favorite browser.

Anyway, just wondering if there is any advice I should heed before attempting this fool's errand?

Totally acceptable if the main answer is that the maintainers just don't have bandwidth to support another implementation. Just wanted know if there are any known technical hurdles I should be aware of?

Thanks.

**Comment by rwjblue** [comment]
The inspector works in safari already via bookmarklet (also works with IE this way). I'm not sure how much work a native extension would be though...

**Comment by teddyzeenny** [comment]
We are happy to support Safari but AFAIK it's not possible to extend their devtools (unless something has changed since I last checked). As @rwjblue mentioned there's the [bookmarklet option](http://guides.emberjs.com/v1.12.0/ember-inspector/installation/#toc_bookmarklet) which already works with Safari. The bookmarklet though is not as powerful as the devtools version, so if there's a better way I'm all for it.

**Comment by eccegordo** [comment]
I tried the bookmarklet but didn't seem to work. But maybe I did something wrong.

@teddyzeenny that was what I was wondering. So not extensible enough. Presumably you could build the inspector as a standalone extension but would require a lot of extra tooling to work.

I will have to do some more research. Thanks for the feedback. 

My main mission is to better understand the internals.

**Comment by rwjblue** [comment]
This will likely sound silly, but I once thought the bookmarklet was broken with Sadari and it turned out I forgot to allow popups. Might be unrelated, but is worth checking...

**Comment by eccegordo** [comment]
@rwjblue Whaddya know, that was it. That little check box buried deep down there I forget about it.

I can see the inspector now. But I think there a little flakiness. For example it opens up in a new tab, seems pretty easy to lose the inspector window.

**Comment by teddyzeenny** [comment]
@eccegordo did you find another way (better than the bookmarklet)?

**Comment by eccegordo** [comment]
Haven't found any way yet to extend devtools in safari. Feel free to close this issue. If I find anything useful I will report back.

**Comment by eccegordo** [comment]
Actually taking the chrome dev tools out of the browser and making work with any browser seems like a good idea.

https://kenneth.io/blog/2014/12/28/taking-chrome-devtools-outside-the-browser/

Makes me wonder how viable it is to build stand alone ember inspector app? Could be handy with mobile debugging.

**Comment by teddyzeenny** [comment]
The inspector is already an Ember app that you can launch standalone. Check out the [remote inspector](https://github.com/joostdevries/ember-cli-remote-inspector) for mobile debugging.
