### ISSUE TITLE
View Tree and ember 1.13.2

### ISSUE THREAD

**Issue by masciugo** [emberjs/ember-inspector#415]
After upgrading to ember 1.13.2 link-to a nested route takes me to a page where the ember inspector view tree loses the parent layer. With the following [jsbin](http://emberjs.jsbin.com/fofubo/edit?html,js,output) I expected this:

![screen shot 2015-06-29 at 13 03 40](https://cloud.githubusercontent.com/assets/454321/8406721/592e78fa-1e5f-11e5-871a-7f22a09bc8ad.png)

but I got the following:

![screen shot 2015-06-29 at 13 03 51](https://cloud.githubusercontent.com/assets/454321/8406725/64d43a32-1e5f-11e5-8fb6-e659222a2603.png)

I need to reload the route to see all layers. It does not happen with ember 1.12.0

**Comment by rwjblue** [comment]
Thank you for the detailed error report!

**Comment by drapergeek** [comment]
I'm seeing this same issue but even after a reload the views do not show up.

My routes tab is also not working.

![screensteps 2015-06-29 11-06-42](https://cloud.githubusercontent.com/assets/89965/8410882/efbf4120-1e4e-11e5-80ae-1e964556e6da.png)

I can confirm that this is an issue on 13.2 but not 12.0

Let me know if I can provide any other information.

**Comment by masciugo** [comment]
@drapergeek have a look to #396

**Comment by nragaz** [comment]
#396 did not fix the view tree issue

**Comment by flyswatter** [comment]
Just hit this as well, seems to still be an issue between ember-inspector and ember `v1.13.2`.

**Comment by masciugo** [comment]
it seems ok with ember 1.13.3 [jsbin](http://emberjs.jsbin.com/fofubo/edit?html,js,console)

**Comment by flyswatter** [comment]
For others looking to solve, updating to `1.13.3` didn't fix this by itself, I also had to update to the latest `ember-cli-htmlbars`.

**Comment by Bargs** [comment]
I'm having the same issue that @drapergeek mentioned, where only the application_loading route shows up in the routes tab. I also tried updating to the latest ember-cli-htmlbars as @flyswatter noted but that didn't fix this issue.

Ember Inspector: 1.8.2
Ember: 1.13.3
ember-cli-htmlbars: 0.7.9
