### ISSUE TITLE
Tomster logo disappears when page contains an iframe

### ISSUE THREAD

**Issue by gdub22** [emberjs/ember-inspector#418]
The tomster logo that shows in the address bar is only showing for a split second, then disappearing on some ember apps.

I've tracked this down to whenever an iframe (with a valid src) is on the page or in a template.

See this comment for possible reason: https://github.com/emberjs/ember-inspector/pull/107#issuecomment-35740072

cc @mixonic

**Comment by gdub22** [comment]
http://output.jsbin.com/hinoriq

**Comment by teddyzeenny** [comment]
Thank you for reporting this.
