### ISSUE TITLE
Not loading sometimes with Firebase 

### ISSUE THREAD

**Issue by vikram-s-narayan** [emberjs/ember-inspector#421]
I get the "Ember application not detected!" message when an Ember app that is connected to Firebase is opened. 

Message goes away and everything runs as normal when you do a 'Hard Reload'.

**Comment by teddyzeenny** [comment]
Can you provide a jsbin, public repo, or any way to reproduce the issue?

**Comment by vikram-s-narayan** [comment]
@teddyzeenny - I'm unable to reproduce this issue today and Ember inspector appears to load fine. Not sure what was going wrong.
