### ISSUE TITLE
Deprecation Overload And UI Thread Locking

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember-inspector#422]
When there are significant deprecation warnings the inspector gets overloaded to the point it appears to lock the UI thread and in some cases crash Chrome.  In other cases deprecations are not properly reported due to the overload.

**Steps to reproduce**
1. Upgrade to Ember 1.13.3
2. Use an Ember Data version south of 1.13.0
3. Experience the :lock: 

 /cc @wycats

**Comment by stefanpenner** [comment]
i suspect this is due to overwhelming the message channel

**Comment by teddyzeenny** [comment]
Are you sure it is correlated with the number of deprecations, or is it the js file size? There's a good chance it's the source map parsing (`JSON.parse`) since it's likely the most expensive operation.

**Comment by teddyzeenny** [comment]
This seems interesting http://azimi.me/2015/07/30/non-blocking-async-json-parse.html

**Comment by acorncom** [comment]
Closing due to the issue growing stale. If this is still an issue, please comment and we can re-open
