### ISSUE TITLE
Cannot open console

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember-inspector#423]
I cannot open the console by hitting `esc`. The window just opens and then closes. Please see video

http://gfycat.com/ImpeccableUnimportantBrahmanbull

/cc @wycats

**Comment by Frozenfire92** [comment]
This happens to me a lot aswell. I always go to another tab and open it first

**Comment by teddyzeenny** [comment]
It's happening on the other custom Chrome devtools as well (tried React, Backbone, Rails). Looks like it may be a Chrome bug.

**Comment by locks** [comment]
I remember tracking this down and confirming it was a Chrome bug, I just don't remember the actual reason why.
