### ISSUE TITLE
Clicking >$E should take you to the Console

### ISSUE THREAD

**Issue by Panman8201** [emberjs/ember-inspector#427]
It would be great if after clicking any `>$E` the Dev Tools would switch to the Console. Not sure that's even possible but just a feature request.

**Comment by vmalloc** [comment]
If it is possible, then definitely +1. This is driving me nuts...

**Comment by teddyzeenny** [comment]
Yes I would love to have this feature. Unfortunately I don't think it's possible with the current Chrome API. Will not hesitate to reopen and implement if there is any way this could be done.

One thing you can do in the meantime is press ESCAPE after clicking on $E - it should open the console just below the inspector. (There's currently a Chrome bug where the console might flicker though).
