### ISSUE TITLE
Can't fetch Ember deprecations

### ISSUE THREAD

**Issue by berfarah** [emberjs/ember-inspector#429]
Hi! I'm not sure what's going on here, but every time I try to open up Ember Inspector's deprecation page, I get the following:

```
GET http://localhost:4200/assets/data:application/json;charset:utf-8;base64,eyJ…VyIG9yIFJoaW5vLlxuICAgIHJvb3QuXyA9IF87XG4gIH1cbn0uY2FsbCh0aGlzKSk7XG4iXX0= net::ERR_EMPTY_RESPONSE
(anonymous function) @ VM56850:1463
initializePromise @ ember.debug.js:54872
Promise @ ember.debug.js:56389
retrieveFile @ VM56850:1457
tryCatch @ ember.debug.js:54825
invokeCallback @ ember.debug.js:54840
publish @ ember.debug.js:54808
(anonymous function) @ ember.debug.js:31646
Queue.invoke @ ember.debug.js:901
Queue.flush @ ember.debug.js:965
DeferredActionQueues.flush @ ember.debug.js:765
Backburner.end @ ember.debug.js:158
(anonymous function) @ ember.debug.js:613
```

I don't know why it's trying to find the `data:` "file" under `/assets`.

The same thing keeps happening (for the most part) when I click on the reload button in the deprecations tab. Is this a node module interfering?

I have `ember-cli-emblem`, `ember-cli-stylus` and `ember-browserify` installed.

**Comment by teddyzeenny** [comment]
This looks like a source map issue. The deprecation pane in the inspector tries to fetch the source map to point you to the exact file location of the deprecation. Here's what it does:
- Fetches the js file (via ajax)
- Looks for `//# sourceMappingURL=[url-to-source-map]` at the end of the js file
- Extracts that source map url and tries to fetch the source map itself via ajax.
- Parses the source map
- Maps the deprecation stack trace to the correct file name and line.

If I were to guess what is happening, my first guess would be that the `sourceMappingURL` provided by the js file is a data URI instead of an actual server URL. Which means the source map is sent along with the js file? Is it possible ember-browserify does this? Can you try to verify from your js file?

**Comment by pete-the-pete** [comment]
I am seeing the same issue.  I don't think its an issue with ember-inspector, it is just trying to download the file.  In my vendor.js I see another sourceMappingURL value that work correctly, I just have one odd ball that is a data URI.

I have tried setting 
```
browserify: {
      sourcemaps: {
        enabled: false
      }
},
```

in my environment.js, but it doesn't solve the issue.  Completely turning off source maps gets rid of the error, but doesn't really fix the issue.

When I decode url it is specific package, but its unclear why _that_ package

**Comment by knownasilya** [comment]
Also having this issue with ember-cli 1.13.8 and ember-browserify 1.0.3

**Comment by maartenparmentier** [comment]
I'm also experiencing this problem *without* ember-browserify

**Comment by knownasilya** [comment]
Try 1.0.5

**Comment by maartenparmentier** [comment]
no luck after updating to 1.0.5.

**Comment by marnen** [comment]
Same issue here, FWIW.

**Comment by maartenparmentier** [comment]
For us it worked by deleting browserify. Installed it back after update.

**Comment by marnen** [comment]
@maartenparmentier Did you delete browserify, ember-browserify, or both?

**Comment by maartenparmentier** [comment]
@marnen ember-browserify

**Comment by efx** [comment]
seeing this issue as well. I tried updating ember-browserify to 1.1.1 but did not see an improvement.
My project's config:
```
    "ember-browserify": "^1.0.5",
    "ember-cli": "^1.13.8",
```
@teddyzeenny I was able to verify that the `sourceMappingURL` being passed to `retrieveFile` is a data URI. In my case it was a npm package I am importing to my app via
`import _ from 'npm:lodash'`

**Comment by locks** [comment]
Is this still a problem?

**Comment by efx** [comment]
@locks in trying to recreate, I was unable to inspect any deprecations as when I clicked on the Deprecations tab in Ember Inspector I saw the following issue: 
<img width="1438" alt="screen shot 2016-09-19 at 7 43 16 am" src="https://cloud.githubusercontent.com/assets/472721/18630858/da2e1792-7e3c-11e6-8339-a2f2a9c4618f.png">
Chrome: 52.0.2743
Ember Inspector: 2.0.2
happy to open another issue, try a build from master.

**Comment by rwwagner90** [comment]
Can anyone reproduce this on latest Inspector? I'm not seeing any issues.

**Comment by efx** [comment]
Not seeing the original or the other issue I mentioned using inspector@3.0.0

**Comment by rwwagner90** [comment]
Thanks @efx. I will close. If anyone is still having issues, please let us know!
