### ISSUE TITLE
Use ember-debug-handlers for better deprecation support

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-inspector#430]
[RFC#65](https://github.com/emberjs/rfcs/blob/master/text/0065-deprecation-warning-handlers.md) was implemented behind a feature flag in Ember in https://github.com/emberjs/ember.js/pull/11833, and all deprecations updated to include `id` and `until` (tracked in https://github.com/emberjs/ember.js/issues/11835).

I created a polyfill for usage with prior Ember versions ([rwjblue/ember-debug-handlers-polyfill](https://github.com/rwjblue/ember-debug-handlers-polyfill)) that the inspector can use to make tracking down and managing deprecations much easier.

A couple of ideas:
- hide "non-critical"  (ones that are being removed more than two versions from now) deprecations in the deprecations pane (with some sort of toggle to show all)
- allow focusing on a single deprecation, by calling `Ember.Debug.registerDeprecationHandler` and throwing for the `id` or deprecation message in question

Thoughts?

**Comment by teddyzeenny** [comment]
:+1: Will work on it for version 1.9.

**Comment by rwwagner90** [comment]
@rwjblue @teddyzeenny do we still want to do anything here or can we close this?

**Comment by rwwagner90** [comment]
I think with collapsible deprecations, and the ability to flush deprecations now, we can close this.
