### ISSUE TITLE
Object inspect pane collapse button hidden in some tabs

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember-inspector#434]
Most of the time (especially <1.8) the object inspect pane had a collapse button (![](http://i.imgur.com/MN6ojwN.png)) just to the top left of it . It seems to be showing up sporadically now (and often not at all) resulting in the pane being stuck open with no way to close it.

Expected:
![](http://i.imgur.com/THdDuGm.png)

Actual:
![](http://i.imgur.com/98EJTgI.png)

I suspect it's probably just a styling issue (the button is obscured) as the button will appear/disappear depending on which Ember Inspector tab you're on. A quick check:
 * View Tree (not visible)
 * Routes (not visible)
 * Data (visible)
 * Deprecations (not visible)
 * Info (not visible)
 * Promises (not visible)
 * Container (visible)
 * Render Performance (visible)

Using Ember Inspector 1.8.3 in Chrome 44.0.2403.107 (64-bit), though have seen it in other Chrome installations at different versions.

**Comment by benmurden** [comment]
I am experiencing the same on Ember Inspector 1.8.3 and Chrome 44.0.2403.125. To close panel at the moment, I would need to go to the Data or Container tabs before being able to see the button, then would click it from there.

**Comment by teddyzeenny** [comment]
Yes it's probably a styling issue. Will look into it.
