### ISSUE TITLE
this._resetSubControllers is not a function

### ISSUE THREAD

**Issue by vvs-code** [emberjs/ember-inspector#449]
I've got this error  on transition from one route to another. But it's happens only if I refresh page with active tab with Ember-debugger. After that - every time after page reload I've got this error on the same transition. To fix - I should close Developer tools, refresh page and then open DevTools again

Stack is 
```
__exports__.default.ArrayProxy.extend.willDestroy	@	ember.js:29004
apply	@	ember.js:19663
superWrapper	@	ember.js:19235
willDestroy	@	VM26681:2298
Queue.invoke	@	ember.js:848
Queue.flush	@	ember.js:913
DeferredActionQueues.flush	@	ember.js:718
Backburner.end	@	ember.js:143
Backburner.run	@	ember.js:198
run	@	ember.js:17905
(anonymous function)	@	socket-adapter.js:163
EventEmitter.emit	@	socket.io.js:623
SocketNamespace.onPacket	@	socket.io.js:2190
Socket.onPacket	@	socket.io.js:1882
Transport.onPacket	@	socket.io.js:1311
Transport.onData	@	socket.io.js:1282
WS.open.websocket.onmessage	@	socket.io.js:2329
```

at  >> **willDestroy	@	VM26681:2298 is** 
```return _oldWillDestroy.apply(_this2, _arguments);```
from code
```

    retainObject: function retainObject(object) {
      var _this2 = this,
          _arguments = arguments;

      var meta = emberMeta(object);
      var guid = guidFor(object);

      meta._debugReferences = meta._debugReferences || 0;
      meta._debugReferences++;

      this.sentObjects[guid] = object;

      if (meta._debugReferences === 1 && object.reopen) {
        (function () {
          // drop object on destruction
          var _oldWillDestroy = object._oldWillDestroy = object.willDestroy;
          object.reopen({
            willDestroy: function willDestroy() {
              _this2.dropObject(guid);
              return _oldWillDestroy.apply(_this2, _arguments);
            }
          });
        })();
      }

      return guid;
    },
```

**_oldWillDestroy** is Ember.K ( `function K() { return this; }` )

**_this2** is 
```
Class {
namespace: Class, 
sentObjects: Object, 
boundObservers: Object, 
__ember1439224455762: null, 
__ember_meta__: Object
}
"<(unknown mixin):ember3886>"
```

I'm not sure that this bug is critical but it is confused

**Comment by teddyzeenny** [comment]
Thanks for reporting this. Definitely a regression.

**Comment by vvscode** [comment]
Please describe what do I need to do to fix this one for me?

**Comment by shahroon** [comment]
@teddyzeenny  how to fix this?

**Comment by teddyzeenny** [comment]
This has been fixed but I haven't been able to release on Chrome yet due to a bug in the Chrome Web Store.

In the meantime you can:
- use [Firefox](http://guides.emberjs.com/v2.0.0/ember-inspector/installation/#toc_firefox)
- use the [bookmarklet](http://guides.emberjs.com/v2.0.0/ember-inspector/installation/#toc_bookmarklet)
- build [from source](https://github.com/emberjs/ember-inspector/blob/7f41898a1b4e01c08b2507d6e3877d9423f3884a/README.md#chrome)
- wait until the Chrome Web Store is fixed and it's released on Chrome

**Comment by shahroon** [comment]
Yea, already started to use FF. 

Thanks

**Comment by teddyzeenny** [comment]
FYI the new version has been released on Chrome too.

**Comment by shahroon** [comment]
Perfect. (Y)
