### ISSUE TITLE
Unable to horizontally scroll the inspector, and not wide enough to view all data

### ISSUE THREAD

**Issue by stevehanson** [emberjs/ember-inspector#451]
I feel like the Ember Inspector used to be able to scroll horizontally, but lately, I haven't been able to do so in any of the tabs. A lot of data is displayed in the inspector, and not much is visible without the ability to scroll. The data is not wrapping; it's just cut off.

Ember Inspector 1.9.0.
Chrome Version 44.0.2403.130 (64-bit)
Mac OS 10.10.4

In the screenshot below, you can see that the full deprecation messages can't be seen :point_down: 

![image](https://cloud.githubusercontent.com/assets/1691324/9241391/8daaad00-4138-11e5-8a1d-46d692619ac0.png)

**Comment by teddyzeenny** [comment]
Thanks for reporting this. Looks like a CSS bug.

**Comment by anujku** [comment]
+1

**Comment by cafreeman** [comment]
Any new developments on this? Just started using Ember Inspector and ran into this issue fairly quickly. Can't scroll horizontally on any of the panes :(

**Comment by ericestes** [comment]
+1

**Comment by Sweet-Bob** [comment]
+1 can't debug my routes

**Comment by adjohu** [comment]
+1

**Comment by adjohu** [comment]
Also unable to resize columns more than about 20px which would otherwise help to mitigate this issue.

**Comment by acorncom** [comment]
Does anyone on this issue have time to help fix this issue? The Ember Inspector team could use a hand, as it’s a bit complicated in there ... 😉

**Comment by thorsteinsson** [comment]
This has been fixed in PR #873, we're still testing it on different apps before merging.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by stevehanson** [comment]
I haven’t used Ember Inspector in years to be able to say either way. I have no objections to closing this.

**Comment by rwwagner90** [comment]
@sandstrom I believe it was fixed for all the tables where we used ember-table, but we didn't drop it in everywhere. I think the biggest offenders were fixed though, so we can close this for now.
