### ISSUE TITLE
link promise labels to Ember.error exception messages 

### ISSUE THREAD

**Issue by Leooo** [emberjs/ember-inspector#452]
See https://github.com/emberjs/ember.js/issues/11863#issuecomment-123898242

Basically, in Ember when an exception is thrown inside a Promise we often have no clue what is the real problem underlying the issue (i.e. which operation, which model, which id).

The "Promises" tab in Ember Inspector actually could help a lot: exceptions happening inside a Promise lead to a fulfillment / rejection value corresponding to the error message, and from the label of the Promise we will often be able to get back to the data needed on the operation / model causing the issue.

Possible improvements would be:

1) Be able to search by fulfillment value in Ember Inspector: that way we could just copy / paste the error message instead of checking all the rejected promises

2) Better, probably bit less trivial, would be to fetch the promise labels and add them as a Field to the Ember.Error object so that we are able to debug more easily the exceptions.

Seems like a huge improvement for Ember developers compared to the cost of / time spent on implementation.

As a side note, the current situation is actually not too bad as we are able to get information on errors from the Ember Inspector promise tabs. But it took me months to discover that, so probably worth updating the docs for Ember-debug.

Thanks.

**Comment by teddyzeenny** [comment]
1. Thanks, good idea, will do that.
2. If I understand correctly you are suggesting that we send the promise's label along with the error? Maybe RSVP can pass the label as a second argument to the `on('error')` event? Though this is not something we can do in the inspector itself.

**Comment by Leooo** [comment]
2. Yes that's right, adding the promise label as argument for on('error'). Indeed it would not be for Ember Inspector then, I suppose this would be more for the issue https://github.com/emberjs/ember.js/issues/11863

**Comment by rwwagner90** [comment]
@Leooo @teddyzeenny is there still interest in this feature?

**Comment by Leooo** [comment]
@rwwagner90 not sure on my side I have no problems to debug anymore recently - you can close for me.

**Comment by rwwagner90** [comment]
Thanks @Leooo, closing due to lack of interest for now.
