### ISSUE TITLE
Collapse deprecations by default

### ISSUE THREAD

**Issue by Panman8201** [emberjs/ember-inspector#454]
It's kind of annoying that deprecations are expanded when opening the tab. Makes it tough to just zip through the list to get a sense of them all, and there is already a badge for the number of instances of a particular deprecation. 

Along with that, there is a weird viewing issue where if the instances list is longer than the window, it (somewhat) hides the list, making it look like you are at the end of the deprecation list. Probably worthy of a separate issue...

**Comment by teddyzeenny** [comment]
Would a "collapse all" button solve this problem?

**Comment by Panman8201** [comment]
I would say that would be a minimal solution, allows the ability to quickly collapse them all. But I was hoping for them to be collapsed by default. Collapse all / expand all buttons would be useful though.

Been a while since I had to deal with a large number of depreciations. Darn that 1.13 version... 😉

**Comment by locks** [comment]
@Panman8201 are you able to PR something?

**Comment by Panman8201** [comment]
Not at the moment, mid (major) project. I'll add it to my open source TODO list. Lot's of stuff, so little time. 😦

**Comment by locks** [comment]
@Panman8201 and now? 👼

**Comment by Panman8201** [comment]
@locks I think I could get a PR started for this, looks fairly straight. What is the best approach to communicate to all the child `{{deprecation-item}}` component instances? Kind of like actions-down.

**Comment by Panman8201** [comment]
Dropping this here as an idea, not sure if it's the right approach though.

https://ember-twiddle.com/41da78414b88e3c514f7fc3a76f0a9ad?openFiles=components.deprecation-item.js%2Ctemplates.components.deprecation-item.hbs
