### ISSUE TITLE
Check for `file:` protocol support

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember-inspector#46]
When installing via the store, file support has to be turned on manually by the user. I believe we can check if it's supported via `chrome.extension.isAllowedFileSchemeAccess` (see http://developer.chrome.com/extensions/extension.html). We should show instructions for how to turn it on instead of showing "App not detected."

![Screen shot](https://www.monosnap.com/image/2CP5ktJ2AFcHIalAXaBzeCa4s.png)

**Comment by teddyzeenny** [comment]
We added a helpful message and clear steps for enabling file support in https://github.com/emberjs/ember-inspector/pull/52.
