### ISSUE TITLE
A deprecation warning prevent app's reloading

### ISSUE THREAD

**Issue by nightire** [emberjs/ember-inspector#461]
![2015-09-01 5 01 16](https://cloud.githubusercontent.com/assets/1104018/9600049/3f9258a0-50cb-11e5-9105-f0c77dec51a6.png)

As above shows, when using with canary version, this deprecation warning will show after ember inspector activated, but this will also prevent the whole application's reload process (ember cli's livereload or manually refresh in browser), just leave a blank page.

If you close the developer tool or never active the ember inspector, then everything is fine.

use ember inspector 1.9.1 in this demo.

**Comment by teddyzeenny** [comment]
Thanks for the report. Looks like current Ember canary is not compatible with the inspector. I will look into it.

**Comment by James1x0** [comment]
+1

**Comment by lolmaus** [comment]
THANK YOU! O_O
