### ISSUE TITLE
Getting error in console when using Ember Inspector: Uncaught TypeError: Cannot set property 'emberExtension' of undefined

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember-inspector#463]
Stacktrace:

Uncaught TypeError: Cannot set property 'emberExtension' of undefined
(anonymous function) @ content-script.js:29
(anonymous function) @ content-script.js:64

The line 29 is as follows:
document.documentElement.dataset.emberExtension = 1;

While pausing at the error using Chrome debugger,
document.documentElement is 
&lt;svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" x="0px" y="0px" width="139.978px" height="10.32px" viewBox="0 0 139.978 10.32" enable-background="accumulate" xml:space="preserve"&gt;...&lt;/svg&gt;

and document.documentElement.dataset is undefined

**Comment by teddyzeenny** [comment]
Can you help me reproduce the case where `documentElement.dataset` is `undefined`?

**Comment by Gaurav0** [comment]
I am getting this error in Chrome 45 with Ember Inspector 1.9.1 with &lt;svg xmlns&gt;  elements on the page.

**Comment by devgru** [comment]
Seems like SVG elements have no dataset since Chrome 45 (tried on both Mac OS and Windows).
