### ISSUE TITLE
[IDEA] Component Hierarchy Tab

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember-inspector#465]
Not sure if this has been discussed, but I think it would be very useful for the inspector to have a tab for component structure similar to how the [react-dev-tools](https://github.com/facebook/react-devtools) work. Basically if we could reflect the components and how their `attrs` and local state changes it would be really cool.

**Comment by rvfischione** [comment]
I thought this was accessible through the "view tree" tab? I usually check the "components" box, then click on the component name, and all of the attributes show up on the right.

**Comment by rwwagner90** [comment]
I believe this is complete, with the recent addition of the component tree tab. It will be released soon.
