### ISSUE TITLE
object is not extensible

### ISSUE THREAD

**Issue by ef4** [emberjs/ember-inspector#468]
ember-inspector calls `guidFor` on streams. `guidFor` is implemented by sticking a `meta` on the object.

But on current canary in development mode, streams are sealed objects. This results in exceptions like `Uncaught TypeError: Cannot define property:__ember1442443003034, object is not extensible.`

**Comment by rwjblue** [comment]
We should ensure that they are setup with a meta in the constructor of BasicStream in metal/streams/stream

**Comment by ef4** [comment]
Yeah, though we can avoid allocating all those unused meta objects and just do `this.__ember_meta__ = null` to create the slot.

**Comment by rwjblue** [comment]
Will be addressed by https://github.com/emberjs/ember.js/pull/12411 upstream.
