### ISSUE TITLE
2.1.0 doesn't run if Inspector is on

### ISSUE THREAD

**Issue by benjaminbalazs** [emberjs/ember-inspector#478]
Getting a deprecation message and my app stays blank.

The `initialize` method for Application initializer 'ember-inspector-booted' should take only one argument...

I tried to uninstall and install Ember Inspector, but didn't help.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-inspector/pull/476 fixed the deprecation, we are going to shoot for a new release soon (hopefully a day or two).

> Getting a deprecation message and my app stays blank.

Deprecations do not generally prevent apps from booting. Perhaps you have `Ember.ENV.RAISE_ON_DEPRECATION` set?  If not, can you share a reproduction?

**Comment by benjaminbalazs** [comment]
Made a 20 sec screencast.
https://www.dropbox.com/s/r9pkami32jyhjrm/Google%20Chrome.mov?dl=0

It happens even if I add
Ember.RAISE_ON_DEPRECATION = false;
Ember.LOG_STACKTRACE_ON_DEPRECATION = false;
to app.js

**Comment by FilmKnurd** [comment]
This happens for me as well. However, If I load the app while the Chrome Dev Tools are **closed**, then open the dev tools, refreshing works.

**Comment by FilmKnurd** [comment]
This is probably the same problem in #461

**Comment by rwjblue** [comment]
Yep, seems like the same thing reported there.  

Also the same issue as https://github.com/emberjs/ember.js/issues/12439.
