### ISSUE TITLE
Data Does Not Populate When "serialize" Is False

### ISSUE THREAD

**Issue by IsaiahJTurner** [emberjs/ember-inspector#479]
I use the `serialize` property to prevent certain properties from being sent to the server. Ember Inspector seems to show the data as `undefined` when `serialize` is `false`.
import DS from 'ember-data';
For example: 

``` js
export default DS.JSONAPISerializer.extend({
  attrs: {
    createdAt: {
      serialize: false
    }
  }
});
```

I can use `createdAt` in my code and the property is there but within Ember Inspector I see 
<img width="181" alt="screen shot 2015-10-05 at 4 55 34 pm" src="https://cloud.githubusercontent.com/assets/3732588/10293328/e5255238-6b81-11e5-86a9-f0acf020455a.png">
The exception to this is if `defaultValue` is set on the model's attribute, Ember Inspector will display that default value.

**Comment by rwwagner90** [comment]
This is the expected behavior, as we just show what is in the store.
