### ISSUE TITLE
Inspector still occasionally showing Globals

### ISSUE THREAD

**Issue by trek** [emberjs/ember-inspector#488]
```
DEBUG: -------------------------------
ember.debug.js:5442 DEBUG: Ember      : 1.13.8
ember.debug.js:5442 DEBUG: Ember Data : 1.13.8
ember.debug.js:5442 DEBUG: jQuery     : 1.11.3
ember.debug.js:5442 DEBUG: -------------------------------
VM311:87 Ember Inspector Active
```

```
ember -v 
version: 1.13.5
node: 0.12.5
npm: 2.13.2
os: darwin x64
```

Inspector is 1.9.3

![popular pays swap dashboard 2015-10-22 11-23-13](https://cloud.githubusercontent.com/assets/9736/10671324/a9cbb2d2-78af-11e5-8a23-43794c864054.png)

**Comment by teddyzeenny** [comment]
My first thought would be it's not detecting the ember-cli config. Have you disabled the config meta tag by any chance (`storeConfigInMeta: false`)?

**Comment by trek** [comment]
Ah, yes we have. The index is generated by a Rails application (some of the chrome comes from Rails, so we have to embed until we've fully extracted the app).

**Comment by acorncom** [comment]
@trek Looks like we can probably close this issue then?
