### ISSUE TITLE
it seems serializers are missing from the container page

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember-inspector#489]
:arrow_up: as in title:
it seems serializers are missing from the container page, but they do seems to exist in the container when i pull them manually

```
Ember      : 2.0.1
Ember Data : 2.0.1
jQuery     : 1.11.3
```

**Comment by teddyzeenny** [comment]
Serializers and adapters are [not singletons](https://github.com/emberjs/data/blob/04a17413428b738880c35de5725cea0e330b6e3b/packages/ember-data/lib/initializers/store.js#L26-L27) so they're not cached. When you lookup them up through the container you actually create a new instance each time.

**Comment by oriSomething** [comment]
hey, thanks!
