### ISSUE TITLE
[FEATURE REQUEST] Find component by ID in Tree View

### ISSUE THREAD

**Issue by IgorKvasn** [emberjs/ember-inspector#490]
It would be nice to be able to find a component in "View Tree" by its HTML ID (elementId). 

Nowadays, you can inspect a component by clicking on an HTML element and an appropriate component will be selected in the "View Tree" panel. However when you have a nested components this feature is hard to use (e.g. when you want to inspect a top-level component, current inspect feature keeps selecting the most-inner component).

**Comment by rwwagner90** [comment]
This should be fixed with the new component tree stuff. You can easily see the hierarchy there.
