### ISSUE TITLE
Help with detecting errors

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/ember-inspector#492]
Ember-Cli in development mode gives me error to Chrome console: 

```
"Uncaught Error: Assertion Failed: The inline form of the `if` and `unless` helpers expect two or three arguments, e.g. `{{if trialExpired 'Expired' expiryDate}}` or `{{unless isFirstLogin 'Welcome back!'}}`."
```

That is kind of fun error to find when you have hundreds of views and components.

Perhaps ember-inspector could help with thesekind of errors?

**Comment by vvscode** [comment]
@mxrguspxrt  did you find solutions?

**Comment by mxrguspxrt** [comment]
Yes. It was caused bacause error in syntax of template. Found & Fixed. 

The main issue is that if you have 100 components with templates, is does not say in which one the error is. 

Please improve the error message.

**Comment by acorncom** [comment]
@mxrguspxrt Any chance you'd be able to send in a PR to help improve the error message?  Folks on this end are pretty swamped ...

**Comment by locks** [comment]
I believe this should be closed, as what needs improving is Ember's (or whatever piece is responsible for that one) error reporting.
