### ISSUE TITLE
Deprecations detected, but can't view them

### ISSUE THREAD

**Issue by yagni** [emberjs/ember-inspector#493]
Using version 1.9.3 in Chrome or Firefox, when I load my site, the deprecations in the sidebar has a nonzero number next to it, but when I click on it, the main pane says "No deprecations have been detected. Try reloading to catch the deprecations that were logged before you opened the inspector.". This happens even when I already have the Inspector open while loading my page.

**Comment by H3Chief** [comment]
+1

**Comment by nselikoff** [comment]
+1

**Comment by MondeSameWave** [comment]
+1

**Comment by locks** [comment]
Use reactions instead of `+1` comments please, thanks :)

**Comment by rwwagner90** [comment]
Is anyone still having issues with this? If so, what Ember version are you on?

**Comment by rwwagner90** [comment]
@josemarluedke those have been fixed, but we have not released a new version yet.

**Comment by rwwagner90** [comment]
Closing this, since it's likely fixed now. Just need to release a new version.
