### ISSUE TITLE
Release new version to support Ember 2.2.0

### ISSUE THREAD

**Issue by vmalloc** [emberjs/ember-inspector#498]
For anyone not installing from the repository, ember-inspector is now broken on the latest Ember. It would be nice to get a new release to support it.

Thanks!

**Comment by rwjblue** [comment]
Seems like a good idea to me also, @teddyzeenny any objections?

**Comment by teddyzeenny** [comment]
No objections. Was just waiting a bit for the obvious bugs to show up.

**Comment by teddyzeenny** [comment]
https://github.com/emberjs/ember-inspector/releases/tag/v1.9.4

**Comment by vmalloc** [comment]
Awesome! Thanks!
