### ISSUE TITLE
Trace in the console not working

### ISSUE THREAD

**Issue by samselikoff** [emberjs/ember-inspector#501]
I'm on Ember Inspector 1.9.4, and clicking "Trace in the console" doesn't seem to be working.

![demo](https://cloud.githubusercontent.com/assets/2922250/11643586/e6a87852-9d12-11e5-9f9a-494e28a27ed0.gif)

Any ideas on how to debug?

**Comment by teddyzeenny** [comment]
Hey @samselikoff. What's your setup/versions?

**Comment by samselikoff** [comment]
Ember Inspector: 1.9.4
Ember: 1.13.11
Ember Data: 1.13.15
jQuery: 1.11.3
TedEdLessonCreator: 0.0.0+485effb7

Chrome: Version 47.0.2526.73 (64-bit)

**Comment by acorncom** [comment]
@samselikoff Is this still an issue for you?

**Comment by samselikoff** [comment]
Not sure - can close for now, reopen if I see it again. Thank!
