### ISSUE TITLE
Routes tab, hide substates checkbox

### ISSUE THREAD

**Issue by Panman8201** [emberjs/ember-inspector#502]
The "/# Routes" tab can be quite overwhelming with all the different substates shown. I propose adding a checkbox next to the existing "Current Route only" checkbox titled something like "Hide substate routes". When checked, all the "loading" and "error" (maybe even "index") substates would be hidden, leaving just the routes you defined in the Router.

As for the "index" route, could that somehow be dynamically hidden if there is nothing defined? Ex: Route, Controller, Template, View. Or maybe hidden if there are no child/sub routes.

**Comment by teddyzeenny** [comment]
+1 on hiding the substates. I think we should keep the index routes though because even if nothing is defined, you could still be in the index route.

**Comment by Panman8201** [comment]
I see your point, and actually it looks like Ember Inspector doesn't show "index" routes for those without child routes anyway. So nothing would need to be changed there. So yeah, just hide the "loading" and "error" substates.

And just a point of clarification. would the substates include both [dot and underscore versions](https://guides.emberjs.com/v2.2.0/routing/loading-and-error-substates/#toc_code-loading-code-substates)? (Ember Inspector shows both) Ex:

- **foobar_loading**
- **foobar_error**
- foobar
    - **foobar.loading**
    - **foobar.error**

**Comment by teddyzeenny** [comment]
Yes I suppose it should include both.

**Comment by nummi** [comment]
Better late than never? https://github.com/emberjs/ember-inspector/pull/860
