### ISSUE TITLE
Properties with more than one camel letter display weird in data view heading

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember-inspector#503]
I have a model with property isRenameableInPO. In the heading it displays as 'Is renameable_in_po', when it should be 'Is renameable in po'. Screenshot attached:

![image](https://cloud.githubusercontent.com/assets/12710362/11899238/86343c78-a595-11e5-8a72-0b8a967c149b.png)

A single camel case name works fine i.e communicationData displays correctly as 'Communication data'.

**Comment by teddyzeenny** [comment]
Thanks for reporting it :+1:

**Comment by teddyzeenny** [comment]
The solution is in ember-data repo.

[This line](https://github.com/emberjs/data/blob/4b025cedaa25d72b34c5b9c7c6920eeb89f36003/addon/-private/system/debug/debug-adapter.js#L41) should be replaced with:

```js
var desc = capitalize(underscore(name).replace(/_/g, ' '));
```

**Comment by adam-knights** [comment]
Thanks for that @teddyzeenny - so do you mean I need to report this against ember data?

**Comment by stevenpetryk** [comment]
@adam-knights, yes, that would be the appropriate repo. It's not an ember-inspector issue.
