### ISSUE TITLE
TypeError: Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by pogopaule** [emberjs/ember-inspector#506]
I updated my Ember app from 1.13.11 to 2.3.0-beta.3. If I open the Ember inspector (1.9.4) and navigate around, the following error is thrown:

```
TypeError: Cannot read property 'getState' of undefined
    at _nodeIsView (<anonymous>:4196:21)
    at _shouldShowNode (<anonymous>:4164:17)
    at <anonymous>:4123:20
    at Array.forEach (native)
    at _appendNodeChildren (<anonymous>:4122:18)
    at <anonymous>:4128:18
    at Array.forEach (native)
    at _appendNodeChildren (<anonymous>:4122:18)
    at <anonymous>:4126:18
    at Array.forEach (native)
```

Unfortunately I can't isolate the error any further.

**Comment by phcoliveira** [comment]
I am also experiencing the exact same problem. Are you using Liquid Fire for replacing smoothly a component inside `liquid-bind`? To be sure:

``` handlebars
{{#liquid-bind lastPane use="fade" as |pane|}}
  {{component pane}}
{{/liquid-bind}}
```

**Comment by pogopaule** [comment]
@phcoliveira No I don't use `liquid-bind`.

**Comment by mitchlloyd** [comment]
This issue is being addressed in this PR: https://github.com/emberjs/ember-inspector/pull/504

**Comment by eibrahim** [comment]
I am having the same issue.  is there a workaround for this while we wait for the PR to be merged?

**Comment by eibrahim** [comment]
fyi: my coworker ran the app in incognito mode and no console errors showed up so I think it has to do with the ember inspector chrome extension.  I also noticed that these errors didn't effect app functionality and everything in my app seemed to work just fine.
