### ISSUE TITLE
Ember inspector does not respect firefox developer tools theme

### ISSUE THREAD

**Issue by ecksun** [emberjs/ember-inspector#508]
Ember inspector is very difficult to use with the dark theme of the firefox developer tools (which is the default in firefox developer edition).

What I had most issues with was inspecting attributes of a model, since the text is black on a very dark background.

Im using firefox developer edition 45.0a2 (2016-01-12).

Steps to reproduce:
1. Open developer tools
2. Select toolbox options
3. Select Dark theme under "Themes"
4. Open the Ember tab
5. Select "Data" and click on any model
6. Notice that the attribute values are more or less the same color as the background.

![ember-inspector-screenshot](https://cloud.githubusercontent.com/assets/135807/12263873/db360264-b932-11e5-9962-579f3010d63d.png)

**Comment by skiner68** [comment]
+1 on this....

**Comment by graham-sportsmgmt** [comment]
Agreed.  The default theme is practically non-usable for regular use.

**Comment by rwwagner90** [comment]
Dark theme support has been added, and will be released soon.
