### ISSUE TITLE
Feature: Add in localhost:4200 to Access-Control-Allow-Origin header onHeadersRecieved

### ISSUE THREAD

**Issue by devinrhode2** [emberjs/ember-inspector#509]
I'm developing a chrome extension that integrates directly with an ember app. My api server's origin is some development machine on amazon. In my extension background page I force-add `http://localhost:4200` into the `Access-Control-Allow-Origin` header for responses from the dev server with the following code:

``` js
//TEMPORARY, THIS CODE CANNOT GO SLIP INTO PRODUCTION.
//THE EXTENSION SHOULD BE TESTED WITHOUT THIS CODE.
var emberCliServer = 'http://localhost:4200'
chrome.webRequest.onHeadersReceived.addListener((resp) => {
    resp.responseHeaders.forEach((header, index) => {
      if (header.name.toLowerCase() === 'access-control-allow-origin') {
        resp.responseHeaders[index].value = emberCliServer
      }
    })
    resp.responseHeaders[resp.responseHeaders.length] = {
      'name': 'Access-Control-Allow-Origin',
      'value': emberCliServer
    }
    return {responseHeaders:resp.responseHeaders}
  }, //end onHeadersRecievedListener
  {
    urls: ['http://localhost:4200/*', 'http://ur.dev.ser.ver/*', 'http://localhost:3000/*']
  },
  ['blocking','responseHeaders'] //block processing of responseHeaders until they are modified
)
```

Upon consideration of what to do when it comes time to deploy production, I realized Ember Inspector extension should totally do this.

Maybe we want to try and read the dev server IP from config/environment.js, I don't know how this could be done though.

Also I'm sure this code could be improved, but it's been working for years and I don't care to improve it. It's basically a 10 line grease monkey script, decoupled from everything.

**Comment by rwwagner90** [comment]
@devinrhode2 forgive my ignorance, but what does this give us?

**Comment by devinrhode2** [comment]
Should definitely NOT be on by default, so my code would have to be
activated when they turn on some setting to "Force-add
access-control-allow-origin" BUT... it's not necessarily secure for a
backend to add in "localhost" is it? That just doesn't make sense for the
backend to add. So then the frontend dev COULD edit /etc/hosts to map
localhost:4200 to their domain, but I think it's a pretty good idea to add
this in... idk if its necessary anymore though, maybe chrome doesn't
enforce this header for localhost anymore, maybe chrome just allows it to
happen now.. really not sure.. currently the backend I work off of (not in
my control) just doesn't even have this security restriction, just using `
access-control-allow-origin:
*`

Sorry if I'm rambling - I think the key/best point I have in this message
is that it doesn't make sense for a backend to allow localhost, but somehow
these ajax requests need to be allowed, it would make the ember experience
much easier to have a setting to just add this header (most likely devs
would find it through google or maaaaaybe even this GH issue)

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>

**Comment by devinrhode2** [comment]
backend would typically add `access-control-allow-origin: api.twitter.com`

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>

**Comment by rwwagner90** [comment]
I still believe this is up to the developer to implement. If your back end allows `*` why do we need this? For someone with a locked down back end, they would still have to either allow this in the back end, or set up nginx or something to proxy requests.

I'm looking for:

1. A clear benefit to enabling this
2. How this would work for a locked down back end?
3. What are the security implications of something like this? It feels like an attack kind of.

**Comment by devinrhode2** [comment]
Idk man at one point it was extremely helpful for me to add the header at
the extension level.

This is irrelevant for a backend that allows *
Locked down backend might not necessarily refuse requests that don't have
the correct origin, although it probably should.

Maybe the key use case is for a new backend where they haven't totally
figured out how to set everything up, or they are in a situation where they
can't add the header. I don't know if backends actually use this header as
a security restriction, it might just be a security restriction at the
browser level.

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>

**Comment by rwwagner90** [comment]
I don't know enough about the security implications or usefulness of this feature request. @rwjblue @teddyzeenny can you help decipher this and let me know if we want this or not?

**Comment by rwwagner90** [comment]
I think this is outside the scope of things we want to support for now, so going to close.
