### ISSUE TITLE
Add support for electron

### ISSUE THREAD

**Issue by BryanHunt** [emberjs/ember-inspector#511]
Now that [ember-electron](https://github.com/felixrieseberg/ember-electron) makes it trivial to develop native Ember applications, it would be nice to have the inspector available during development.

**Comment by rwjblue** [comment]
Hmm.  I think it should be possible with the remote inspector work that has already been done.  Have you tried that?

**Comment by rwjblue** [comment]
Whoops, I noticed there is no details in the README about the remote inspector work. Take a look at https://github.com/joostdevries/ember-cli-remote-inspector for more details.

If you find that that works, would you mind adding something to the README?

**Comment by felixrieseberg** [comment]
I know I just said two days ago that I wouldn't be able to support it - but as it turns out, I was able to integrate with the ember-inspector's websocket implementation. Pull down :sparkles: ember-electron 0.5.0 :sparkles: and you'll get a working Ember Inspector ;-)

**Comment by acorncom** [comment]
Sweet!  Looks like we can close this issue then
