### ISSUE TITLE
Release for Ember 2.3.0.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-inspector#513]
@teddyzeenny - Can we push out a new release with the fixes from #510?

**Comment by orf** [comment]
I hate to +1 one this but... +1. Ember inspector has been broken for a while now with 2.3.0 and the fix seems pretty trivial.

**Comment by sly7-7** [comment]
@orf, just let some time, @teddyzeenny has already open this new release: https://github.com/emberjs/ember-inspector/pull/516 
There is no doubt he will publish as soon as he can.

**Comment by teddyzeenny** [comment]
@orf if you're using Chrome or the bookmarklet the new version is published (1.9.5)

**Comment by sly7-7** [comment]
@rwjblue I think this could be closed now :)

**Comment by rwjblue** [comment]
Thanks for reminding me!
