### ISSUE TITLE
Resizable table headers

### ISSUE THREAD

**Issue by camskene** [emberjs/ember-inspector#520]
Inside the developer tools it's possible to resize the table headers in the network tab. The same functionality would be nice to have inside the ember inspector.

![out](https://cloud.githubusercontent.com/assets/507499/12890893/9f350cd4-ce53-11e5-901a-e41d16b58dcd.gif)

**Comment by camskene** [comment]
I will work on this if there's enough interest. A few people I asked agreed this would be useful to them.

**Comment by mgallag** [comment]
This would be very useful. Right now the only way to read long paths / filenames is to stretch the browser window open across multiple monitors.

**Comment by JonET** [comment]
It would also be useful if I could choose which columns are visible.

**Comment by koryteg** [comment]
I was looking into the css changes that would need to happen to do some of this and I believe that it would take a lot of work that may conflict with or could be incorporated into the work that @teddyzeenny is doing on the tables right now. he is removing `list-view` and adding `smoke and mirrors` (the table addons.). 

It would be good to get some input on how do implement this. It might be a good add-on that utilizes mixins, that way it could be plugged into existing tables and add-ons.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/574

**Comment by camskene** [comment]
Awesome work on #574. Thank you.
