### ISSUE TITLE
Ember Using Parent Route

### ISSUE THREAD

**Issue by DevGuy128** [emberjs/ember-inspector#522]
I am creating an app that lets users answer and create polls. I have 4 pages, an index, polls listing, single poll page, and a results for the single poll. Here is my router code:

`Router.map(function() {
  this.route('polls', function() {
    this.route('poll',{ path:':poll_id' },function(){
      this.route('results');
    });
  });
});`

The results page is displaying the poll template, instead of the results template, like it should. The wierd thing is, Inspector says it's using the right route and template. Does anyone know what's going on?

**Comment by sly7-7** [comment]
Hi, could you reproduce it in ember-twiddle, it will be easier for us to help: https://ember-twiddle.com/ ?
Also not sure if this issue belongs to the inspector repo.

**Comment by DevGuy128** [comment]
Yes, I accidentally put it in the inspector category.

On Tue, Mar 1, 2016 at 6:28 AM, Sylvain MINA <notifications@github.com>
wrote:

> Hi, could you reproduce it in ember-twiddle, it will be easier for us to
> help: https://ember-twiddle.com/ ?
> Also not sure if this issue belongs to the inspector repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember-inspector/issues/522#issuecomment-190677508>
> .
>



-- 
Visit my blog:http://homeschoolson.com

**Comment by sly7-7** [comment]
No problem, simply close this issue then :)
