### ISSUE TITLE
EmberJs Inspector crashes

### ISSUE THREAD

**Issue by kulbida** [emberjs/ember-inspector#525]
### Here is an error message I received, it happened when I tried to open Data tab.

===

The connection to ws://localhost:49152/livereload was interrupted while the page was loading. livereload.js:74:0
Content Security Policy: The page's settings observed the loading of a resource at self ("script-src http://localhost:4200 'unsafe-eval' http://localhost:49152 http://0.0.0.0:49152"). A CSP report is being sent. localhost:4200:1:0
DEBUG: ------------------------------- vendor.js:16301:5
DEBUG: Ember      : 2.3.1 vendor.js:16301:5
DEBUG: Ember Data : 2.3.1 vendor.js:16301:5
DEBUG: jQuery     : 2.2.0 vendor.js:16301:5
DEBUG: ------------------------------- vendor.js:16301:5
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendor.js:125100:210
Ember Inspector Active content-script.js line 53 > eval:86:14
"Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: _emberData.default.store is undefined
Stack trace: @http://localhost:4200/assets/launcher.js:223:5
Module.prototype.exports@http://localhost:4200/assets/vendor.js:63:20
Module.prototype.build@http://localhost:4200/assets/vendor.js:113:1
findModule@http://localhost:4200/assets/vendor.js:161:5
requireModule@http://localhost:4200/assets/vendor.js:148:12
Resolver<._extractDefaultExport@http://localhost:4200/assets/vendor.js:66191:20
resolveOther@http://localhost:4200/assets/vendor.js:65923:27
superWrapper@http://localhost:4200/assets/vendor.js:32665:17
exports.default<.resolve@http://localhost:4200/assets/vendor.js:15652:30
resolve@http://localhost:4200/assets/vendor.js:12381:18
Registry.prototype.resolve@http://localhost:4200/assets/vendor.js:11921:21
Registry.prototype.resolve@http://localhost:4200/assets/vendor.js:11923:19
factoryFor@http://localhost:4200/assets/vendor.js:11446:19
Container.prototype.lookupFactory@http://localhost:4200/assets/vendor.js:11333:14
containerAlias/<@http://localhost:4200/assets/vendor.js:42749:15
exports.default<._nameToClass@http://localhost:4200/assets/vendor.js:16781:16
exports.default<.getModelTypes/types<@http://localhost:4200/assets/vendor.js:16978:18
exports.default<.getModelTypes@http://localhost:4200/assets/vendor.js:16976:15
exports.default<.watchModelTypes@http://localhost:4200/assets/vendor.js:16756:24
getModelTypes@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:843:35
apply@http://localhost:4200/assets/vendor.js:32856:1
sendEvent@http://localhost:4200/assets/vendor.js:26602:11
exports.default<.trigger@http://localhost:4200/assets/vendor.js:44016:7
messageReceived/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:2799:9
wrap/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:2829:18
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10718:18
run@http://localhost:4200/assets/vendor.js:30697:12
wrap@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:2827:1
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:2798:7
init/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:2790:11
_messageReceived/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:134:9
_messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:133:7
_listen/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:418:11
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10718:18
run@http://localhost:4200/assets/vendor.js:30697:12
_listen/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ember-inspector-at-emberjs-dot-com/ember-inspector/data/content-script.js line 53 > eval:405:9
" content-script.js line 53 > eval:99:14

===
the issue here is obviously "Error message: _emberData.default.store is undefined" but how can I fix it? Thanks is advance.

**Comment by teddyzeenny** [comment]
Is it possible your are using `DS.store` instead of `DS.Store` in your app?

**Comment by locks** [comment]
Closing due to staleness. If this is still an issue let us know @kulbida!
