### ISSUE TITLE
After a page reload, the opened source-mapped file is not persisted in Firefox Debugger tab 

### ISSUE THREAD

**Issue by kemenaran** [emberjs/ember-inspector#530]
Steps to reproduce:
1. Open Firefox, and go to http://captaintrain.github.io/stations-studio with the Ember-Inspector enabled
2. Open the Developers Tools, and switch to the Debugger tab
3. Open any sourcemap-defined script (like `src/geocoder.js`)
4. Reload the web page

Actual results:
The Debugger tab is now open on ember-inspectors's `content-script.js` file.

Expected results:
The Debugger tab should be open on the previously selected file (`src/geocoder.js`).

The behavior is correct when the Ember Inspector is not enabled. (But it may be a Firefox bug triggered by this specific use case ; if that's so I can file a bug in Firefox.)

**Comment by rwwagner90** [comment]
This sounds like a Firefox issue, since it is not a bug in inspector, but rather FF itself switching scripts when you reload. I would file a bug there.
