### ISSUE TITLE
Cutom Adpter updateRecord unable to update ember model 

### ISSUE THREAD

**Issue by Maruboinasuresh** [emberjs/ember-inspector#531]
How to get promise through updateRecord into controller.

**Example:**
var question = this.store.adapterFor('component').updateRecord('component', {
          message: this.get('message'),
          id  : this.get('id')
      });
      question.then(function(data) {
      console.log('RESPONSE",data);
     });

Here console.log printed but ember data model not updated, please suggest how to get promise method for updateRecord

**Comment by teddyzeenny** [comment]
I don't fully understand the question. How is it related to the Ember Inspector?

**Comment by Maruboinasuresh** [comment]
oh sorry.., it is related to ember-data issue.
