### ISSUE TITLE
PDF links are displayed as blank pages in chrome

### ISSUE THREAD

**Issue by mguida22** [emberjs/ember-inspector#532]
With the ember-inspector installed for chrome when loading most PDF links, it will display as a blank white page. I have no idea what can cause this, but only when the ember-inspector extension is this an issue.

I haven't tried this on another computer but I can reproduce it on my machine as follows.

- have ember inspector active
- visit http://ga.berkeley.edu/wp-content/uploads/2015/02/pdf-sample.pdf (sample pdf)
- a blank page is displayed  😢 
- reload page
- the PDF is displayed

Relevant information:

ember inspector version: 1.9.5
chrome version: 49.0.2623.112 (64-bit)
mac version: OS X El Capitan Version 10.11.3 (15D21)

If you need any more information let me know. Thanks!

**Comment by lasernite** [comment]
I'm having this same issue as well, I was wondering what was going on. It's easily reproducible on my machine as well:

ember inspector version: 1.9.5
chrome version: 49.0.2623.110 (64-bit)
Mac OSX version: 10.11.4 (15E65)

**Comment by felixbuenemann** [comment]
I have the same problem in Chrome 52.0.2707.0 on MacOS X 10.11.4 and Ember Inspector 1.9.5.

How about inspecting `document.contentType` before injecting the script?

For the PDF viewer this returns `application/pdf`.
