### ISSUE TITLE
Display a nice error when viewing the new welcome page

### ISSUE THREAD

**Issue by acorncom** [emberjs/ember-inspector#534]
As mentioned [in this issue](https://github.com/ember-cli/ember-welcome-page/issues/22) (for the new welcome screen that we'll be showing as part of Ember-CLI in the near future), it'd be nice to have a message saying "You're just getting started" or something like that, rather than "Ember application not detected".

"Ember application not detected" is actually correct (as we're displaying a static page), but we'd like to fake something a bit nicer ;-)

I'm happy to do the work (and have some ideas of where I'd make the changes for this), but wanted to get your 👍 on making the change prior to sending in an unexpected PR ;-)

**Comment by locks** [comment]
@acorncom I'm closing this as we're revamping ember-welcome-page and possibly this won't be applicable.
