### ISSUE TITLE
Instrumentation and other performance data

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember-inspector#54]
For profiling reasons, it would be great if we could display application instrumentation and other performance related data:

* View render durations (https://github.com/eviltrout/ember-renderspeed)
* Run loop duration and frequency (prototype: http://jsbin.com/uBiYELO/14/edit)
* Application memory usage
* Route transition duration
* Custom instrumentation data (http://emberjs.com/api/classes/Ember.Instrumentation.html)

**Comment by locks** [comment]
After an internal discussion it was decided that the current overhead of the instrumentation hooks, with the fact that people are usually measuring the apps in dev mode, let's to inaccurate results that people tend to take as gospel. We're closing it for now, to possibly revisit in the future.
