### ISSUE TITLE
Latest release Firefox

### ISSUE THREAD

**Issue by danilovaz** [emberjs/ember-inspector#545]
In the Firefox addon the latest release is 1.9.4, when you will update this addon for 1.10.0?

Thank's

**Comment by locks** [comment]
@danilovaz unfortunately the Firefox review process is wildly unpredictable. Hopefully it goes through soon!

**Comment by danilovaz** [comment]
@locks I can imagine. I hope it comes out soon, very useful this project. Thanks.

**Comment by teddyzeenny** [comment]
@danilovaz 1.10.0 only contains internal changes to the code but no visible bug fixes and features (except for Chrome). Which is why I did not publish this version to Firefox.

**Comment by teddyzeenny** [comment]
I just realized 1.9.5 is also missing from Firefox. Will publish asap.

**Comment by callahad** [comment]
Has 1.9.5 or 1.10.0 been submitted to addons.mozilla.org? We've finally fixed the slow / inconsistent review process, and I'd love to hear if there's anything else we can do to make sure supporting Firefox is as simple and seamless as possible.

**Comment by callahad** [comment]
Pinging @teddyzeenny

**Comment by teddyzeenny** [comment]
@callahad the Firefox review process has been amazing. The delay is purely on me as I've been incredibly busy lately. I'm also currently rewriting a big chunk of the inspector to upgrade it from Ember 1.12 to 2.6. I will publish to FF once I finish my upgrade PR.

**Comment by teddyzeenny** [comment]
1.10 is now on Firefox.
