### ISSUE TITLE
ember inspector gets completely blank after live-reloading while inspecting a model under a subdirectory

### ISSUE THREAD

**Issue by HenryVonfire** [emberjs/ember-inspector#548]
I have a project with models under subfolders (i.e. `models/posts/comment.js`) and whenever I'm inspecting them in the `ember-inspector`, if I make a change in the code and let the live-reload reloads the page, `ember-inspector` gets completely blank and forces me to close and reopen the browser to make it works again.

I've tested this issue in Chrome, Chromium and Firefox.

**Comment by raido** [comment]
I have similar issue with 2 ember apps, one includes other using iframe.

After selecting the app in the iframe from the dropdown in the inspector, it crashes with blank page with following error:

```
inspector.js:6154 Position missing 'column' or 'column' < 0.callback @ inspector.js:6154
chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/panes-2-7-0/assets/ember-inspector.js:343 

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
inspector.js:6154 Position missing 'column' or 'column' < 0.callback @ inspector.js:6154
inspector.js:9963 evaluate: there is no frame with URL about:blank
inspector.js:9987 Extension server error: Object not found: about:blank
inspector.js:6154 Position missing 'column' or 'column' < 0.callback @ inspector.js:6154
inspector.js:9963 evaluate: there is no frame with URL javascript:false
inspector.js:9987 Extension server error: Object not found: javascript:false
vendor.js:12166 Uncaught Error: Cannot re-register: `adapter:main`, as it has already been resolved.
```

**Comment by teddyzeenny** [comment]
@raido this seems like a separate issue. It may be better to track it in a separate ticket.

@HenryVonfire can you provide an example app (jsbin or public repo) where we can reproduce this? BTW you probably only need to close and reopen devtools (not the browser).

**Comment by raido** [comment]
@teddyzeenny -> https://github.com/emberjs/ember-inspector/pull/551

**Comment by HenryVonfire** [comment]
> @HenryVonfire can you provide an example app (jsbin or public repo) where we can reproduce this? BTW you probably only need to close and reopen devtools (not the browser).

Sure, I'll try to create a repo with an example. 

That was the first thing I tried (closing the devtools only) but it didn't work. It stays the same after reopening them.

**Comment by HenryVonfire** [comment]
Here's the repository (https://github.com/HenryVonfire/inspector-bug)

Steps to generate it:
- run `ember s`
- open the app in a browser (firefox / chrome)
- open the inspector
- go to `Data`
- click on the model `test/potato`
- click in the record to show the detailed view of the record
- make a change in the project to provoque `live-reload` to reload the app

After this the inspector should get completely empty.
