### ISSUE TITLE
Ember Inspector Routes Tab Blank

### ISSUE THREAD

**Issue by alr888** [emberjs/ember-inspector#554]
Hi,

I'm running Ember Inspector version 1.10.0 Chrome Extension on Windows 10.
I just noticed my Routes tab doesn't show any routes.

Attached are screenshots showing this exception including app stack versions.
I have also restarted Ember server and browser, but still have the same issue.

Thanks in advance for any advise on this.

Cheers,

Ariel
[Ember Inspector Routes Blank.pdf](https://github.com/emberjs/ember-inspector/files/318147/Ember.Inspector.Routes.Blank.pdf)

**Comment by teddyzeenny** [comment]
You seem to be exporting a non-route from your `libraries/new` route module. Is that correct?

**Comment by locks** [comment]
@alr888 can you confirm the above?

**Comment by alr888** [comment]
@teddyzeenny , @locks its was a problem with my libraries/new route.  Recoded it and deployed it on Firebase and routes are there.  Apologies not replying sooner.

**Comment by locks** [comment]
No problem, thank you for the update!
