### ISSUE TITLE
Alphabetically sort data view

### ISSUE THREAD

**Issue by mguida22** [emberjs/ember-inspector#562]
It would be nice to have the ability to sort alphabetically on any of the table columns within the data view, and also on the `attributes`, `belongs to`, `has many`, etc. lists when viewing a specific object. Especially with lots of data and attributes, it gets hard to find a specific item. Thanks!

**Comment by teddyzeenny** [comment]
There's a search field you can use in the data tab. As for the object inspector, would a search field help with this problem?

**Comment by mguida22** [comment]
A search field would be better, but I think being able to sort the display alphabetically would be best. I don't feel strongly though, just a suggestion I had!

**Comment by ryanlitalien** [comment]
@teddyzeenny I tried a first pass, as I needed the sorting as well. I'd be super gracious if you could implement sorting on model properties!

**Comment by rwwagner90** [comment]
https://github.com/emberjs/ember-inspector/pull/622 seems to have been merged a long time ago. Did it resolve this issue?

**Comment by rwwagner90** [comment]
@Bestra @nummi @pbishop16 I think the essence of this issue, is we should support sorting alphabetically in each column of the models table, so if you want to view the data for all your models, and click an arrow, which would flip up and down for asc and desc, it should sort the records by that field. Is anyone interested in taking a stab at this?

**Comment by Bestra** [comment]
To be clear we're talking of something similar to http://opensource.addepar.com/ember-table/latest/docs/guides/header/sorting, correct?

**Comment by rwwagner90** [comment]
@bestra yep! I believe ember-table has been rewritten to use vertical collection as well, so if it is possible to switch out our tables for ember-table, I'd be in support of that too.

**Comment by jakeboyles** [comment]
🎈 🎈 🎈 🎈 🎈 🎈 🎈 🎈 🎈 🎈
