### ISSUE TITLE
This Ember version is not supported in development environment.

### ISSUE THREAD

**Issue by vvscode** [emberjs/ember-inspector#564]
I install addon for Chrome from github repo ( I try both `master` / `stable` ) and got 

> This Ember version is not supported in development environment.

We use Ember `1.13.x` -- how can I fix it ? Cause version from Chrome store is buggy ( it detect application not every time )

**Comment by teddyzeenny** [comment]
If you want to build the inspector from source for production use (not to develop the inspector) you will need to use `npm run build:production`.

> Cause version from Chrome store is buggy ( it detect application not every time )

I doubt building from source will fix that. That sounds like a bug that we should fix. Are you able to help me reproduce this issue so I can look into it? Is your app inside an iframe?

**Comment by vvscode** [comment]
@teddyzeenny  No, my app not inside iframe. And it didn't see app not always, but sometimes. I need to close, refresh, open ( sometimes repeat one-two times ) to repair it's work. But I didn't know steps to broke it

**Comment by teddyzeenny** [comment]
Does that happen on other online public Ember apps or just your private app? If you can point me to any online app that does this or public repo or jsbin I can work on fixing it.

**Comment by vvscode** [comment]
Sometime I get the situation on public auth app, but right now it's ok. What information I can attach if it repeat?
Possible it's chrome bug, cause sometime when Ember inspector detect app I can't get $E -- it show in console that variable assigned, but on trying get it I got `$E is undefined`

Just say what details I can provide, and if I met it again - I'll post report

P.S. with local copy all works fine

**Comment by teddyzeenny** [comment]
You can open devtools for devtools and check the console for errors. You do that by undocking devtools into a separate window and then opening devtools for that new window. Also describe what exactly happens ("Application not detected" or blank inspector, etc).

I'm going to close this issue (it is about a different topic). If you encounter the problem again feel free to open a new issue with as much info as you can so we can reproduce and fix it.
