### ISSUE TITLE
Check 'current route only' by default

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember-inspector#566]
Our application has several hundred routes. Iterating them all takes ~1 second.

It's great that this happens only when visiting the routes tab, but would be better if 'current route only' was checked by default. It would also make it easier to find the current route (otherwise one has to look for bold in the long list).

![image](https://cloud.githubusercontent.com/assets/122287/17376876/c5f458e4-59b7-11e6-8c10-2ca911f3186f.png)

Thanks for a great extension! ⛵

**Comment by locks** [comment]
Hi @sandstrom, can you tell us why you need to access the current route?

Having it on by default would be more confusing to less advanced users IMO, as they'd expect to see the whole hierarchy so they can explore. We could make it a preference, but if we can get at the root of the problem and address that, the solution will be stronger.

**Comment by teddyzeenny** [comment]
One more question @sandstrom, would you consider https://github.com/emberjs/ember-inspector/issues/567 to be a solution to your problem? You would always see the current route by default until you close the tab.

**Comment by sandstrom** [comment]
Closing, mostly fixed by https://github.com/emberjs/ember-inspector/commit/276d77b65f7a3557e89581805ab7217d42795de0

thanks @teddyzeenny & @locks
