### ISSUE TITLE
Persist "Current Route only" through refreshes

### ISSUE THREAD

**Issue by locks** [emberjs/ember-inspector#567]

**Comment by teddyzeenny** [comment]
Should "just work" by making `hideRoutes`a query param [here](https://github.com/emberjs/ember-inspector/blob/67404b7aea2bccd8733ad49bbaccfa7b7b5c59b2/app/controllers/route-tree.js).

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/568
