### ISSUE TITLE
Use model's `primaryKey` value on data tab

### ISSUE THREAD

**Issue by ralphholzmann** [emberjs/ember-inspector#57]
Heyo,

My models are configured to use `_id` as their primary key instead of `id`, by setting the `primaryKey` property on the model. It would be great in ember-extension could use this value as well. Currently it seems hard coded to `id`, therefore not correctly reporting the PK of my models:

![sad models](http://i.ralph.io/hyu3rith.png)

**Comment by thorsteinsson** [comment]
The `primaryKey` should be set on the serializer and not the model.
