### ISSUE TITLE
[GLIMMER] Known issues

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#582]
- [x] When a re-render only causes component removal (no components are added) the components view tree is not updated.  This is due to the fact that "willRender" doesn't fire when expected. This will probably be fixed in Ember core before Glimmer beta is released. Related issue: https://github.com/emberjs/ember.js/issues/13947
- [ ] If more than one outlet share the same controller instance, their children components will be combined and listed under the first outlet. That is due to the fact that we are matching components to outlets by comparing controllers. I can work on that when I'm back from vacation in a week.

**Comment by chancancode** [comment]
@teddyzeenny I think emberjs/ember.js#14222 fixed the first issue, can you confirm?

**Comment by teddyzeenny** [comment]
@chancancode I confirm the issue is fixed 🎉 .

There was one regression though https://github.com/emberjs/ember-inspector/pull/588, should be fixed next time I publish. It may be good to have a `ViewUtils.getRootElement` API to avoid future breakage however I'm not sure what's the story behind multiple roots - `ViewUitls.getRootElement(s)`?

**Comment by chancancode** [comment]
@teddyzeenny that's usually not something you would see in apps. it's mainly for things like ember-islands where you manually instantiate multiple `Component`s and call `appendTo(...)` on each of them manually

**Comment by chancancode** [comment]
@teddyzeenny what is the status of this? do you need any new APIs from me? 😄

**Comment by teddyzeenny** [comment]
@chancancode we'd need a way to know which components belong to which outlet without matching them through their controllers (which is what we're doing at the moment). The edge case that doesn't work currently when using controllers to match components to outlets is when multiple outlets use the same controller - all components will go under the first outlet.

That being said, tbqh I think our effort is best spent on building a Glimmer API to display the entire DOM tree in the inspector (à la devtools Elements tab) so we can replace the inspector's view tree altogether with a more sophisticated tab . So I'm thinking let's skip this issue and start working on an API for the new tab. What do you think?

**Comment by rwwagner90** [comment]
Since we have the new component view tab now, I am closing this. Feel free to reopen if we need to do more work here!
