### ISSUE TITLE
Data Tab - Column Headers not refreshing when changing model type

### ISSUE THREAD

**Issue by alejandrocibilich** [emberjs/ember-inspector#586]
Clicking on Data Tab and then on Model Type number 1 (`item` in the example printscreen), shows the correct column headers:
![image](https://cloud.githubusercontent.com/assets/19896046/18335236/2d53012c-7554-11e6-8a25-8c6846ce9393.png)

Clicking on Data Tab and then on Model Type number 2 (`menu` in the example printscreen), shows the correct column headers:
![image](https://cloud.githubusercontent.com/assets/19896046/18335221/0b9883ae-7554-11e6-8dc4-e3f2507b7404.png)

After that, if you don't click on Data Tab and click directly on Model Type 1 (`item` in the example printscreen), even though it shows the correct data, it doesn't show the correct column headers. Clicking on one Model Instance, further shows the discrepancies between column headers and field names on the right panel:
![image](https://cloud.githubusercontent.com/assets/19896046/18335261/78d2f300-7554-11e6-9ab2-08444f28f064.png)

It seems it's not refreshing the column headers when switching between model types.

**Comment by mkriegeskorte** [comment]
Same here!

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.7.2
DEBUG: Ember Data        : 2.7.0
DEBUG: jQuery            : 2.2.4
DEBUG: Ember Simple Auth : 1.1.0
DEBUG: -------------------------------
```

Ember Inspector 2.0.1 (Chrome Web Store)

**Comment by teddyzeenny** [comment]
Thanks for the bug report! I'm on it.
