### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-inspector#590]
@rwjblue is working on making jQuery an optional dependency of Ember. Once that has progressed far enough we should investigate what we need to do to drop our dependency on jQuery too.

https://github.com/emberjs/ember-inspector/blob/master/shared/in-page-script.js for example will need to be adjusted to a world without jQuery.

**Comment by rwjblue** [comment]
FWIW, it is already possible to use Ember without jQuery (you just need a custom event dispatcher at the moment).

**Comment by locks** [comment]
A custom event dispatcher by ours truly: https://github.com/rwjblue/ember-native-dom-event-dispatcher

**Comment by cibernox** [comment]
I will try to work on this as soon as I can put a couple hours in a row

**Comment by acorncom** [comment]
This was resolved by #768

**Comment by rwwagner90** [comment]
@acorncom technically, this isn't 100% done. While our jQuery usages have been removed, there is something still using it, and if you remove it from vendor, things break.

**Comment by cibernox** [comment]
@rwwagner90 When I removed jQuery, I did it from the parts of the app that ran along with the app, so the addon could be useful in apps without jQuery, but I didn't care about usages of jQuery INSIDE the addon itself. 

That said, personally I'd remove it completely and ensure CI don't have it, so we can be sure we don't use it, not even by mistake.

**Comment by rwwagner90** [comment]
@cibernox yeah, that's what I mean. Inspector itself, not the part that runs in the consuming app. Mainly want to remove it to align with the removal we have been doing across the learning team.

**Comment by acorncom** [comment]
Reopening in the interests of tracking the remaining work needed to remove internal jQuery usage
