### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by locks** [emberjs/ember-inspector#594]
As commented on https://github.com/emberjs/ember-inspector/issues/561: 

* [x] #43
* [ ] #115
* [x] #119
* [x] #130
* [x] #141
* [x] #142
* [ ] #143
* [ ] #170
* [x] #248
* [x] #259
* [ ] #268
* [ ] #429
* [x] #448

**Comment by sandstrom** [comment]
Awesome! These were just some examples I pulled from the oldest issues. I think there are many more.

**Comment by locks** [comment]
Closing this issue as we're doing a thorough review of the entire catalog.
