### ISSUE TITLE
Components View Tree broken in ember 2.9.0-beta2

### ISSUE THREAD

**Issue by felixbuenemann** [emberjs/ember-inspector#598]
The current master (44e820f) as well as 2.0.2 break when the Component checkbox is ticked on the View Tree tab with the following exception:

**TypeError: Cannot read property 'get' of undefined**

Full Backtrace:

```
TypeError: Cannot read property 'get' of undefined
    at _default.controllerForComponent (<anonymous>:1821:35)
    at <anonymous>:1464:42
    at Array.forEach (native)
    at _default.componentsForController (<anonymous>:1463:20)
    at <anonymous>:1427:34
    at Array.map (native)
    at _default.build (<anonymous>:1342:63)
    at Class.viewTree (<anonymous>:4658:33)
    at <anonymous>:4630:27
    at fn (http://localhost:4200/assets/vendor.js:15457:18)
```

**Comment by teddyzeenny** [comment]
Can you reproduce this in a jsbin/online app/public repo?

**Comment by felixbuenemann** [comment]
I'm not sure how to build a test case, because I don't know how to find out the component which causes this. I can see the `emberNNN` id on the component, but I have no idea how to trace it back to the actual name of the component.

I can say that the problem is triggered because `component.get('_targetObject')` in `controllerFroComponent` returns `undefined` so it tries to recurse an then runs into the above mentioned exception, because it calls `controllerForComponent(undefined)`.

**Comment by felixbuenemann** [comment]
I think the ember-cli-head component really has no controller, because it is [inserted into the DOM from an initialiser](https://github.com/ronco/ember-cli-head/blob/master/app/instance-initializers/browser/head.js).

So maybe the assumption that each component must have a controller is wrong?

**Comment by teddyzeenny** [comment]
Yes we should likely guard against that. Although that will mean not showing these components in the view tree.

**Comment by felixbuenemann** [comment]
It's also interesting to note that the exception did not occur on 2.8.1, maybe someone from the ember core team like @rwjblue can comment on wether it is expected behaviour that `_targetObject` of components can be undefined.

I only found a [single usage](https://github.com/emberjs/ember.js/blob/beta/packages/ember-runtime/lib/mixins/target_action_support.js#L146)  of `_targetObject` in the ember codebase and it is guarded by an if.

**Comment by teddyzeenny** [comment]
That's because the inspector doesn't use `_targetObject` in Ember < 2.9. `_targetObject` is used post Glimmer 2.
