### ISSUE TITLE
Deep dive into Ember Inspector Internals on The Ember Show

### ISSUE THREAD

**Issue by taras** [emberjs/ember-inspector#600]
Hey Teddy,

Would you be interested in giving a talk on The Ember Show about the internals of Ember Inspector?
This could be a great opportunity to tell lower the barrier to contributing to a tool that's very important to the community.

What do you think?

**Comment by f3ndot** [comment]
Throwing my hat into the ring: I'm curious what this repo accomplishes (technically) at 10,000ft.

How does it leverage in-page-script.js, content.js, background.js to facilitate what appears to be an Ember application that's aware of the website's own Ember application? What's the code execution flow for this bootstrap? Etc.?

I have a vested interested in understanding how one can interrogate a website's Ember app programmatically from a Chrome extension.

**Comment by teddyzeenny** [comment]
Hey @taras @f3ndot my email is my github username at gmail, let's discuss this over email. Closing this to keep github issues for Ember Inspector bugs.
