### ISSUE TITLE
errors not logging to console

### ISSUE THREAD

**Issue by jaredgalanis** [emberjs/ember-inspector#602]
I've got several pages which are not rendering, but no error is logged in the browser console. I have been able to find errors within some objects themselves in the Inspector. For instance a computed property on a model was not resolving properly and it was throwing an error, but it was only reported when I viewed the model that the computed property was defined on in the data panel of the inspector. 

I'm using Chrome 53 and Ember Inspector 2.0.2.

For what it's worth, I was previously having the issues described in #561 so I updated to Ember 2.8.1 (which resolved that problem).

**Comment by locks** [comment]
In the specific case of the computed property, they're lazily evaluated and only compute when consumed, so your description is how it's expected to work.
Do you have a small reproduction we can check out?

**Comment by jaredgalanis** [comment]
Ah okay, thanks @locks! I now realize the other pages which were not firing any errors were all making use of an addon that was no longer functioning. I'm not sure why I was receiving no errors at all, but I found a substitute way of addressing that particular addon's functionality so it is no longer an issue in my project.

**Comment by locks** [comment]
> is there a more central location that would show that computed property is having an issue?

Not really. There isn't really a way to know and trigger unconsumed computed properties.
