### ISSUE TITLE
Not detecting the Ember app with Ember 2.8.0?

### ISSUE THREAD

**Issue by givanse** [emberjs/ember-inspector#604]
Chrome: 53.0.2785.116 (64-bit)
Ember cli: 2.8.0

Default app, I just did `ember new foobar; cd foobar; ember serve` but the inspector doesn't detect it:

![screen shot 2016-09-28 at 5 00 23 pm](https://cloud.githubusercontent.com/assets/431270/18936542/163ba86e-859d-11e6-9c81-410eb8716e77.png)

![screen shot 2016-09-28 at 5 00 48 pm](https://cloud.githubusercontent.com/assets/431270/18936552/23cf5e44-859d-11e6-9d0b-e943dfe4225f.png)

Re-installed the extension and restarted the browser, didn't help.
I don't see any errors either :S

**Comment by givanse** [comment]
Interesting, the inspector worked after removing the welcome addon, `"ember-welcome-page": "^1.0.1",`.

**Comment by locks** [comment]
@givanse `ember-welcome-page` is actually an express middleware that serves the page in your screenshot above when the application doesn't have any templates. We are aware of this problem and are working on it!
Thanks for reporting, I'm closing the issue as it isn't entirely related to Inspector. Feel free to keep track at the `ember-welcome-page` repo, or ask us on Slack!
