### ISSUE TITLE
Feature request: autogenerated entity-relationship diagrams

### ISSUE THREAD

**Issue by fotinakis** [emberjs/ember-inspector#613]
Had a thought... it would be amazing to have a tab in the Ember Inspector that auto generates an ERD based on the current Ember Data models and their relationships.

Here's an equivalent in the Rails world:
https://github.com/voormedia/rails-erd

Which generates ERDs like:
![687474703a2f2f766f6f726d656469612e6769746875622e696f2f7261696c732d6572642f696d616765732f656e746974792d72656c6174696f6e736869702d6469616772616d2e706e67](https://cloud.githubusercontent.com/assets/75300/19833476/621b3192-9df7-11e6-9494-bf3c1c3cabec.png)

You could then go to any Ember site, open the inspector and see a graphical representation of the frontend data model.

I was thinking about this because I just found a bug in my app where Ember Data was guessing an inverse relationship incorrectly and I needed to add `DS.belongsTo(... {inverse: null})` to break the link to the unrelated model. That kind of broken relationship mapping could potentially be seen in an ERD and discovered quickly. Another use case, it would be really helpful for onboarding new frontend devs in an app and explaining data models, especially as it would always be automatically up to date.

**Comment by hjdivad** [comment]
@stefanpenner and i have done this internally, albeit in lolcode and not in a way that's publicly available.

@fotinakis do you have any cycles to work on this?  we could likely extract some of our efforts (much of which may already have been extracted in [dotbars](https://github.com/stefanpenner/dotbars))

**Comment by stefanpenner** [comment]
i do like the coloring more, i should update ours

**Comment by stefanpenner** [comment]
example @hjdivad mentioned:

dotbars file: https://github.com/stefanpenner/dotbars/blob/master/examples/er.dot
dotbars runner: https://github.com/stefanpenner/dotbars/blob/master/examples/er.js

@hjdivad we need to extract our traverser code and share it

**Comment by stefanpenner** [comment]
![out](https://cloud.githubusercontent.com/assets/1377/19945356/0911221a-a0fd-11e6-826f-2329b7eab3cd.png)

**Comment by stefanpenner** [comment]
> Ember Data models and their relationships.

My thought, is it would be likely best to generate an ER diagram for 1 model, and that ER diagram would be what it reaches. For example, we work on some complicated apps. A single ER diagram for those complex apps, would be... less the useful, and most likely would just crash the browser :P Although I should test if it would crash or not..

**Comment by hjdivad** [comment]
> My thought, is it would be likely best to generate an ER diagram for 1 model, and that ER diagram would be what it reaches. For example, we work on some complicated apps. A single ER diagram for those complex apps, would be... less the useful, and most likely would just crash the browser :P Although I should test if it would crash or not..

Also focusing on one model is a very useful hint for graph layout.  Having the diagram drawn after you've selected a single model is i think the main use case

**Comment by rwwagner90** [comment]
I don't think we're looking to support this, at this time, but if anyone has the cycles, and would like to take a stab at it, it seems like a fine idea to me!
