### ISSUE TITLE
Ember 2.10 CHILD_VIEW_IDS error

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember-inspector#618]
Not sure exactly what the cause of this issue is, but it's exposed by trying to use `this.set` to set a key on an object that is being iterated over in an `each-in`.

See: https://github.com/emberjs/ember.js/issues/14661

**Comment by rwjblue** [comment]
Basically, ember-inspector is observing the `CHILD_VIEW_IDS` symbol on a component instance, which we set without `Ember.set`.

Associated links:

* https://github.com/emberjs/ember.js/blob/e34ed31a0ddf6dd43f375348a9f3f9ee11a0eb9c/packages/ember-views/lib/system/utils.js#L89
* https://github.com/emberjs/ember.js/blob/e34ed31a0ddf6dd43f375348a9f3f9ee11a0eb9c/packages/ember-views/lib/system/utils.js#L109

This results in the classic mandatory setter error:

```
Assertion Failed: You must use Ember.set() to set the `CHILD_VIEW_IDS [id=__ember1480545924918304558307952]` property (of <mission-control@component:my-component::ember1757>) to `ember1759`."`
```

**Comment by teddyzeenny** [comment]
@rwjblue we need to update [this list](https://github.com/emberjs/ember-inspector/blob/e28c9185c3a8c1e99705a9791086c689a1b91c1b/ember_debug/object-inspector.js#L662-L674) to include new properties such as `CHILD_VIEW_IDS` and make it apply to components (it used to work when components inherited from `Ember.View`).

**Comment by rwjblue** [comment]
Ya, but since `CHILD_VIEW_IDS` is actually one of our internal symbols it isn't a static value (it's actually randomly generated for each eval of Ember) and it is not exposed to the rest of the world (since it is technically private) we'll need a way to identify these types of properties...

**Comment by teddyzeenny** [comment]
@rwjblue we can define a [_debugInfo](https://github.com/emberjs/ember-inspector/blob/e28c9185c3a8c1e99705a9791086c689a1b91c1b/ember_debug/object-inspector.js#L652) method on the component where you can specify private properties. We already do that for ED models. I think we can avoid exposing the value of the symbol in this case.
