### ISSUE TITLE
Ember Inspector for Microsoft Edge?

### ISSUE THREAD

**Issue by froomzy** [emberjs/ember-inspector#619]
Hi all,

I have been doing some learning of Ember recently, and have been Edge as my browser.  I tried the bookmarklet, but that is a bit harder to setup then I would like on Edge. Because Edge and bookmarks are a bit silly looking. Or at least to me as a new user used to Chrome.

It made me curious though. Has anyone investigated porting the inspector to Edge? Is it something that could happen? Or is it a no go for reasons?

Cheers for any answers.

Dylan

**Comment by stefanpenner** [comment]
may be possible re: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6508820-javascript-browser-extensions

**Comment by teddyzeenny** [comment]
We'd need the ability to extend devtools using extensions. I took a very quick look at [the supported APIs page](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-APIs/) but didn't see anything related. I also found [this ticket](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15574155-allow-extensions-to-exist-on-the-devtools-pane) asking for devtools extension support.

**Comment by rwwagner90** [comment]
This may be possible with these instructions, unsure https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

**Comment by rwwagner90** [comment]
We think supporting every browser with their own extensions is more work than it is worth. We are going to explore using a standalone app for these other browsers.
