### ISSUE TITLE
Inconsistent Version Number

### ISSUE THREAD

**Issue by jreading** [emberjs/ember-inspector#623]
Not sure why I have the same browser reporting two different version numbers for the inspector on two different apps.

![screenshot at dec 21 17-22-22](https://cloud.githubusercontent.com/assets/301830/21408263/1295cf7c-c7a2-11e6-8796-cd747c97acd9.png)

Any idea what this is? Is this intended? I think it's related to some other issues I am having with the data tab and model fragments.

This is the same browser, same profile. The 2.0.4 one is a new app I just spun up to test.

**Comment by teddyzeenny** [comment]
Ember < 2.7 apps use Ember Inspector 1.10.0. Ember >= 2.7 apps use Ember Inspector latest. This is so we can drop support for old Ember versions without breaking the inspector for old apps.

**Comment by teddyzeenny** [comment]
If you're still having issues with the data tab feel free to open another ticket. It would be very helpful if you can provide a way to reproduce it of course.

**Comment by jreading** [comment]
Ok, good to know it's not my app code responsible. My issue is with Model Fragments; I'll open a new ticket.
