### ISSUE TITLE
How to add other items to the "info" pane?

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/ember-inspector#627]
I'd like to add some things in the toolbar for when people are using it for debugging such as the version of inhouse addons and what not. Is this possible?

**Comment by teddyzeenny** [comment]
If I understood the question correctly, you want to add additional libraries to the info tab? If that's what you need then you can call`Ember.Libraries.register(name, version)` in your app.

**Comment by tsteuwer** [comment]
Where do you call this? In index.js?

**Comment by teddyzeenny** [comment]
You can call it anywhere, doesn't even need to be part of the app. You can call it in `app/app.js`.

**Comment by acorncom** [comment]
@tsteuwer looks like this issue can be closed?
