### ISSUE TITLE
Show all model attributes in the Data tab's list view

### ISSUE THREAD

**Issue by jtrost** [emberjs/ember-inspector#631]
The Ember Inspector only shows the first four attributes of a model in the Data tab. It would be convenient if it showed all of the attributes in list view. When viewing a model that returns many records, I sometimes want to quickly see a single attribute for every record, but I can't do this since list view is limited to four attributes.

The [Ember Guide](https://guides.emberjs.com/v2.11.0/ember-inspector/data/) says: "The first four model attributes are shown in the list view," so I know this is by design, but is there a good reason why the Data tab works this way? Can all of a model's attributes be listed in the list view?

**Comment by locks** [comment]
I'd say it's mostly for space and performance reasons. Horizontal scrolling is also iffy.

**Comment by teddyzeenny** [comment]
This limit is [set in Ember core](https://github.com/emberjs/ember.js/blob/cdcd3853a9e013f8963ab59fafd25560c4850ed5/packages/ember-extension-support/lib/data_adapter.js#L89) and is configurable. You can reopen `data-adapter:main` and set `attributeLimit: 100`. However, you should expect some UI issues as @locks mentioned.

**Comment by acorncom** [comment]
@jtrost looks like this issue can be closed now?
