### ISSUE TITLE
routeNames.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember-inspector#633]
![screen shot 2017-02-13 at 1 30 20 pm](https://cloud.githubusercontent.com/assets/75710/22897153/a394cd98-f1f0-11e6-804a-a04fe4a49856.png)

Running into this error when visiting the routing tab in the Ember inspector.  Possibly an issue with Ember 2.12.0-beta.1

Inspector info: 
![screen shot 2017-02-13 at 1 31 46 pm](https://cloud.githubusercontent.com/assets/75710/22897183/cd2fdd28-f1f0-11e6-88d0-8c0481ab69db.png)

**Comment by bantic** [comment]
I have seen this as well. In my case, the inspector error disappeared after downgrading to ember version 2.11.0.

**Comment by locks** [comment]
Repro: www.linkedin.com

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember-inspector/pull/635, but that doesn't seem to be released yet?

**Comment by mjsommer** [comment]
Having same issue, with:

Ember Inspector	2.0.4
Ember	2.10.0-beta.2-patched-beta+dafad266
Ember Data	2.12.0-canary.c2af5be
jQuery	2.1.4

How can I fix this, and see the routes?

**Comment by mixonic** [comment]
This seems to be closed in #635 and released. Closing for now, please re-open if I have missed something.
