### ISSUE TITLE
'Data' not responding to clicks

### ISSUE THREAD

**Issue by duncan-bayne** [emberjs/ember-inspector#636]
I load my Ember app in development (running on my local machine), and click Data (`resource://ember-inspector-at-emberjs-dot-com/data/panes-0-0-0/index.html#data`).  I can see the data being used by my application, as expected.

If I load the same app in staging (running on an Amazon EC2 instance), Data does not respond to clicks in any way; it doesn't highlight, and it doesn't subsequently display the data being used by the application.

Is there a configuration option I need to enable in staging, in order to use this functionality?  I looked in [the documentation](https://guides.emberjs.com/v2.11.0/ember-inspector/data/) but didn't see anything.

**Comment by acorncom** [comment]
@duncan-bayne I saw a similar report on this issue: https://github.com/ember-cli/ember-resolver/issues/175, does the new ember-resolver release fix your problem?

**Comment by rwwagner90** [comment]
I've noticed a few times I need to click the Data tab a few times and it will work after that. Are you still experiencing this issue?

**Comment by nickschot** [comment]
I have seen this issue too with one app consistently, but not with all my apps. Let me know what I can do to pin this issue down @rwwagner90 .

**Comment by rwwagner90** [comment]
@nickschot is that app using engines or anything non-standard? Is the ember-resolver version perhaps outdated as @acorncom mentioned above?

**Comment by nickschot** [comment]
It's a normal app with (currently) one npm linked addon which also contains models. It's on Ember 3.0, CLI 3.4 and Data 3.4. Resolver is ^5.0.1, so don't think that's it.

**Comment by rwwagner90** [comment]
@nickschot I just reread the initial issue here, and it sounds like it worked in development, but did not work in a deployed staging environment. Is that the same issue you are having?

**Comment by nickschot** [comment]
Ah no it occurs in development for me, haven’t checked anything else yet.

**Comment by rwwagner90** [comment]
@duncan-bayne @nickschot without more information or a reproduction, I am unable to dig much deeper into this. I am going to close for now, but if you have a reproducible way to trigger this, let me know!
