### ISSUE TITLE
Feature request: Make engine's store visible

### ISSUE THREAD

**Issue by jnfingerle** [emberjs/ember-inspector#643]
Using engines one can either use the application's store or have new one for the engine. 

It would be great if I could select an engine's store in the data view instead of the application's store.

**Comment by cyril-sf** [comment]
I may look into it as I need it too.

**Comment by albertpak** [comment]
has there been any update on this issue?

**Comment by locks** [comment]
@albertpak nope, is this something you're interested in helping with?

**Comment by rwwagner90** [comment]
Closing in favor of #632
