### ISSUE TITLE
Styling doesn't show in Opera

### ISSUE THREAD

**Issue by basicBrogrammer** [emberjs/ember-inspector#651]
After using the instructions in the read me, ember inspector is added to the dev tools in Opera, but the styling is not loaded. 
![image](https://cloud.githubusercontent.com/assets/6913826/24863376/92f27ba2-1dce-11e7-90c3-baf0646eec31.png)

**Comment by cyril-sf** [comment]
Fixed by #652 

cc @teddyzeenny

**Comment by locks** [comment]
Thanks for the reminder, but especially for the fix!

**Comment by basicBrogrammer** [comment]
Awesome Thanks !
