### ISSUE TITLE
lookupFactory deprecation fix not yet released

### ISSUE THREAD

**Issue by bgentry** [emberjs/ember-inspector#656]
On a recent version of Ember (v2.12 or v2.13), the inspector causes a ton of deprecation warnings from the lookupFactory deprecation. It looks like this was resolved in https://github.com/emberjs/ember-inspector/pull/645 but never released. I tried following the trail but couldn't tell if there were still blockers preventing a new release.

Any way we could get a new version published? :pray:

**Comment by locks** [comment]
I believe this is out, please reopen if otherwise!
