### ISSUE TITLE
Not multiprocess compatible (Firefox)

### ISSUE THREAD

**Issue by jgelens** [emberjs/ember-inspector#661]
Got an error in FF nightly that the extension is not multiprocess compatible; with a link to the following page: https://wiki.mozilla.org/Add-ons/ShimsNightly

**Comment by locks** [comment]
Thanks for the report :) You don't happen to have experience with this that you can help us out?

**Comment by jgelens** [comment]
No, sorry, never developed a plugin for Firefox :( . Just wanted to report this, because I guess it's kinda important for future stable versions.

**Comment by clarkbw** [comment]
We should start looking at Firefox using the WebExtension code and this error will go away.

**Comment by locks** [comment]
Issue tracked at https://github.com/emberjs/ember-inspector/issues/666!
