### ISSUE TITLE
Unusable urls after moving ember to 2.12 or 2.13

### ISSUE THREAD

**Issue by KillaPL** [emberjs/ember-inspector#663]
Hello

My application currently stands on ember 2.11, ember data is on 2.13 and ember cli is on 2.13. We are currently blocked from moving to 2.13 because when we do, Urls section in ember data is broken like this:
![undefined_urls](https://cloud.githubusercontent.com/assets/1272828/26159491/fecdcff8-3b1e-11e7-85bb-da091ec6b853.png)

Is this a known issue, and is there a known solution? If not, what can I do to help solve it?

Thank you

**Comment by vanne** [comment]
Same here. Having exactly the same problem with freshly generated empty app (as well as with existing apps updated to 2.12).

ember-cli: 2.12.3
node: 6.10.3
ember inspector: 2.0.6

<img width="1049" alt="screen shot 2017-05-19 at 14 37 35" src="https://cloud.githubusercontent.com/assets/20854/26248019/c9c50154-3ca0-11e7-8908-14057f6fe095.png">

**Comment by KillaPL** [comment]
This seems to be fixed by https://github.com/emberjs/ember-inspector/commit/3a012d8db1e3f177f42a51735fddbc75457bd313 . Can't wait to get on it!: )

**Comment by KillaPL** [comment]
Works perfectly with new version, thank you!
