### ISSUE TITLE
Hiding inspector is not working now. earlier it used to work

### ISSUE THREAD

**Issue by kumkanillam** [emberjs/ember-inspector#664]
I used to define  `window.NO_EMBER_DEBUG = true`  inside app.js file, this configuration earlier it was working. but now it stopped working.  related #195 . Is there anything do I need to do disable inspector for production build.

**Comment by locks** [comment]
I can't reproduce it, setting `window.NO_EMBER_DEBUG = true` does what is expected.
Can you provide more information on versions, and ideally a reproduction?

**Comment by kumkanillam** [comment]
Discussed and solved it on #-ember-inspector slack channel thanks to @teddyzeenny  and @locks . Problem is, I have written this configuration inside `ready` hook of the `Ember.Application`. Actually, we need to set `window.NO_EMBER_DEBUG = true` before Ember is loading. Either it can be placed inside app.js file like the below,
This will enable inspector in development mode and disable it in production mode.
```
if (config.environment === 'development') {
    window.NO_EMBER_DEBUG = false;
} else {
    window.NO_EMBER_DEBUG = true;
}
```
or it in `index.html`

Note: To test this configuration, we need to close already opened Ember.Inspector and do refresh and check it.
