### ISSUE TITLE
Add support to Firefox Nightly: 55.0a1 (2017-05-31) (64-bit)

### ISSUE THREAD

**Issue by wellington1993** [emberjs/ember-inspector#665]
Hi,

please add support to Firefox Nightly 55.0a1 (2017-05-31) (64-bit) and add to multiprocess (Like another issue)

Thanks!

**Comment by locks** [comment]
Duplicate of https://github.com/emberjs/ember-inspector/issues/666 and https://github.com/emberjs/ember-inspector/issues/661
