### ISSUE TITLE
add a refresh button for Data tab like you do for Container

### ISSUE THREAD

**Issue by robneville73** [emberjs/ember-inspector#672]
For apps like mine where there are some models that are created on the fly via queried metadata, it'd be nice to be able to tell the inspector to requery the app registry for newly defined models. (or alternatively, we may be doing something wrong that's preventing them from showing up but being otherwise usable).

**Comment by teddyzeenny** [comment]
How do you dynamically define the models? Do you use register them manually into the container?

**Comment by robneville73** [comment]
Yes, exactly
