### ISSUE TITLE
Search View Tree

### ISSUE THREAD

**Issue by shoxter** [emberjs/ember-inspector#677]
Sometimes we have hundreds of components in the view tree at a given time and it would be extremely useful to be able to search the contents of that view tree for a specific component.

Thoughts?

**Comment by kamikaz1k** [comment]
+1

**Comment by kamikaz1k** [comment]
I put up a PR to address this issue. If you are still interested in this functionality please drop into the PR.

**Comment by rwwagner90** [comment]
We have search in both the view tree and components tree, so this is done.
