### ISSUE TITLE
Maybe also show ember-cli version in info tab ? 

### ISSUE THREAD

**Issue by bekzod** [emberjs/ember-inspector#680]
I think only ember-cli version missing from `info tab`

**Comment by locks** [comment]
@bekzod I'm not sure that is exposed, and would only be available during development, right?

**Comment by bekzod** [comment]
@locks yeah its not exposed, it needs some modification either in `ember-cli` or in `ember-app-version` addon so it passes `emberCLIVersion` to environment so it can be picked up by ember-inspector I guess :)

**Comment by locks** [comment]
cc @stefanpenner @twokul

**Comment by bekzod** [comment]
maybe `ember-cli` can pass additional analytics data to `ember-inspector` along side version, not sure what though :P

**Comment by twokul** [comment]
might be asking a stupid question here but what's the value of seeing `ember-cli` version in the browser? why would that info be useful for a developer?

**Comment by locks** [comment]
@twokul flipping this on its head, don't we want to expose it for better errors at least?

**Comment by twokul** [comment]
@locks yeah I think so

**Comment by twokul** [comment]
but it makes sense there, as we want to expose all build tool info there. I'm not pushing back, just genuinely trying to understand

**Comment by stefanpenner** [comment]
> I think only ember-cli version missing from info tab

in development or in production? In dev seems totally fine, prod would leak what version of tools people are using on there laptops, which makes me nervous.

**Comment by andyhot** [comment]
I don't see any value in this. What may be important are the dependecy versions in the package.json but still...

**Comment by davidwkeith** [comment]
Currently the Express server is sending a `x-powered-by` header of just "Express". If `ember-cli` were to customize that to be something like "ember-cli 2.15.1; node 8.1.4; os darwin x64", the inspector could pick it up and do the right thing without having to conditionally include developer tool info in the built output.

Taking that further, once `ember-cli` is detected, another header with an additional port number to connect on (or a pre-defined 'special route' sans header) could open a ton of diagnostics information to the inspector including:

- Dependency versions and info (yarn, node, etc)
- Unit test results/code coverage (standardized output like CI servers consume)
- Auto-setup Persistence with DevTools Workspaces (Is there even an API for this?)
- Lint errors
- git info (branch, dirty, etc)

Likely more, this is just off the top of my head right now.

**Comment by rwwagner90** [comment]
Since ember-cli is just the build tool, I don't know how useful this would be. @teddyzeenny what do you think?

**Comment by teddyzeenny** [comment]
It will be providing extra information that a user cannot currently deduce via devtools since it's not a runtime library, so we should be careful about what information we want to expose. If we can make sure this info is only displayed during dev then I think it can be fine/useful, why not.

**Comment by rwwagner90** [comment]
@teddyzeenny it just feels redundant because if you are developing, you can see all that in your terminal.

**Comment by rwwagner90** [comment]
Closing due to lack of interest. If someone still really wants this, let me know!
