### ISSUE TITLE
Implement "Inspect component" contextual menu

### ISSUE THREAD

**Issue by locks** [emberjs/ember-inspector#689]
When right-clicking a DOM element in the page, the contextual menu should have an "Inspect Ember component" option that takes you to the appropriate Inspector route.

See ["Inspecting components just got easier"](https://medium.com/the-vue-point/whats-new-in-vue-devtools-4-0-9361e75e05d0) for inspiration.

**Comment by Bestra** [comment]
I'm working on this

**Comment by thorsteinsson** [comment]
We're working on this together

**Comment by rwwagner90** [comment]
@Bestra @thorsteinsson how's this going? Need any help from me?
