### ISSUE TITLE
DEPRECATION: Usage of router is deprecated thrown when access #/Routes tab

### ISSUE THREAD

**Issue by kumkanillam** [emberjs/ember-inspector#691]
When I access #/Routes tabs, it's throwing deprecation warning.

> DEPRECATION: Usage of router is deprecated, use _routerMicrolib instead. [deprecation id: ember-router.router] See http://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib for more details.

```
ember-cli: 2.14.1  
http_parser: 2.7.0 
node: 6.3.1        
v8: 5.0.71.57      
uv: 1.9.1          
zlib: 1.2.8        
ares: 1.10.1-DEV   
icu: 57.1          
modules: 48        
openssl: 1.0.2h    
os: win32 x64      
3.10.3             
0.21.3  
 ```

**Comment by locks** [comment]
Did you address this one when you upgraded @cibernox?

**Comment by rwjblue** [comment]
Should have been fixed by https://github.com/emberjs/ember-inspector/pull/658. Are there other situations where we were hitting the deprecation that weren't fixed? Have we perhaps not released since that was merged?

**Comment by locks** [comment]
> Have we perhaps not released since that was merged?

I don't think we have.

**Comment by teddyzeenny** [comment]
@kumkanillam can you please check if this is still happening on Ember Inspector 2.1.0?

**Comment by kumkanillam** [comment]
@teddyzeenny Yes. 2.1.0 fixed the issue. thank you
