### ISSUE TITLE
Release of new version?

### ISSUE THREAD

**Issue by KillaPL** [emberjs/ember-inspector#700]
Hey

I'd like to ask when could we expect the release of new version. It would seem that https://github.com/emberjs/ember-inspector/issues/663 is already solved, and will only require new version to be released.

**Comment by stephanebruckert** [comment]
Temporarily you could try to specify the commit you want as part of your `package.json`, have a look at https://stackoverflow.com/a/18049685/1515819

**Comment by teddyzeenny** [comment]
2.1.0 released.

**Comment by KillaPL** [comment]
Works perfectly, thank you!
