### ISSUE TITLE
Compatibility with new modules API (Ember 2.16)

### ISSUE THREAD

**Issue by locks** [emberjs/ember-inspector#707]
With the release of Ember 2.16, it is planned that projects will now use the [new modules API (RFC 176)](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) by default.
However, you can already use them in your application if you have `ember-cli-babel` 6.6 or higher.

We are asking community members that have moved their addons and applications to new modules already to test out the Inspector and help us make sure that if something happens to break, that we can try to address it before the release.

The instructions are:
- Make sure you're using the latest version of the Inspector (2.1.0 at the time of writing)
- Navigate to your app
- Open up Ember Inspector
- Use your app and the Inspector and report any breakage as a separate issue an link here in a comment

Thank you! :) We are aware that there are some current bugs in the Inspector, we're trying to address those as well!

**Comment by nightire** [comment]
@locks It should be 2.1.0 instead of 2.0.1, isn't it?

**Comment by sivakumar-kailasam** [comment]
@locks Seems to be working fine on 2.18 and 3.0. Probably good to close.
