### ISSUE TITLE
Compact view tree listing for Name column

### ISSUE THREAD

**Issue by jnthnwn** [emberjs/ember-inspector#710]
It's difficult to view the names of the components when components are deeply nested, especially when working with a more compact single monitor setup. The current level of indentation causes the name of some components to be completely obscured by the adjacent column.

Is it possible to reduce the amount of indentation or use another visual indicator for nesting level?

**Comment by rwwagner90** [comment]
We're currently working on a new component tree, which should fix these issues https://github.com/emberjs/ember-inspector/issues/774 😄
