### ISSUE TITLE
Does not work in Firefox Nightly

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember-inspector#726]
Just tried the new WebExtension and the Ember tab in the Devtools is just an empty pane.
Launching current stable (56) works perfectly though.

**Comment by teddyzeenny** [comment]
Which Firefox version does it fail on and what's the installed Ember Inspector addon version?

**Comment by topaxi** [comment]
Firefox 58
Ember Inspector 2.2.0

**Comment by topaxi** [comment]
Working now with latest Nightly (58), probably been a Firefox bug?

**Comment by locks** [comment]
Thanks for following up :)
