### ISSUE TITLE
Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by Charizard** [emberjs/ember-inspector#727]
![screen shot 2017-10-11 at 10 37 02 pm](https://user-images.githubusercontent.com/1897178/31454954-c620e49a-aed4-11e7-9d93-165e03a1d2a3.png)

My environment:
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.16.0
DEBUG: Ember Data        : 2.16.2
DEBUG: jQuery            : 3.2.1
DEBUG: Ember Bootstrap   : 1.0.0-rc.3
DEBUG: Ember Simple Auth : 1.4.0
DEBUG: -------------------------------
```

**Comment by teddyzeenny** [comment]
Hi, thanks for reporting this! Can you reproduce this in an online app or repo?

**Comment by jacobq** [comment]
FWIW, I have run into this when trying to use `ember-inspector` after there's been a serious error earlier (e.g. trying to use a component/helper in a template that the app can't find/doesn't exist).

**Comment by mswanson** [comment]
I am seeing a similar error after disabling the application template wrapper in the latest ember 3.1.0-beta

![screenshot 2018-04-02 23 39 23](https://user-images.githubusercontent.com/144861/38229591-16cfa1ce-36cf-11e8-95bf-ade4d0880c08.png)

**Comment by rwwagner90** [comment]
@mswanson I think that is a new issue, not the same as here. @teddyzeenny is this original issue still something we need to fix or can we close?

**Comment by rwwagner90** [comment]
@mswanson I'm pretty sure it is different, one is `rootElement.getAttribute` is not a function and another is `getAttribute` of undefined. I think this issue may no longer be an issue, but the one you are seeing might be.

**Comment by teddyzeenny** [comment]
@rwwagner90 I agree, I'm going to close this issue. @mswanson do you mind opening a new issue so we can track the Ember 3.1-beta issue?

**Comment by mswanson** [comment]
@rwwagner90 @teddyzeenny done. https://github.com/emberjs/ember-inspector/issues/775
