### ISSUE TITLE
App freezes on record unload

### ISSUE THREAD

**Issue by alexphys** [emberjs/ember-inspector#733]
I was trying to unload/delete a record on `willTransition` of a route while looking at the inspector to check if its removed.
When the record was unloaded/deleted the app would then freeze.
If I close the inspector and repeat this , then the record is unloaded/deleted successfully without freezing the app and I can then open up the inspector and see everything working fine.

Tested on 

- Chrome Version 62.0.3202.62 (Official Build) (64-bit)
- Ember Inspector | 2.3.0
- Ember | 2.12.2
- Ember Data | 2.16.3

**Comment by rwjblue** [comment]
Seems roughly the same as https://github.com/emberjs/ember-inspector/issues/725, can you review that issue and let us know if it’s the same?

**Comment by alexphys** [comment]
Closing as its the same as #725
