### ISSUE TITLE
Support Firefox 57.0 ("Quantum")

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember-inspector#735]
Right now https://addons.mozilla.org/de/firefox/addon/ember-inspector/ says that ember-inspector is not compatible.

**Comment by teddyzeenny** [comment]
Hi! It was recently disabled by Mozilla addon review because of its use of `unsafe-eval` in its content security policy, but I'm working on getting it approved again.

**Comment by luketheobscure** [comment]
I haven't done any addon development, but when I built from source and tried on my local firefox (v57) complained about the `options_page` in manifest.json. Removing this made everything work, and I was still able to access the options page.

**Comment by teddyzeenny** [comment]
The addon should be compatible now.
