### ISSUE TITLE
Firefox add-on doesn't recognise that Ember is running on https://www.emberjs.com

### ISSUE THREAD

**Issue by pauljacobson** [emberjs/ember-inspector#740]
I just installed the [Ember Inspector add-on for Firefox](https://addons.mozilla.org/en-US/firefox/addon/ember-inspector/) (version 2.3.1). It doesn't recognise that Ember is running on the Ember site (I've configured Tomster to display in my location bar when I'm on an Ember site).

![developer_tools_-_ember_js_-_a_framework_for_creating_ambitious_web_applications__-_https___emberjs_com__and_ember_js_-_a_framework_for_creating_ambitious_web_applications_](https://user-images.githubusercontent.com/2912202/34071308-1edb34b0-e27d-11e7-951a-9f19567f21dd.png)

**Comment by teddyzeenny** [comment]
Hi @pauljacobson. I don't think the Ember homepage is running Ember. The [API](https://emberjs.com/api/ember/) and the [Builds](https://emberjs.com/builds/) pages are running Ember so you should be able to use the inspector on these pages.

As for the Tomster icon, it only works if the Ember library is loaded before the domready event, which might not be the case on the Ember website pages that run Ember.

**Comment by pauljacobson** [comment]
@teddyzeenny ah, ok, apologies. My mistake. The inspector picks up Ember on the Builds and API pages.
