### ISSUE TITLE
Consider dropping Ember 1.x support / `ember-new-computed`

### ISSUE THREAD

**Issue by jacobq** [emberjs/ember-inspector#745]
I'm not sure how long Ember 1.x is to be supported, but I think it's been 2+ years since v1.13.13 was released. If it isn't supported any more then it would be nice to drop `ember-new-computed` from this project's dependencies since it currently (v1.0.0) triggers a [deprecation warning for Ember v2.18+](https://github.com/ember-cli/ember-cli-version-checker/issues/48) (shown below). (I've also [requested that `ember-new-computed` be updated to fix this](https://github.com/rwjblue/ember-new-computed/issues/12).)

```
├─┬ ember-inspector@2.3.0
│ └─┬ ember-new-computed@1.0.3
│   └─┬ ember-cli-babel@5.2.4
│     └── ember-cli-version-checker@1.3.1 
```

```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/path/to/project/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

**Comment by teddyzeenny** [comment]
Ember 1.x is not supported. I believe we can safely remove `ember-new-computed`.

**Comment by jacobq** [comment]
See PR #746 -- should be all set to merge, if you like.
