### ISSUE TITLE
Interferes with unrelated websites

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember-inspector#747]
I've discovered that images aren't being loaded on this website for me only: https://express42.com/ (`img`s miss `src` attributes).

After disabling extensions one by one and retrying, I was astonished to discover that Ember Inspector is responsible.

Disabling Ember Inspector and refreshing the page resolves the issue. Re-enable the inspector -- and the issue is back.

**Comment by teddyzeenny** [comment]
That is indeed surprising. Thanks for reporting it, I will look into it!

**Comment by teddyzeenny** [comment]
It seems https://express42.com/ is overwriting `window.removeEventListener` for some reason.

**Comment by teddyzeenny** [comment]
While we're calling `window.removeEventListener` to unsubscribe from an event that we set up, the website's overwritten `window.removeEventListener` new behavior stops their image from displaying. I'm closing this as there's nothing we can do if the website is overwriting native DOM methods and changing their behavior. If anyone has ideas how to handle that I can reopen.

**Comment by lolmaus** [comment]
Thank you for debugging this. :bow: I'll pass your findings to the site owner.
