### ISSUE TITLE
"Cannot read property 'outlets' of undefined" On Ember 3.1-beta.1

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember-inspector#770]
Stacktrace from error message:

```
Uncaught TypeError: Cannot read property 'outlets' of undefined
    at exports.default.getApplicationOutlet (<anonymous>:1478:40)
    at exports.default.buildOutletTree (<anonymous>:1290:49)
    at exports.default.build (<anonymous>:1266:31)
    at Class.viewTree (<anonymous>:4573:33)
    at later (<anonymous>:4547:25)
    at invoke (backburner.js:207)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
    at Backburner._runExpiredTimers (backburner.js:831)
```

Stacktrace from error object:

. | . | .
--- | ---- | ----
getApplicationOutlet | @ | VM1282:1478
buildOutletTree | @ | VM1282:1290
build | @ | VM1282:1266
viewTree | @ | VM1282:4573
later | @ | VM1282:4547
invoke | @ | backburner.js:207
flush | @ | backburner.js:125

Points to this code:

```js
    /**
     * Returns the application (top) outlet.
     *
     * @return {Object} The application outlet state
     */
    getApplicationOutlet() {
      return this.getRoot().outletState.outlets.main;
    }
```

Can be reproduced on an empty `ember new foo` app.

**Comment by lolmaus** [comment]
Looks like upgrading to Ember Inspector to 3.0.0 helped.

Sorry, I upgraded it, was seeing `3.0.0` version number and the error. Looks like I had to restart the browser or something.

**Comment by nightire** [comment]
@lolmaus This issue shouldn't be closed b/c it reflects an error caused by 3.1-beta.x, as it introduced a new feature: https://github.com/emberjs/rfcs/blob/master/text/0280-remove-application-wrapper.md, sooner or later users will notice this bug.

**Comment by rwwagner90** [comment]
@nightire are you seeing this bug? I was pretty sure we fixed it. If you are on Ember Inspector 3.0.0, it should work with Ember 3.0+.

**Comment by nightire** [comment]
@rwwagner90 Oh I'm sorry, this is a different error, I misread it, my bad... 😰

**Comment by rwwagner90** [comment]
No worries @nightire! If you'd like to help fix that issue, PRs would be greatly appreciated! 😄
