### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#771]
Copying over data from slack:

it looks like we actually can detect the devTools theme from `chrome.devtools.panels.themeName`. @teddy where would be the best spot to check this?

teddy [6:26 AM]
we can add a CP `isDarkTheme` or `theme` on the adapter
https://github.com/emberjs/ember-inspector/blob/1aa8f03e1f00a6166042b61914a0ccdf03a4512b/app/adapters/web-extension.js
https://github.com/emberjs/ember-inspector/blob/1aa8f03e1f00a6166042b61914a0ccdf03a4512b/app/adapters/chrome.js

Then check the theme in `x-app`
https://github.com/emberjs/ember-inspector/blob/1aa8f03e1f00a6166042b61914a0ccdf03a4512b/app/components/x-app.js

We should use CSS variables to switch the colors based on this.

**Comment by pbishop16** [comment]
@rwwagner90 I would like to tackle this.

**Comment by rwwagner90** [comment]
@pbishop16 sure thing! We would love the help 😃 . Please feel free to ping me with questions on slack. I'm happy to help however I can.

**Comment by pbishop16** [comment]
@rwwagner90 Greatly appreciated. Will do.

**Comment by nummi** [comment]
@rwwagner90 close?

**Comment by rwwagner90** [comment]
This is done now 👍
