### ISSUE TITLE
[Quest] - Implement Component Tree

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#774]
- [ ] Land the current context menu PR
- [ ] Have two tabs for component and views
- [ ] Make the component tab only have the component tree and attrs, no models or tables etc

More items to come 😄 

Feature branch: https://github.com/emberjs/ember-inspector/tree/component-tree

cc @thorsteinsson @Bestra

**Comment by Bestra** [comment]
@nummi Future wish list:
- [ ] Use specific overlays for the component tab
- [ ] Visually distinguish between components with/without blocks in the tree

**Comment by rwwagner90** [comment]
I think this is done, since we merged the component tree in. If we need to do more things, we can open another issue.
