### ISSUE TITLE
[Error] - `rootElement.getAttribute is not a function` when using 3.1.0-beta

### ISSUE THREAD

**Issue by mswanson** [emberjs/ember-inspector#775]
![error](https://user-images.githubusercontent.com/144861/38343742-459be346-384b-11e8-8c21-afac167ba1d2.png)

I am using the latest 3.1 beta versions of ember and ember-cli

![screenshot 2018-04-02 23 19 17](https://user-images.githubusercontent.com/144861/38229038-4a49ab60-36cc-11e8-80f8-c745f62244c3.png)

```
ember-cli: 3.1.0-beta.1
node: 9.5.0
os: darwin x64
```

#### Steps to reproduce
1. Installed the latest ember-cli beta `yarn global upgrade ember-cli#3.1.0-beta.1`
2. `ember install @ember/optional-features`
3. `ember feature:disable application-template-wrapper`
4. opened Ember Inspector in Chrome

![screenshot 2018-04-04 21 02 38](https://user-images.githubusercontent.com/144861/38343793-8708f076-384b-11e8-86c1-4156e9d0f255.png)

**Comment by rwjblue** [comment]
The wrapper div was only guaranteed for the top level route template, none of the others had wrapping elements.

**Comment by rwwagner90** [comment]
@rwjblue fair enough, but all of our view tree stuff, and it appears components, controllers, and everything is dependent on `buildOutletTree` it https://github.com/emberjs/ember-inspector/blob/master/ember_debug/libs/glimmer-tree.js#L139

I assumed there was some magic somewhere in here that find nested outlets when inspecting, but I'm not 100% positive. We could remove the concept of inspecting outlets / route templates etc and just have the new component tree, but outlets could be useful.

I'm also not sure if anything else would break if we removed this stuff outright, and if more than just the view tree relies on this stuff.

**Comment by fran-worley** [comment]
I'm finding the same error with ember-source 3.1.2 and ember cli 3.1.4 when application-template-wrapper is disabled.

**Comment by rwwagner90** [comment]
@fran-worley Yes, I do not think we have a way around this, at the moment. @rwjblue any ideas?

**Comment by rwwagner90** [comment]
@teddyzeenny @Bestra  we need `buildOutletTree` for everything right?

**Comment by Bestra** [comment]
@rwwagner90 I dunno, actually :).  It'll be a good reason for me to dive in a bit.

**Comment by Bestra** [comment]
I've been trying to reproduce this locally without any luck yet.
I'm on ember 3.1.2
<img width="624" alt="screen shot 2018-05-18 at 11 49 46 am" src="https://user-images.githubusercontent.com/2043348/40244937-33880202-5a92-11e8-88a4-783ce1a97db3.png">

I've got the feature flag turned off:
```
$ cat config/optional-features.json
{
  "application-template-wrapper": false
}
```
Ember cli 3.1.4
```
ember -v
ember-cli: 3.1.4
node: 9.4.0
os: darwin x64
```

I've got an app with a few routes in it:
```
Router.map(function() {
  this.route('about', function () {
    this.route('us');
  })
});
```
and for kicks here's a screenshot of the app html without the wrapper. 
<img width="406" alt="screen shot 2018-05-18 at 12 03 33 pm" src="https://user-images.githubusercontent.com/2043348/40245438-ac7c24bc-5a93-11e8-866e-38cf74d627a3.png">


It's _very_ possible I'm missing something.  @rwwagner90 can you currently reproduce?

**Comment by Turbo87** [comment]
@Bestra you can use https://github.com/skylines-project/skylines to reproduce this. I've disabled the application wrapper there yesterday evening and started seeing these issues too.

**Comment by robclancy** [comment]
Wait why was this released with this bug still existing? At least catch it and give a message about the application wrapper being required for now.

**Comment by rwwagner90** [comment]
@robclancy there have been several other fixes and features we needed to get out. We released to fix those things.
