### ISSUE TITLE
Models that extend DS.Model using ES6 class syntax not picked up by Inspector

### ISSUE THREAD

**Issue by allthesignals** [emberjs/ember-inspector#777]
Models written this way don't seem to be picked up by the Inspector. Here's a related [thread](https://github.com/ember-decorators/ember-decorators/pull/211). The models seem to be working fine otherwise. 

```javascript
export default class LayerGroup extends Model {}
```

Thoughts?

**Comment by rwwagner90** [comment]
I would assume that the model view looks specifically for the `DS.Model` or at least non-class based models. I would need to dig in and look around.

**Comment by jamescdavis** [comment]
I am not seeing this behavior. All of our models are defined with ES6 classes and do appear in the inspector.

**Comment by jamescdavis** [comment]
You can try it on https://osf.io. Model definitions: https://github.com/CenterForOpenScience/ember-osf-web/tree/develop/app/models

**Comment by onceatime** [comment]
have the same problem... looks that it has todo with ember decorators and how inspector pics up models.

**Comment by rwwagner90** [comment]
@onceatime it sounds like @jamescdavis sees things working fine, can we compare your models to his and see if we can find the issue?

**Comment by onceatime** [comment]
sure, if i find the time i also can create a sample application.... for now i hope this helps...

this works:
```
export default DS.Model.extend();
```

this not:
```
export default class Sample extends DS.Model {}
```

i think jamescdavis example works because it uses typescript and i use default js with ember-decorators. thanks and cheers

**Comment by onceatime** [comment]
i finally found time to create a sample app. It contains a default model and a model decorated with ember-decorators. to Run it:

```
yarn && yarn ember serve
```

then open http://127.0.0.1:4200/ and open ember-inspector in chrome. It shows one model only but not the one that uses ember-decorators

[https://github.com/onceatime/ember-inspector-decorators-sample](url)

**Comment by rwwagner90** [comment]
Thanks @onceatime! I will try to take a look this week.

**Comment by localpcguy** [comment]
I think the difference is that this:
```export default class Sample extends DS.Model {}```
is not picked up, while this:
```export default class Sample extends DS.Model.extend({}) {}```
is picked up.

However, even though the second syntax is picked up, it doesn't show the attributes defined via decorators in the model Detail view (the columns are all there with the data, so this seems specific to the Detail view when clicking a specific data item).

**Comment by rwwagner90** [comment]
I don't use Typescript, classes, or decorators myself, so I would love some help with this, if anyone would like to give it a shot!

**Comment by localpcguy** [comment]
I'll try to take a look after hours this week. Haven't worked on an plugin in the past, but looks like the README has good instructions on how to get started and how to install the dev version. I'll ping on the Slack channel if I have questions, if that's ok.

**Comment by bartocc** [comment]
I've investigated this a bit as I've had the issue in my app for a long time. Turn out that this seems to be fixed with `ember-source` 3.3.0 and has nothing to do with `ember-decorators` or `ember-inspector`.

To investigate, I've created 3 barebone apps:

- one with ember-cli 3.1.4
- one with ember-cli 3.2.0
- one with ember-cli 3.3.2

In each, I've got 2 empty models.

```js
// app/models/model-a.js
import DS from 'ember-data';
export default DS.Model.extend({});
```

```js
// app/models/model-b.js
import DS from 'ember-data';
export default class ModelB extends DS.Model {}
```

`ember-inspector` in 3.1.4 and 3.2.0 fail to display model-b while 3.3.0 does show it!

Could you guys double check this?

**Comment by rwwagner90** [comment]
From what I have heard, this is fixed in latest ember-source.

**Comment by rwjblue** [comment]
Yes, it should work from Ember 3.3+...

**Comment by bartocc** [comment]
Great !
