### ISSUE TITLE
UI Tweaks April 2018

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#778]
*Whitespace, alignment, consistency.*

"7 commits; 38 changed files; 372 additions and 287 deletions." I have this all on one branch but the commits are pretty isolated to the different parts the UI. I can drop a single PR or one for each commit. I figured we could discuss things before I do that.

<details>
  <summary>Toolbar</summary>

Slightly taller, more breathing room for items.  Old on top, new on bottom.

![toolbar](https://user-images.githubusercontent.com/3692/38449492-bb2022d8-39c4-11e8-865a-d3db6ed9e70f.png)

---

"Toolbar Radios". The selected item stands out more. Style is at home in Firefox and Safari

![toolbar more](https://user-images.githubusercontent.com/3692/38449493-bb40b4b2-39c4-11e8-803e-6502ea14be45.png)

---

White space is used for larger click areas on buttons and checkbox labels (red area is clickable).

![toolbar-click-area](https://user-images.githubusercontent.com/3692/38449494-bb607a9a-39c4-11e8-8d78-b880b71a43ce.png)

---

Button to clear searches

![toolbar-clear-button](https://user-images.githubusercontent.com/3692/38449495-bb7fb1bc-39c4-11e8-86da-367e59e54d12.png)

</details>

<details>
  <summary>Inspector</summary>

Consistent alignment and spacing. More whitespace.

![inspector](https://user-images.githubusercontent.com/3692/38449605-da2c847c-39c5-11e8-97ed-f00ac2f175b5.png)

</details>

<details>
  <summary>Navigation</summary>

New icons are consistent in style and weight.

![navigation](https://user-images.githubusercontent.com/3692/38449629-2830cc32-39c6-11e8-8b9c-10a4c328357e.png)

</details>

<details>
  <summary>Full Page Screenshots</summary>

Easiest to see if you open each image in a tab and toggle between the two.

![all old](https://user-images.githubusercontent.com/3692/38449659-a6816376-39c6-11e8-9b07-3f2c90e903d3.png)

![all new](https://user-images.githubusercontent.com/3692/38449660-a6a3d884-39c6-11e8-94d3-3c1c6f7e15f5.png)

</details>

**Comment by rwwagner90** [comment]
This stuff looks awesome!

**Comment by rwwagner90** [comment]
@nummi is there a PR for this?
