### ISSUE TITLE
Unable to traverse some ember data relationships in the Inspector

### ISSUE THREAD

**Issue by christophermlne** [emberjs/ember-inspector#791]
Looking at the screenshot of the ember inspector UI, I can click through the `ancestors` relationship, but not any of the others that are identified as `<DS.PromiseObject:...>` or `<DS.PromiseManyArray:...>`. Clicking on those relationships causes the warning included below to be printed to the console.

**Screenshot:**  
![image](https://user-images.githubusercontent.com/1007981/39329907-cecdaa22-496d-11e8-8939-665d10ac6ec8.png)

__Console warning that results from clicking on the DS.Promise relationships__
```
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Assertion Failed: You attempted to access the `_debugInfo` property (of <DS.PromiseObject:ember2256>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. **However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('_debugInfo')` in this case.**
```

__Info__
```
Ember Inspector | 3.0.0
Ember | 3.1.0
Ember Data | 3.1.1
jQuery | 3.3.1
Ember Simple Auth | 1.6.0
Ember Paper  | 1.0.0-beta.4
Model Fragments | 3.0.0


```

**Comment by rwwagner90** [comment]
Hi @christophermlne, thanks for letting us know about this. It looks like the issue is here https://github.com/emberjs/ember-inspector/blob/d865fec15690103f1c58739546b31a056bb79e15/ember_debug/object-inspector.js#L704

Would you be interested in working on a fix?

**Comment by christophermlne** [comment]
@rwwagner90 I will have a look at it tonight after work and report back
