### ISSUE TITLE
Data tab - change visible columns not working

### ISSUE THREAD

**Issue by IgorKvasn** [emberjs/ember-inspector#803]
In "Data" tab when I change visible columns, it looks like columns are added/removed, but data in the table are still the same. 

E.g. in the example below, when I hide ID column, it looks like just header is removed - data in the table are still showing "ID" column

![ember-inspector](https://user-images.githubusercontent.com/2052652/39802410-3ed391ba-536e-11e8-9077-796f836ea448.gif)

**Comment by thorsteinsson** [comment]
This is not limited to the data tab, it happens in all lists.

**Comment by rwwagner90** [comment]
@thorsteinsson would you have time to investigate a fix for this? I'm on vacation until Monday.

**Comment by thorsteinsson** [comment]
I was also on a vacation until today, I can take a look at this on Wednesday.

**Comment by Bestra** [comment]
I'm currently working on this.  I hope to have a PR for the solution by the end of the weekend.
