### ISSUE TITLE
Seeing failing tests on `/tests` route with Ember Inspector open

### ISSUE THREAD

**Issue by cafreeman** [emberjs/ember-inspector#816]
When running the tests in an Ember app using the `/tests` route, I'm seeing tests fail as a result of Ember Inspector's `getOwner` function throwing an exception (specifically, [this line](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/main.js#L164)).

After digging into the stack trace for a bit, it appears that one of Ember Inspector's initializers ([this one](https://github.com/emberjs/ember-inspector/blob/1aa8f03e1f00a6166042b61914a0ccdf03a4512b/ember_debug/vendor/startup-wrapper.js#L119-L138)) is falling over when the second test in the suite beings (so, presumably when `application.reset` is being called).

It almost seems like my application instance isn't even getting passed into the initializer, so that when Ember Inspector tries to call methods on it, it immediately fails.

Have you ever run into this before, or do you have any ideas about what might be causing this?

**Comment by rwwagner90** [comment]
@cafreeman I can't say that I have had Inspector open while running tests before. It seems like `application.__deprecatedInstance__` would be something we would want to get away from though, as it looks very private and deprecated.

@teddyzeenny @rwjblue any ideas on alternatives?
