### ISSUE TITLE
CPU spiking

### ISSUE THREAD

**Issue by davewasmer** [emberjs/ember-inspector#817]
Seeing consistently spiked CPU usage from this extension:

![image](https://user-images.githubusercontent.com/707213/40850936-277fcfd4-6583-11e8-8eda-3fa94a7223eb.png)

I suspect it's related to https://bugs.chromium.org/p/chromium/issues/detail?id=848210, since it seems like there is a synchronous XHR request happening [here](https://github.com/emberjs/ember-inspector/blob/e3023ae9bc73f8fa4abedf5fe4980cf15dd5fe8e/app/adapters/web-extension.js#L121). FWIW, the Ghostery extension [had the same issue](https://github.com/ghostery/ghostery-extension/issues/11) and just published a fix for it, though I can't seem to track down what the actual fix was.

**Comment by rwwagner90** [comment]
I'm not very familiar with developing Chrome extensions. Would you be interested in helping determine a fix @davewasmer?

**Comment by davewasmer** [comment]
Not much experience here either. And the Ghostery git history is confusing - I dunno if there is some closed source stuff going on, but AFAICT, the patched release just updated the changelog.

I'd say potentially try to make the XHR request async (I have no idea what the context is for it though, so not sure if that's feasible). If not, then maybe just wait for Chrome to patch - I doubt they will sit on it long. If anything this issue might at least help others who come searching.

**Comment by rwwagner90** [comment]
@teddyzeenny @thorsteinsson Any ideas? You guys would know more about dealing with Chrome extensions than I would, I think.

**Comment by john-kurkowski** [comment]
[Ghostery's fix](https://github.com/ghostery/ghostery-extension/commit/7fa0d7ba1c213ca2a79ad7865346bb4e007ed85e) updated their dependencies, in package-lock.json. The relevant change must be in there.

**Comment by john-kurkowski** [comment]
In this extension's case, it's not a Chrome-specific fix. It's a fix to not use Synchronous XHR, on the line [the OP mentioned](https://github.com/emberjs/ember-inspector/issues/817#issue-328577541). That would benefit all browsers.

Or keep using Synchronous XHR and wait for Chrome to publish a fix itself.

**Comment by rwwagner90** [comment]
I'm not sure if we need it to be synchronous or not or if we can make it async. Would anyone like to take a stab at it?

**Comment by stefanpenner** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=848210 is so serious it sounds like chrome folks are hoping to release another Chrome 67 by EOW to resolve. Fixing the above described problem.

I've opened a separate issue to track the sync XHR: https://github.com/emberjs/ember-inspector/issues/820

Given that Chrome folks will release a fix later this week. I think we can close this.
