### ISSUE TITLE
Failing in Ember 3.1

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember-inspector#818]
I'm seeing the following error in new greenfield Ember application using Ember Inspector 3.1.1:

<img width="493" alt="screen shot 2018-06-04 at 11 17 31 am" src="https://user-images.githubusercontent.com/3300/40926334-f6e6ee84-67e9-11e8-9f9a-d3e6c9f0f1ad.png">

Which is found: https://github.com/emberjs/ember-inspector/blob/02351d34b3b2a645e4ad9ced50606e3fb7486592/ember_debug/view-debug.js#L334-L336

Clearly:

<img width="321" alt="screen shot 2018-06-04 at 11 25 43 am" src="https://user-images.githubusercontent.com/3300/40926417-23fe9d18-67ea-11e8-94a2-526710143894.png">

is the problem.

I'm more than willing to help with a solution.

**Comment by rwwagner90** [comment]
Hi @jherdman thanks for reporting the issue and offering to help! I am curious how this issue has not shown up for me yet.

What versions of ember/ember-cli and related packages are you on?

**Comment by jherdman** [comment]
ember-cli: 3.1.4
ember-source: 3.1.2

I could try and put together a reproduction app if that helps?

**Comment by jherdman** [comment]
Failing app https://github.com/jherdman/ei-failure.

Clone, run the tests, and try to use the Ember Inspector.

**Comment by BryanCrotaz** [comment]
`ember-learning/guides-app` suffers from this.

**Comment by jherdman** [comment]
Definitely. Sometimes I pause the test so I can inspect the state Ember is in, especially when state seems to wildly contradict my expectations.
