### ISSUE TITLE
What's New

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#821]
A quick mockup for what we discussed in the meeting. The design and content can be anything — I'm interested in thoughts on tucking _What's New_ under the Info tab.

@rwwagner90, @pbishop16 

![info](https://user-images.githubusercontent.com/3692/41193905-2ff9702a-6bc8-11e8-90b6-2fb0f1431186.jpg)

![info-2](https://user-images.githubusercontent.com/3692/41193906-32b33968-6bc8-11e8-9fe3-4bb76f9abdd3.jpg)

**Comment by rwwagner90** [comment]
This seems like a good first step. I would like to default to showing the release notes whenever you grab a new version probably. We could just route people to that tab to handle that.

**Comment by pbishop16** [comment]
@nummi Sorry for the late replay, but this looks great.
