### ISSUE TITLE
[Feature Request] Adding Observer Breakpoints

### ISSUE THREAD

**Issue by anlumo** [emberjs/ember-inspector#827]
Hi,

I don't know if it's possible to do, but it'd be a huge help while debugging applications if I could set a breakpoint on 'whenever this specific property changes', irrespective from where in the code this change happened.

It's quite frequent that something in my model is altered to an invalid state, and I first have to hunt down where this change actually happens.

**Comment by rwwagner90** [comment]
This seems out of scope for inspector. You may want to set your own observer for debugging, and remove it afterwards.
