### ISSUE TITLE
Inspector is not detecting Ember deprecations

### ISSUE THREAD

**Issue by urbany** [emberjs/ember-inspector#833]
Just tried in a fresh `ember new` with latest release versions of all packages and as you can see, in the screenshot below, the inspector is not picking up the deprecations.

![screen shot 2018-07-20 at 15 52 25](https://user-images.githubusercontent.com/50884/43080747-5c0fdc8e-8e88-11e8-8d56-b285f94c4263.png)

**Comment by bgentry** [comment]
@urbany those specific deprecations were caused by ember-inspector itself, not your app. Maybe that's why they weren't showing up?

Those specific deprecations should be resolved now that #835 is merged (pending an actual release, of course).

**Comment by urbany** [comment]
I think this should only be closed when a new version of ember-inspector is released with your fix.
