### ISSUE TITLE
Fix intermittent promise debug test failures

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#848]
We have test failures for this test occasionally https://github.com/emberjs/ember-inspector/blob/master/tests/ember_debug/promise-debug-test.js#L162

It usually resolves itself if you rerun the build, but we, ideally, want this to pass the first time. I assume there is some kind of timing issue with the `await` and `run.later` of other tests, which ends up setting the `message` to the wrong one for the test, if run in a certain order.

**Comment by rwwagner90** [comment]
@Bestra @nummi @pbishop16 does anyone have some spare cycles to look into this? I tried to debug it for a bit, but did not find a fix.

**Comment by Bestra** [comment]
@rwwagner90 I'll timebox an hour or so tomorrow to see what I can see and take some notes if I make any progress.

**Comment by rwwagner90** [comment]
We will remove this test, since it is unreliable, and cannot be trusted.
