### ISSUE TITLE
 Cannot read property 'eachAttribute' of undefined

### ISSUE THREAD

**Issue by shanekoss** [emberjs/ember-inspector#851]
Seemingly all of a sudden I get this error in the inspector when trying to get info on any model.

Routes and components are fine.  

I commented out all unloadAll, unloadRecord, but still no change (previous reports suggested this could be a cause)

Going back to previous commits where the inspector was definitely working has no effect - even a clean installation doesn't work.  

Any ideas?

Thanks!

VM70:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'eachAttribute' of undefined
Stack trace: TypeError: Cannot read property 'eachAttribute' of undefined
    at _debugInfo (http://localhost:4200/assets/vendor.js:141199:10)
    at getDebugInfo (<anonymous>:3359:19)
    at Class.mixinsForObject (<anonymous>:2993:23)
    at Class.sendObject (<anonymous>:2885:26)
    at Class.inspectModel (<anonymous>:721:37)
    at sendEvent (http://localhost:4200/assets/vendor.js:33705:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:49701:33)
    at wrap (<anonymous>:3461:14)
    at Class.<anonymous> (<anonymous>:3491:18)
    at Backburner._run (http://localhost:4200/assets/vendor.js:21289:35)

**Comment by rwwagner90** [comment]
Could you please share some code, so we can see what is causing this?

**Comment by shanekoss** [comment]
Thanks for the quick reply!  Shall I email you a link to the repo?

**Comment by lougreenwood** [comment]
I'm getting it too, guessing it's an issue in inspector 3.3.0, only started noticing it today...

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'eachAttribute' of undefined
Stack trace: TypeError: Cannot read property 'eachAttribute' of undefined
    at _debugInfo (https://enhanced.cpdpro.localhost:8443/assets/vendor.js:248220:10)
    at getDebugInfo (<anonymous>:3359:19)
    at Class.mixinsForObject (<anonymous>:2993:23)
    at Class.sendObject (<anonymous>:2885:26)
    at Class.inspectModel (<anonymous>:721:37)
    at sendEvent (https://enhanced.cpdpro.localhost:8443/assets/vendor.js:43392:20)
    at Class.trigger (https://enhanced.cpdpro.localhost:8443/assets/vendor.js:54017:33)
    at wrap (<anonymous>:3461:14)
    at Class.<anonymous> (<anonymous>:3491:18)
    at Backburner._run (https://enhanced.cpdpro.localhost:8443/assets/vendor.js:32580:35)
```

```
Ember Inspector | 3.3.0
-- | --
Ember | 3.3.1
Ember Data | 3.1.1
```

**Comment by corrspt** [comment]
Same here, just seems to not read any model I throw at it. I did try installing 3.2 but without success by following the tutorials google provided me, any tips? :) @shanekoss

**Comment by metzelhoff** [comment]
@corrspt Have a look [here at the installation instructions.](https://github.com/emberjs/ember-inspector/tree/v3.2.0#chrome) I was having this issue with v3.3.0 in Chrome, so I just installed v3.2.0 locally and it is working as @lougreenwood said.

**Comment by rwwagner90** [comment]
@shanekoss @lougreenwood can either of you point me to a site I can inspect where this happens?

**Comment by rwwagner90** [comment]
Never mind, I found one. Currently debugging.

**Comment by rwwagner90** [comment]
Just kidding, I am stuck. Does someone have the bandwidth to help with this? The only changes around debugInfo were this https://github.com/emberjs/ember-inspector/commit/309d52cb5b427420a1c4d5e7418252461ffdb9b7

**Comment by rwwagner90** [comment]
Figured it out, we needed to `bind` to get the correct `this`. PR incoming.

**Comment by nolman** [comment]
Any ETA on publishing the fix to the chrome web store?

**Comment by rwwagner90** [comment]
@nolman we're working on it. @teddyzeenny will do it today.

**Comment by teddyzeenny** [comment]
Already published, this should be fixed now.

**Comment by corrspt** [comment]
Just want to say thanks. The time-to-debug-fix-and-deploy was incredible :) @teddyzeenny @rwwagner90 
 
And I learned how to install this locally as well 👍

**Comment by rwwagner90** [comment]
You're welcome @corrspt! Now that you know how to run locally, we'd love your help developing inspector! 😉

**Comment by corrspt** [comment]
@rwwagner90 Man, you don't know the guilty feeling I sometimes have for not contributing back enough. As the sole developer of a two-man boostrapped startup (who uses a lot of open source) and father to a 9 month old son... time for open-source is so hard to find 😢 . But I hear you.

I do try to provide good issue reports if I can (twiddle, reproduction repo, anything I can) when those issues appear.
