### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by nightire** [emberjs/ember-inspector#864]
During development of a new add-on, I noticed an error that caused by ember-inspector.

In order to help solve this issue more effectively, I prepare a reproduction repo at: https://github.com/very-geek/ember-plyr

Follow these steps to reproduce:

1. `npm install`
2. `ember serve`
3. open `http://localhost:4200/tests`
  at this stage, all tests should be passed
4. open chrome devtools (assuming using google chrome)
5. switch to ember inspector tab
6. refresh page
  now you should see the error, and some test cases should fail:

```
VM10735:2371 Uncaught TypeError: Cannot read property 'send' of undefined
    at Class.sendMessage (<anonymous>:2371:23)
    at Class.sendCount (<anonymous>:842:12)
    at invoke (backburner.js:249)
    at Queue.flush (backburner.js:167)
    at DeferredActionQueues.flush (backburner.js:326)
    at Backburner._end (backburner.js:748)
    at Backburner.end (backburner.js:513)
    at Backburner._runExpiredTimers (backburner.js:851)
```

**Comment by nlfurniss** [comment]
Error happens [here](https://github.com/emberjs/ember-inspector/blob/824e95333a2536972d28c429527a66048e8ef8bb/ember_debug/mixins/port-mixin.js#L22) when at some point `this.get('port')` is undefined

**Comment by thorsteinsson** [comment]
Thanks for creating a reproduction repo, it helped me track it down quickly.
