### ISSUE TITLE
Custom Component Support

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#870]
Inspector currently doesn't do a great job of supporting custom components, tagless components, etc. This issue should serve as a place for us to discuss how we want to support everything, how it should look, and how we get one nice cohesive experience for all the things.

**Comment by nummi** [comment]
Template-only component:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/3692/50988525-bb972800-14c1-11e9-87e4-19a2085c9b57.png">

Component used with angle bracket syntax:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/3692/50988973-fcdc0780-14c2-11e9-9bed-a6eb29a18f85.png">

**Comment by nummi** [comment]
There are many ways a component can be used in a template — do we want to support them all? I would say yes, we want to mirror what the developer typed.

![image](https://user-images.githubusercontent.com/3692/51348498-c0c31c80-1a57-11e9-85e0-2695a1feeaf6.png)

**Comment by chancancode** [comment]
Should be fixed by #1088 in the next release.
