### ISSUE TITLE
Replace Inspect Ember Component Icon with Ember "e"

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#871]
We currently use the Tomster logo, but it is small and hard to tell what it is. The "e" logo would also match favicons from other Ember sites.

**Comment by nummi** [comment]
We have one in the project (`public/images`) but it is very low resolution. Maybe we could get a better one and use that? Vue seems to have a higher res' icon.

<img width="159" alt="screen shot 2018-09-28 at 9 01 10 am" src="https://user-images.githubusercontent.com/3692/46219791-1e8ef580-c2fd-11e8-96c6-f52e49ce7716.png">

**Comment by rwwagner90** [comment]
@nummi yeah, I was also thinking we should do the "e" without the square background.

**Comment by dipil-saud** [comment]
@rwwagner90 Having been using this extension for a long time now, It'd be great to contribute to it, so I'd like to take this up.
The ember brand guidelines has 3 types of icons defined for the minimal icons. Do we want to go with one of these or something modified?
![image](https://user-images.githubusercontent.com/672476/46718032-a96ed900-cc89-11e8-87c3-6154ccf40ade.png)
Using the e without the square background is also a good idea but we'll need to make the e orange in that case.

**Comment by nummi** [comment]
My vote is for the rounded square.

**Comment by nummi** [comment]
Also while we're tinkering with that icon maybe we could improve on the icon in the Firefox developer tab?

**Comment by dipil-saud** [comment]
Samples
![ember-inspector](https://user-images.githubusercontent.com/672476/46796800-363e9300-cd6d-11e8-9d82-76520c46b71e.png)

**Comment by rwwagner90** [comment]
@dipil-saud I think I like the circle. I feel like an "e" with no background could look good too, but as you mentioned, that is not in the recommended assets to use.

@locks any suggestions or preferences here?

**Comment by locks** [comment]
I think I'm partial to the square out of familiarity, but as long as it is one of the options from the branding page, I am ok with it 😁

**Comment by rwwagner90** [comment]
@dipil-saud feel free to pick whichever you prefer and open a PR 😄
