### ISSUE TITLE
Ember inspector is causing errors with service workers

### ISSUE THREAD

**Issue by siwalikm** [emberjs/ember-inspector#880]
Getting the following error when using service workers if Ember chrome inspector is present in browser.
`Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported at sw.js`
![image](https://user-images.githubusercontent.com/20061595/47609357-83ec1880-da5a-11e8-96a9-6908e4ad73c9.png)

**Comment by rwwagner90** [comment]
@siwalikm we are going to need more info here. I do not see this error using service workers myself. Can you provide a url to a site where we can reproduce the error?

**Comment by siwalikm** [comment]
Hi @rwwagner90 ,  please check [this website url](https://elegant-perlman-615767.netlify.com/) to reproduce the issue. Check console log for the sw.js error which goes away on disabling ember inspector.

**Comment by rwwagner90** [comment]
@siwalikm Is this not an error with your service worker code? Shouldn't it not run on chrome extensions?

**Comment by siwalikm** [comment]
Is it? @rwwagner90 I'm new to sw.js. Could you please help me understand why I'm facing this issue and why the error goes away when ember inspector is disabled?

**Comment by rwwagner90** [comment]
@siwalikm So chrome extensions run content scripts when you load pages, and it appears your service worker is trying to run on the chrome extension, it should not do that.

If you go to https://shipshape.io/ you can see I register a service worker there, but there is no error thrown, so it's something specific to your service worker I think.
