### ISSUE TITLE
3.3.2: this.eachAttribute is not a function

### ISSUE THREAD

**Issue by slisznia** [emberjs/ember-inspector#890]
I'm playing with Ember Inspector and I'm getting the error (screenshot below) in both Firefox and Chrome. The model is trivial:

```
export default Route.extend({
	model() {
		this.store.pushPayload({
			data: [
				{ 
					type: "packet",
					id: "p1",
					attributes: {
						"family-name": "Smith",
						"alias": "Smithy",
					},
					relationships: {
						"primary-residency": {
							"data": { "id": "a1", "type": "postal-addresses" }
						}
					}
				}
			],
			included: [
				{
					type: "postal-address",
					id: "a1",
					attributes: {
						"street": "12 Mulholland Dr",
						"apt": "4c",
						"city": "Los Angeles",
						"zip-code": "90102",
						"state": "CA"
					}
				},
				{
					type: "postal-address",
					id: "a2",
					attributes: {
						"street": "475 Winchester St.",
						"apt": null,
						"city": "Saginaw",
						"zip-code": "48601",
						"state": "MI"
					}
				}
			]
		});
		return this.store.peekRecord('packet', 'p1');
	}
});
```

![infodeqpilot - google chrome_072](https://user-images.githubusercontent.com/1666246/49491512-14680680-f81a-11e8-9e1d-7e5cfa2cd503.png)

**Comment by wukongrita** [comment]
Beside that, the label should be "Belongs To" and "Has Many"; not the first relation model name:

<img width="545" alt="screen shot 2019-01-14 at 14 30 03" src="https://user-images.githubusercontent.com/25361005/51100497-f625fb00-1808-11e9-90b8-cca72832751d.png">

here is what to be expected (I took the screenshot with the lower ember.js version):

<img width="561" alt="screen shot 2019-01-14 at 14 30 21" src="https://user-images.githubusercontent.com/25361005/51100510-03db8080-1809-11e9-95ab-ed7b5dbe1da1.png">

**Comment by rwwagner90** [comment]
@wukongrita that seems like a separate issue. Do you mind filing a new issue with steps to reproduce that?

**Comment by rwwagner90** [comment]
@slisznia @wukongrita do either of you have reproductions of these issues we could play with?

**Comment by rwwagner90** [comment]
Having heard nothing back about this, I am going to close for now. Please feel free to reopen, if you are still experiencing issues!
