### ISSUE TITLE
Table's area sizing issue

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember-inspector#892]
version:
![image](https://user-images.githubusercontent.com/1360552/49719937-a84d2e80-fc6f-11e8-90c6-8b7d54fe387b.png)

issues:

![image](https://user-images.githubusercontent.com/1360552/49719985-c7e45700-fc6f-11e8-9b67-831061e7a81b.png)

![image](https://user-images.githubusercontent.com/1360552/49720082-f3674180-fc6f-11e8-910d-4291040de1e2.png)

![image](https://user-images.githubusercontent.com/1360552/49720127-12fe6a00-fc70-11e8-92e0-462869821d16.png)

Tables has 1/2 of available height.

Data & Components tabs looks good:
![image](https://user-images.githubusercontent.com/1360552/49720274-6ec8f300-fc70-11e8-9364-bb7d84dc5d16.png)

![image](https://user-images.githubusercontent.com/1360552/49720304-80aa9600-fc70-11e8-8606-4fd61a569b73.png)

**Comment by rwwagner90** [comment]
I think we should be able to fix this by using ember-table for all the tables. Will try to get to that soon.

**Comment by rwwagner90** [comment]
@nummi since we are stuck on the ember-table stuff for now, is there something we can do to make sure the tables size correctly for now?

**Comment by nummi** [comment]
I will take a stab at it. Do we have a consistent way of reproducing the bug?

**Comment by lifeart** [comment]
@nummi yeah, try to open https://emberjs.com/api/ember/release
with Ember-inspector, having 25% size 
![image](https://user-images.githubusercontent.com/1360552/50730094-20672100-1156-11e9-8247-e39835904700.png)

after full-size it and go to `routes` section

![image](https://user-images.githubusercontent.com/1360552/50730100-4a204800-1156-11e9-8715-bbd34a782a01.png)

**Comment by nummi** [comment]
Looks like the height of the table is set manually. There is a window resize event listener that is supposed to keep it up to date but only seems to fire once. I'm not really sure why all this is necessary, shouldn't the table just take up 100% of the available height?

**Comment by lifeart** [comment]
@nummi in some pages tables broken, but "Data" looks ok

**Comment by rwwagner90** [comment]
@nummi I think making it 100% height sounds logical. I'm not sure why it's not done like that.
