### ISSUE TITLE
Chrome Store Extension page refers to old repo.

### ISSUE THREAD

**Issue by deanmarano** [emberjs/ember-inspector#893]
https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi refers to this repo being under tildeio (https://github.com/tildeio/ember-extension).

Also, with the icon change, it might make sense to change the logo in the Chrome Store as well.

**Comment by rwwagner90** [comment]
Totally agree @deanmarano. I'm hoping to get some style advice from @nummi about what tile images and icons we want to use, and I will also update the url and the other info as needed.

**Comment by nummi** [comment]
- [ ] Update Github repo link at the bottom of the Chrome Store description.
- [ ] Update tile image on Chrome Store search listing

Who has credentials for the listing on the Chrome store?

**Comment by nummi** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/3692/49849510-c6f61700-fd8e-11e8-8f83-4e534ccbe91f.png">

---

<img width="966" alt="image" src="https://user-images.githubusercontent.com/3692/49849525-d37a6f80-fd8e-11e8-9622-62af71c5e318.png">

**Comment by rwwagner90** [comment]
@nummi I've got credentials. I like the tile with the orange background, makes us stand out from all the other ones that are just using their icon.

**Comment by nummi** [comment]
![ember](https://user-images.githubusercontent.com/3692/49885793-005d6f80-fded-11e8-9f67-8a47ab9357dd.png)
@rwwagner90

**Comment by rwwagner90** [comment]
Just updated both things 👍
