### ISSUE TITLE
Ember inspector watching non-ember properties causes error.

### ISSUE THREAD

**Issue by argote** [emberjs/ember-inspector#897]
Error:

`You must use set() to set the `animationTask` property (of <dummy@component:sq-field-input-searchable/input-element::ember296>) to `[object Object]`.`

This is happening because the values are being observed by the Ember Inspector and therefore the property must be set through `.set`. https://discuss.emberjs.com/t/ember-1-8-you-must-use-ember-set-to-set-the-property/6582

**Comment by rwwagner90** [comment]
Hi @argote do you have a reproduction of this we could take a look at?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
