### ISSUE TITLE
Decorated model properties don't show in object-inspector column

### ISSUE THREAD

**Issue by HodofHod** [emberjs/ember-inspector#903]
Model properties that are defined using ES6 classes and ember-decorators don't show in the detailed object-inspector sidebar, but they *do* show in the table view.

[Codesandbox Repro](https://codesandbox.io/embed/3qlwvyq926)

```js
import DS from "ember-data";
import { attr } from "@ember-decorators/data";

export default class User extends DS.Model.extend({
  bar: DS.attr("string")
}) {
  @attr("string") foo;
  baz = DS.attr("string");
}

```
![image](https://user-images.githubusercontent.com/1865736/50492026-3735a700-09e3-11e9-8ced-f93d62c102c2.png)

**Comment by lifeart** [comment]
May be related to https://github.com/emberjs/ember-inspector/issues/943

**Comment by rwwagner90** [comment]
I believe this may have been fixed by https://github.com/emberjs/ember-inspector/pull/1006 would you guys mind trying it out please? 😃

**Comment by lifeart** [comment]
https://github.com/emberjs/ember-inspector/issues/943#issuecomment-522924712

**Comment by rwwagner90** [comment]
Considering this fixed, since the other issue was fixed. If it is not fixed after the release, please let us know!
