### ISSUE TITLE
Removal of View Tab

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#923]
Place for discussion around removal of the View Tab.

## Todo

- [x] Make Components Tab default route
- [ ] Display render performance in Components tab?

## Current View Tab Functionality

1. **List of components** 
	- ☑️ covered by Components Tab
1. **Template path**
	- _click to view element in browser Elements panel_
	- ☑️ covered by Routes and Components tab
1. **Model**
	- _open in object inspector or send to console_
	- 🤷🏽‍♀️ I believe this is the model of the controller which can be accessed from the Routes Tab by selecting a controller and finding the model in the object inspector. This adds more clicks.
1. **Controller**
	- _open in object inspector or send to console_
	- ☑️ covered by Routes Tab
1. **Render times**
	- ☑️ covered by Performance Tab
	- We could also include this in the Components Tab (I'm not sure how useful this information is on a regular basis)

**Comment by rwjblue** [comment]
Awesome, thank you for putting this together!

**Comment by wycats** [comment]
re: performance tab -- it was nice to be able to see the latest render time right next to the view without digging into more lists, but I think it would just be fine to add it to the component.

Secondly, and only tangentially relatd, what would be needed to add the invocation arguments to the components tab?

**Comment by rwjblue** [comment]
totally agreed on both counts, we already have an issue open RE: fixing up the display of custom components on the components tab and I think as part of that effort we will likely also try to add invocation arguments (at _least_ the names of the arguments, if not the current values)

**Comment by wycats** [comment]
It seems like it would be possible to snapshot the ARGS references and peek at them if the user clicks on the argument slot, right?

**Comment by nummi** [comment]
@wycats Something like this?
https://codepen.io/nummi/details/mvJwbq

**Comment by nummi** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/3692/52181846-5e824f80-27ab-11e9-86d9-20086a90cdea.png">

**Comment by rwwagner90** [comment]
@nummi do you know if other dev tools for React, Vue, etc incorporate render times?

**Comment by nummi** [comment]
The React devtools have a _Profiler_ screen where you can see render times for components. 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/3692/52225937-7e277f80-2860-11e9-8991-3c072bccdda9.png">

The _Elements_ screen does not display this information.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/3692/52226028-b4fd9580-2860-11e9-9e20-becf87cc3745.png">

**Comment by rwwagner90** [comment]
@nummi I believe we can see all that in the normal devtools performance tab, with the addition of `ember-perf-timeline` correct? https://github.com/ember-best-practices/ember-perf-timeline

I'm unsure if we want to build this into inspector or not, but if we did, I think it would warrant a separate tab as well.

**Comment by nummi** [comment]
Closing for PR. Please continue conversation there.
