### ISSUE TITLE
getApplications(...).mapBy is not a function

### ISSUE THREAD

**Issue by exeto** [emberjs/ember-inspector#926]
Prototype extensions are disabled in my project.

Version: 3.5.0

**Comment by efx** [comment]
Seeing this when I link canary against my app. This probably came from https://github.com/emberjs/ember-inspector/pull/898 
It seems the responsible line is here:
https://github.com/emberjs/ember-inspector/blob/master/ember_debug/vendor/startup-wrapper.js#L135
I think we could change that line to `.map(item => item && item.name)`.
I can try fixing this later today or if anyone else wants to now :)
cc @alexhancock

**Comment by efx** [comment]
NVM, just figured I'd get it now. I manually tested this locally and it solved the issue. I'm curious how to stub no prototype extensions in the acceptance tests.
