### ISSUE TITLE
Setting dependency keys using the `.property()` modifier has been deprecated

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/ember-inspector#944]
In a nearly generated app, using ember 3.9 beta the app gets a deprecation message. This is coming from the inspector. If I disable the inspector, my app does not get the deprecation. 

```
deprecate.js:120 DEPRECATION: Setting dependency keys using the `.property()` modifier has been deprecated. Pass the dependency keys directly to computed as arguments instead. If you are using `.property()` on a computed property macro, consider refactoring your macro to receive additional dependent keys in its initial declaration. [deprecation id: computed-property.property] See https://emberjs.com/deprecations/v3.x#toc_computed-property-property for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:35082:23)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:35176:11)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:35109:11)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:35176:11)
        at invoke (http://localhost:4200/assets/vendor.js:35188:11)
        at deprecate (http://localhost:4200/assets/vendor.js:35147:30)
        at ComputedProperty.property (http://localhost:4200/assets/vendor.js:14960:46)
        at <anonymous>:3617:8
        at requireModule (<anonymous>:39:28)
```

In a quick search, I found a few places using `.property()`. 

https://github.com/emberjs/ember-inspector/blob/824e95333a2536972d28c429527a66048e8ef8bb/app/controllers/deprecations.js#L18-L20

https://github.com/emberjs/ember-inspector/blob/9ed9e547bfad6e6223a4d72c37679a9a79d9da72/app/controllers/container-type.js#L21-L23

https://github.com/emberjs/ember-inspector/blob/824e95333a2536972d28c429527a66048e8ef8bb/ember_debug/promise-debug.js#L82-L90

**Comment by rwwagner90** [comment]
We can likely remove the `.property` bits here. We'll look into it!

**Comment by gabz75** [comment]
Happy to work on this!

**Comment by vaidehijoshi** [comment]
👋 Hi there! I just ran into this deprecation while trying to use the inspector and happened upon this PR. I uninstalled/reinstalled the inspector only to realize that this PR hasn't actually been released yet? Any idea when it might be? It would be super helpful! 😅

**Comment by rwwagner90** [comment]
Hi @vaidehijoshi! Unfortunately, we have some bug fixes we have to get in first, and those are held up by ember-table breaking in Ember 3.9, so we're kind of in a tough spot where we have to fix some bugs, to fix some bugs, to fix some bugs. Hopefully soon though!
