### ISSUE TITLE
Editing an attributes adds quotes to the value

### ISSUE THREAD

**Issue by locks** [emberjs/ember-inspector#952]
When editing an attribute in the Inspector object side panel, quotes are added to the value being edited. If this value is then submitted, the quotes are escaped:

1. ![Screenshot 2019-04-02 at 15 21 57](https://user-images.githubusercontent.com/32344/55410124-3d47a080-555b-11e9-8624-9efa4507262f.png)
2. ![Screenshot 2019-04-02 at 15 22 01](https://user-images.githubusercontent.com/32344/55410122-3caf0a00-555b-11e9-860b-f3d99c54a39b.png)
3. ![Screenshot 2019-04-02 at 15 22 09](https://user-images.githubusercontent.com/32344/55410123-3d47a080-555b-11e9-8216-f1fba06805aa.png)

**Comment by nummi** [comment]
Do we need the quotes at all?

**Comment by locks** [comment]
That we are adding the quotes to the input field is what I consider the bug!

**Comment by rwwagner90** [comment]
It was probably intended to show the type as a string, but not sure why it is adding them.
