### ISSUE TITLE
[Feature Request] Add a way to view all observers registered on an object?

### ISSUE THREAD

**Issue by sumeetattree** [emberjs/ember-inspector#956]
It would be nice to see what observers have been added since the object's creation. It can be really tricky to debug when an observer has been created and stays past its intended duration. For eg: Attaching observers to routes are long lived as routes once created never get destroyed. So the observers are never removed. It would be very handy in these cases to quickly debug if there are observers lurking around.

Is this something you are already planning? I don't have an exact idea how this feature would work. Perhaps someone more knowledgeable about inner workings of observers could chime in?

**Comment by nummi** [comment]
Hi @sumeetattree, I believe the use of observers is generally discouraged so this feature would not be frequently used.

I suggest finding a channel in the Ember Discord chat —`#help` might be a good place — to find out if there is a way to list all observers on an object. https://discordapp.com/invite/zT3asNS

I'm going to close this Issue for now but we can keep chatting about it here.
