### ISSUE TITLE
Remove grunt for compress tasks

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#958]
We currently use grunt for some build tasks, but some of our packages are way out of date and not supported. We should modernize our build and use gulp, broccoli, rollup, etc.

**Comment by KamiKillertO** [comment]
I've some experiences with gulp, I'll have a look 👍

**Comment by KamiKillertO** [comment]
Ok so grunt compress files and publish on s3. It's not gonna be an easy thing to migrate from grunt to something else 😞. The compress tasks can be tested in local but for the s3 tasks I'm not sure how to test ><.

**Comment by rwwagner90** [comment]
The S3 tasks have actually been not working anyway. I think we should use the built in Travis functionality to upload to S3 https://docs.travis-ci.com/user/deployment/s3/
