### ISSUE TITLE
Use Travis for S3 Uploads

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-inspector#965]
Travis support deploying to S3, so rather than using grunt for this, it would be ideal to deploy directly from Travis. https://docs.travis-ci.com/user/deployment/s3/

**Comment by rwwagner90** [comment]
@teddyzeenny I need the S3 credentials. I am not sure where `config/secrets.json` is supposed to come from. Please ping me on Discord and we can get this figured out 😄

**Comment by rwwagner90** [comment]
This works now 🎉

**Comment by nummi** [comment]
🎉
